[workspace]
resolver = "2"
members = ["crates/gax-core", "crates/gax-gen", "crates/gax"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/TBD/gax"

[workspace.dependencies]
gax-core = { path = "crates/gax-core", version = "0.1.0" }
gax-gen = { path = "crates/gax-gen", version = "0.1.0" }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
many_single_char_names = "allow"
similar_names = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
must_use_candidate = "allow"
missing_panics_doc = "allow"
inline_always = "allow"

[profile.bench]
debug = true
