// @generated by gax-gen: part of `vga2d` (see ../vga2d.rs). Do not edit by hand.

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Vector<S2, T>> for Vector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Vector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                ((p(0, 1) - p(1, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Pseudoscalar<S2, T>> for Vector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Pseudoscalar<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (-p(1, 0)).0,
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Rotor<S2, T>> for Vector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Rotor<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (-p(1, 1)).0,
                (p(0, 1)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Multivector<S2, T>> for Vector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-p(1, 3)).0,
                (p(0, 3)).0,
                ((p(0, 2) - p(1, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Vector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Vector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 1)).0,
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Multivector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Multivector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 2)).0,
                (-p(0, 1)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Vector<S2, T>> for Rotor<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Vector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(1, 1)).0,
                (-p(1, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Multivector<S2, T>> for Rotor<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Multivector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(1, 2)).0,
                (-p(1, 1)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Vector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Vector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(3, 1)).0,
                (-p(3, 0)).0,
                ((p(1, 1) - p(2, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Pseudoscalar<S2, T>> for Multivector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Pseudoscalar<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (-p(2, 0)).0,
                (p(1, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Rotor<S2, T>> for Multivector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Rotor<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 2 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (-p(2, 1)).0,
                (p(1, 1)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Commutator<Multivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn commutator(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Commutator::commutator(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                ((p(3, 2) - p(2, 3))).0,
                ((p(1, 3) - p(3, 1))).0,
                ((p(1, 2) - p(2, 1))).0,
            ],
        }
    }
}
