// @generated by gax-gen: part of `vga2d` (see ../vga2d.rs). Do not edit by hand.

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Scalar<S, T>> for Vector<(), T> {
    type Output = Scalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Scalar<S, T>) -> Scalar<S, T> {
        let v = self.c;
        if let Some(xv) = gx::slots::values::<S, T, 1>(&x.c) {
        let t1 = v[1] * v[1];
        let t2 = v[0].mul_add(v[0], t1);
        let t3 = xv[0] * t2;
            return Scalar { c: gx::slots::from_values::<S, T, 1>([t3]) };
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let x = x.c.map(gx::SlotArr::<S, T>);
        Scalar { c: [(x[0].scale(m2)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Scalar<S, T>> for Vector<(), T> {
    type Output = Scalar<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Scalar<S, T>) -> Scalar<S, T> {
        gx::Transform::transform(self.reverse(), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Scalar> for Vector<(), T> {
    type Output = gx::Prepared<Vector, Scalar, T, 1>;
    #[inline]
    fn prepare(self) -> gx::Prepared<Vector, Scalar, T, 1> {
        let v = self.c;
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        gx::Prepared::from_entries([m2])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Scalar<S, T>> for gx::Prepared<Vector, Scalar, T, 1> {
    type Output = Scalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Scalar<S, T>) -> Scalar<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Scalar { c: [(x[0].scale(m[0])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<Vector, Scalar, T, 1>> for Scalar<(Scalar,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<Vector, Scalar, T, 1>) -> Self {
        let m = p.m;
        Scalar { c: [[m[0]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Scalar, gx::batch::Plain> for Vector {
    type Y = Scalar;
    type Versor<T: gx::Coef> = Vector<(), T>;
    type Prepared<T: gx::Coef> = gx::Prepared<Vector, Scalar, T, 1>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: Vector<(), T>) -> gx::Prepared<Vector, Scalar, T, 1> {
        gx::Prepare::<Scalar>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<Vector, Scalar, T, 1>, mut f: impl FnMut(T) -> W) -> gx::Prepared<Vector, Scalar, W, 1> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<Vector, Scalar, T, 1>, x: Scalar<(), T>) -> Scalar<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: Vector<(), T>, x: Scalar<(), T>) -> Scalar<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Scalar<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Scalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Scalar<S, T>) -> Scalar<S, T> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        if let Some(xv) = gx::slots::values::<S, T, 1>(&x.c) {
        let t1 = v[1] * v[1];
        let t2 = v[0].mul_add(v[0], t1);
        let t3 = xv[0] * t2;
            return Scalar { c: gx::slots::from_values::<S, T, 1>([t3]) };
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let x = x.c.map(gx::SlotArr::<S, T>);
        Scalar { c: [(x[0].scale(m2)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Scalar<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Scalar<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Scalar<S, T>) -> Scalar<S, T> {
        gx::Transform::transform(gx::Unit::new_unchecked(self.into_inner().reverse()), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Scalar> for gx::Unit<Vector<(), T>> {
    type Output = gx::Prepared<gx::Unit<Vector>, Scalar, T, 1>;
    #[inline]
    fn prepare(self) -> gx::Prepared<gx::Unit<Vector>, Scalar, T, 1> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        gx::Prepared::from_entries([m2])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Scalar<S, T>> for gx::Prepared<gx::Unit<Vector>, Scalar, T, 1> {
    type Output = Scalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Scalar<S, T>) -> Scalar<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Scalar { c: [(x[0].scale(m[0])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<gx::Unit<Vector>, Scalar, T, 1>> for Scalar<(Scalar,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<gx::Unit<Vector>, Scalar, T, 1>) -> Self {
        let m = p.m;
        Scalar { c: [[m[0]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Scalar, gx::batch::Certified> for Vector {
    type Y = Scalar;
    type Versor<T: gx::Coef> = gx::Unit<Vector<(), T>>;
    type Prepared<T: gx::Coef> = gx::Prepared<gx::Unit<Vector>, Scalar, T, 1>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> gx::Unit<Vector<(), T>> {
        gx::Unit::new_unchecked(v)
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> Vector<(), T> {
        v.into_inner()
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> gx::Prepared<gx::Unit<Vector>, Scalar, T, 1> {
        gx::Prepare::<Scalar>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Scalar, T, 1>, mut f: impl FnMut(T) -> W) -> gx::Prepared<gx::Unit<Vector>, Scalar, W, 1> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Scalar, T, 1>, x: Scalar<(), T>) -> Scalar<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: gx::Unit<Vector<(), T>>, x: Scalar<(), T>) -> Scalar<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Vector<S, T>> for Vector<(), T> {
    type Output = Vector<S, T>;
    #[inline(always)]
    fn transform(self, x: Vector<S, T>) -> Vector<S, T> {
        let v = self.c;
        if let Some(xv) = gx::slots::values::<S, T, 2>(&x.c) {
        let t0 = v[0] * v[0];
        let t2 = v[0] * v[1];
        let t3 = (-v[1]).mul_add(v[1], t0);
        let t5 = xv[1] * t2;
        let t6 = xv[0] * t2;
        let t8 = t5 * T::from_i64(2);
        let t9 = xv[0].mul_add(t3, t8);
        let t10 = t6 * T::from_i64(2);
        let t11 = (-xv[1]).mul_add(t3, t10);
            return Vector { c: gx::slots::from_values::<S, T, 2>([t9, t11]) };
        }
        let m0 = v[0] * v[0];
        let m1 = v[0] * v[1];
        let m3 = (-v[1]).mul_add(v[1], m0);
        let m4 = m1 * T::from_i64(2);
        let m5 = -m3;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Vector { c: [(x[0].scale(m3) + x[1].scale(m4)).0, (x[0].scale(m4) + x[1].scale(m5)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Vector<S, T>> for Vector<(), T> {
    type Output = Vector<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Vector<S, T>) -> Vector<S, T> {
        gx::Transform::transform(self.reverse(), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Vector> for Vector<(), T> {
    type Output = gx::Prepared<Vector, Vector, T, 3>;
    #[inline]
    fn prepare(self) -> gx::Prepared<Vector, Vector, T, 3> {
        let v = self.c;
        let m0 = v[0] * v[0];
        let m1 = v[0] * v[1];
        let m3 = (-v[1]).mul_add(v[1], m0);
        let m4 = m1 * T::from_i64(2);
        let m5 = -m3;
        gx::Prepared::from_entries([m3, m4, m5])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Vector<S, T>> for gx::Prepared<Vector, Vector, T, 3> {
    type Output = Vector<S, T>;
    #[inline(always)]
    fn transform(self, x: Vector<S, T>) -> Vector<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Vector { c: [(x[0].scale(m[0]) + x[1].scale(m[1])).0, (x[0].scale(m[1]) + x[1].scale(m[2])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<Vector, Vector, T, 3>> for Vector<(Vector,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<Vector, Vector, T, 3>) -> Self {
        let m = p.m;
        Vector { c: [[m[0], m[1]], [m[1], m[2]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Vector, gx::batch::Plain> for Vector {
    type Y = Vector;
    type Versor<T: gx::Coef> = Vector<(), T>;
    type Prepared<T: gx::Coef> = gx::Prepared<Vector, Vector, T, 3>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: Vector<(), T>) -> gx::Prepared<Vector, Vector, T, 3> {
        gx::Prepare::<Vector>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<Vector, Vector, T, 3>, mut f: impl FnMut(T) -> W) -> gx::Prepared<Vector, Vector, W, 3> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0]), f(m[1]), f(m[2])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<Vector, Vector, T, 3>, x: Vector<(), T>) -> Vector<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: Vector<(), T>, x: Vector<(), T>) -> Vector<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Vector<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Vector<S, T>;
    #[inline(always)]
    fn transform(self, x: Vector<S, T>) -> Vector<S, T> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        if let Some(xv) = gx::slots::values::<S, T, 2>(&x.c) {
        let t0 = v[0] * v[0];
        let t2 = v[0] * v[1];
        let t3 = (-v[1]).mul_add(v[1], t0);
        let t5 = xv[1] * t2;
        let t6 = xv[0] * t2;
        let t8 = t5 * T::from_i64(2);
        let t9 = xv[0].mul_add(t3, t8);
        let t10 = t6 * T::from_i64(2);
        let t11 = (-xv[1]).mul_add(t3, t10);
            return Vector { c: gx::slots::from_values::<S, T, 2>([t9, t11]) };
        }
        let m0 = v[0] * v[0];
        let m1 = v[0] * v[1];
        let m3 = (-v[1]).mul_add(v[1], m0);
        let m4 = m1 * T::from_i64(2);
        let m5 = -m3;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Vector { c: [(x[0].scale(m3) + x[1].scale(m4)).0, (x[0].scale(m4) + x[1].scale(m5)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Vector<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Vector<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Vector<S, T>) -> Vector<S, T> {
        gx::Transform::transform(gx::Unit::new_unchecked(self.into_inner().reverse()), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Vector> for gx::Unit<Vector<(), T>> {
    type Output = gx::Prepared<gx::Unit<Vector>, Vector, T, 3>;
    #[inline]
    fn prepare(self) -> gx::Prepared<gx::Unit<Vector>, Vector, T, 3> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        let m0 = v[0] * v[0];
        let m1 = v[0] * v[1];
        let m3 = (-v[1]).mul_add(v[1], m0);
        let m4 = m1 * T::from_i64(2);
        let m5 = -m3;
        gx::Prepared::from_entries([m3, m4, m5])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Vector<S, T>> for gx::Prepared<gx::Unit<Vector>, Vector, T, 3> {
    type Output = Vector<S, T>;
    #[inline(always)]
    fn transform(self, x: Vector<S, T>) -> Vector<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Vector { c: [(x[0].scale(m[0]) + x[1].scale(m[1])).0, (x[0].scale(m[1]) + x[1].scale(m[2])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<gx::Unit<Vector>, Vector, T, 3>> for Vector<(Vector,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<gx::Unit<Vector>, Vector, T, 3>) -> Self {
        let m = p.m;
        Vector { c: [[m[0], m[1]], [m[1], m[2]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Vector, gx::batch::Certified> for Vector {
    type Y = Vector;
    type Versor<T: gx::Coef> = gx::Unit<Vector<(), T>>;
    type Prepared<T: gx::Coef> = gx::Prepared<gx::Unit<Vector>, Vector, T, 3>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> gx::Unit<Vector<(), T>> {
        gx::Unit::new_unchecked(v)
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> Vector<(), T> {
        v.into_inner()
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> gx::Prepared<gx::Unit<Vector>, Vector, T, 3> {
        gx::Prepare::<Vector>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Vector, T, 3>, mut f: impl FnMut(T) -> W) -> gx::Prepared<gx::Unit<Vector>, Vector, W, 3> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0]), f(m[1]), f(m[2])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Vector, T, 3>, x: Vector<(), T>) -> Vector<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: gx::Unit<Vector<(), T>>, x: Vector<(), T>) -> Vector<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Pseudoscalar<S, T>> for Vector<(), T> {
    type Output = Pseudoscalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Pseudoscalar<S, T>) -> Pseudoscalar<S, T> {
        let v = self.c;
        if let Some(xv) = gx::slots::values::<S, T, 1>(&x.c) {
        let t1 = v[1] * v[1];
        let t2 = v[0].mul_add(v[0], t1);
        let t3 = xv[0] * t2;
        let t4 = -t3;
            return Pseudoscalar { c: gx::slots::from_values::<S, T, 1>([t4]) };
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Pseudoscalar { c: [(x[0].scale(m3)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Pseudoscalar<S, T>> for Vector<(), T> {
    type Output = Pseudoscalar<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Pseudoscalar<S, T>) -> Pseudoscalar<S, T> {
        gx::Transform::transform(self.reverse(), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Pseudoscalar> for Vector<(), T> {
    type Output = gx::Prepared<Vector, Pseudoscalar, T, 1>;
    #[inline]
    fn prepare(self) -> gx::Prepared<Vector, Pseudoscalar, T, 1> {
        let v = self.c;
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        gx::Prepared::from_entries([m3])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Pseudoscalar<S, T>> for gx::Prepared<Vector, Pseudoscalar, T, 1> {
    type Output = Pseudoscalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Pseudoscalar<S, T>) -> Pseudoscalar<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Pseudoscalar { c: [(x[0].scale(m[0])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<Vector, Pseudoscalar, T, 1>> for Pseudoscalar<(Pseudoscalar,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<Vector, Pseudoscalar, T, 1>) -> Self {
        let m = p.m;
        Pseudoscalar { c: [[m[0]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Pseudoscalar, gx::batch::Plain> for Vector {
    type Y = Pseudoscalar;
    type Versor<T: gx::Coef> = Vector<(), T>;
    type Prepared<T: gx::Coef> = gx::Prepared<Vector, Pseudoscalar, T, 1>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: Vector<(), T>) -> gx::Prepared<Vector, Pseudoscalar, T, 1> {
        gx::Prepare::<Pseudoscalar>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<Vector, Pseudoscalar, T, 1>, mut f: impl FnMut(T) -> W) -> gx::Prepared<Vector, Pseudoscalar, W, 1> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<Vector, Pseudoscalar, T, 1>, x: Pseudoscalar<(), T>) -> Pseudoscalar<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: Vector<(), T>, x: Pseudoscalar<(), T>) -> Pseudoscalar<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Pseudoscalar<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Pseudoscalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Pseudoscalar<S, T>) -> Pseudoscalar<S, T> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        if let Some(xv) = gx::slots::values::<S, T, 1>(&x.c) {
        let t0 = -xv[0];
        let t2 = v[1] * v[1];
        let t3 = v[0].mul_add(v[0], t2);
        let t4 = t0 * t3;
            return Pseudoscalar { c: gx::slots::from_values::<S, T, 1>([t4]) };
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Pseudoscalar { c: [(x[0].scale(m3)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Pseudoscalar<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Pseudoscalar<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Pseudoscalar<S, T>) -> Pseudoscalar<S, T> {
        gx::Transform::transform(gx::Unit::new_unchecked(self.into_inner().reverse()), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Pseudoscalar> for gx::Unit<Vector<(), T>> {
    type Output = gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1>;
    #[inline]
    fn prepare(self) -> gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        gx::Prepared::from_entries([m3])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Pseudoscalar<S, T>> for gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1> {
    type Output = Pseudoscalar<S, T>;
    #[inline(always)]
    fn transform(self, x: Pseudoscalar<S, T>) -> Pseudoscalar<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Pseudoscalar { c: [(x[0].scale(m[0])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1>> for Pseudoscalar<(Pseudoscalar,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1>) -> Self {
        let m = p.m;
        Pseudoscalar { c: [[m[0]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Pseudoscalar, gx::batch::Certified> for Vector {
    type Y = Pseudoscalar;
    type Versor<T: gx::Coef> = gx::Unit<Vector<(), T>>;
    type Prepared<T: gx::Coef> = gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> gx::Unit<Vector<(), T>> {
        gx::Unit::new_unchecked(v)
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> Vector<(), T> {
        v.into_inner()
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1> {
        gx::Prepare::<Pseudoscalar>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1>, mut f: impl FnMut(T) -> W) -> gx::Prepared<gx::Unit<Vector>, Pseudoscalar, W, 1> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Pseudoscalar, T, 1>, x: Pseudoscalar<(), T>) -> Pseudoscalar<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: gx::Unit<Vector<(), T>>, x: Pseudoscalar<(), T>) -> Pseudoscalar<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Rotor<S, T>> for Vector<(), T> {
    type Output = Rotor<S, T>;
    #[inline(always)]
    fn transform(self, x: Rotor<S, T>) -> Rotor<S, T> {
        let v = self.c;
        if let Some(xv) = gx::slots::values::<S, T, 2>(&x.c) {
        let t1 = v[1] * v[1];
        let t2 = v[0].mul_add(v[0], t1);
        let t3 = xv[0] * t2;
        let t4 = xv[1] * t2;
        let t5 = -t4;
            return Rotor { c: gx::slots::from_values::<S, T, 2>([t3, t5]) };
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Rotor { c: [(x[0].scale(m2)).0, (x[1].scale(m3)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Rotor<S, T>> for Vector<(), T> {
    type Output = Rotor<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Rotor<S, T>) -> Rotor<S, T> {
        gx::Transform::transform(self.reverse(), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Rotor> for Vector<(), T> {
    type Output = gx::Prepared<Vector, Rotor, T, 2>;
    #[inline]
    fn prepare(self) -> gx::Prepared<Vector, Rotor, T, 2> {
        let v = self.c;
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        gx::Prepared::from_entries([m2, m3])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Rotor<S, T>> for gx::Prepared<Vector, Rotor, T, 2> {
    type Output = Rotor<S, T>;
    #[inline(always)]
    fn transform(self, x: Rotor<S, T>) -> Rotor<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Rotor { c: [(x[0].scale(m[0])).0, (x[1].scale(m[1])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<Vector, Rotor, T, 2>> for Rotor<(Rotor,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<Vector, Rotor, T, 2>) -> Self {
        let m = p.m;
        Rotor { c: [[m[0], T::zero()], [T::zero(), m[1]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Rotor, gx::batch::Plain> for Vector {
    type Y = Rotor;
    type Versor<T: gx::Coef> = Vector<(), T>;
    type Prepared<T: gx::Coef> = gx::Prepared<Vector, Rotor, T, 2>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: Vector<(), T>) -> gx::Prepared<Vector, Rotor, T, 2> {
        gx::Prepare::<Rotor>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<Vector, Rotor, T, 2>, mut f: impl FnMut(T) -> W) -> gx::Prepared<Vector, Rotor, W, 2> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0]), f(m[1])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<Vector, Rotor, T, 2>, x: Rotor<(), T>) -> Rotor<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: Vector<(), T>, x: Rotor<(), T>) -> Rotor<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Rotor<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Rotor<S, T>;
    #[inline(always)]
    fn transform(self, x: Rotor<S, T>) -> Rotor<S, T> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        if let Some(xv) = gx::slots::values::<S, T, 2>(&x.c) {
        let t0 = -xv[1];
        let t2 = v[1] * v[1];
        let t3 = v[0].mul_add(v[0], t2);
        let t4 = xv[0] * t3;
        let t5 = t0 * t3;
            return Rotor { c: gx::slots::from_values::<S, T, 2>([t4, t5]) };
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Rotor { c: [(x[0].scale(m2)).0, (x[1].scale(m3)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Rotor<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Rotor<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Rotor<S, T>) -> Rotor<S, T> {
        gx::Transform::transform(gx::Unit::new_unchecked(self.into_inner().reverse()), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Rotor> for gx::Unit<Vector<(), T>> {
    type Output = gx::Prepared<gx::Unit<Vector>, Rotor, T, 2>;
    #[inline]
    fn prepare(self) -> gx::Prepared<gx::Unit<Vector>, Rotor, T, 2> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        let m1 = v[1] * v[1];
        let m2 = v[0].mul_add(v[0], m1);
        let m3 = -m2;
        gx::Prepared::from_entries([m2, m3])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Rotor<S, T>> for gx::Prepared<gx::Unit<Vector>, Rotor, T, 2> {
    type Output = Rotor<S, T>;
    #[inline(always)]
    fn transform(self, x: Rotor<S, T>) -> Rotor<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Rotor { c: [(x[0].scale(m[0])).0, (x[1].scale(m[1])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<gx::Unit<Vector>, Rotor, T, 2>> for Rotor<(Rotor,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<gx::Unit<Vector>, Rotor, T, 2>) -> Self {
        let m = p.m;
        Rotor { c: [[m[0], T::zero()], [T::zero(), m[1]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Rotor, gx::batch::Certified> for Vector {
    type Y = Rotor;
    type Versor<T: gx::Coef> = gx::Unit<Vector<(), T>>;
    type Prepared<T: gx::Coef> = gx::Prepared<gx::Unit<Vector>, Rotor, T, 2>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> gx::Unit<Vector<(), T>> {
        gx::Unit::new_unchecked(v)
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> Vector<(), T> {
        v.into_inner()
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> gx::Prepared<gx::Unit<Vector>, Rotor, T, 2> {
        gx::Prepare::<Rotor>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Rotor, T, 2>, mut f: impl FnMut(T) -> W) -> gx::Prepared<gx::Unit<Vector>, Rotor, W, 2> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0]), f(m[1])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Rotor, T, 2>, x: Rotor<(), T>) -> Rotor<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: gx::Unit<Vector<(), T>>, x: Rotor<(), T>) -> Rotor<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Multivector<S, T>> for Vector<(), T> {
    type Output = Multivector<S, T>;
    #[inline(always)]
    fn transform(self, x: Multivector<S, T>) -> Multivector<S, T> {
        let v = self.c;
        if let Some(xv) = gx::slots::values::<S, T, 4>(&x.c) {
        let t0 = v[0] * v[0];
        let t1 = v[1] * v[1];
        let t2 = v[0] * v[1];
        let t3 = t0 + t1;
        let t4 = t0 - t1;
        let t5 = xv[0] * t3;
        let t7 = xv[2] * t2;
        let t8 = xv[1] * t2;
        let t10 = xv[3] * t3;
        let t11 = t7 * T::from_i64(2);
        let t12 = xv[1].mul_add(t4, t11);
        let t13 = t8 * T::from_i64(2);
        let t14 = (-xv[2]).mul_add(t4, t13);
        let t15 = -t10;
            return Multivector { c: gx::slots::from_values::<S, T, 4>([t5, t12, t14, t15]) };
        }
        let m0 = v[0] * v[0];
        let m1 = v[1] * v[1];
        let m2 = v[0] * v[1];
        let m3 = m0 - m1;
        let m4 = m0 + m1;
        let m5 = m2 * T::from_i64(2);
        let m6 = -m3;
        let m7 = -m4;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Multivector { c: [(x[0].scale(m4)).0, (x[1].scale(m3) + x[2].scale(m5)).0, (x[1].scale(m5) + x[2].scale(m6)).0, (x[3].scale(m7)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Multivector<S, T>> for Vector<(), T> {
    type Output = Multivector<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Multivector<S, T>) -> Multivector<S, T> {
        gx::Transform::transform(self.reverse(), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Multivector> for Vector<(), T> {
    type Output = gx::Prepared<Vector, Multivector, T, 5>;
    #[inline]
    fn prepare(self) -> gx::Prepared<Vector, Multivector, T, 5> {
        let v = self.c;
        let m0 = v[0] * v[0];
        let m1 = v[1] * v[1];
        let m2 = v[0] * v[1];
        let m3 = m0 - m1;
        let m4 = m0 + m1;
        let m5 = m2 * T::from_i64(2);
        let m6 = -m3;
        let m7 = -m4;
        gx::Prepared::from_entries([m4, m3, m5, m6, m7])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Multivector<S, T>> for gx::Prepared<Vector, Multivector, T, 5> {
    type Output = Multivector<S, T>;
    #[inline(always)]
    fn transform(self, x: Multivector<S, T>) -> Multivector<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Multivector { c: [(x[0].scale(m[0])).0, (x[1].scale(m[1]) + x[2].scale(m[2])).0, (x[1].scale(m[2]) + x[2].scale(m[3])).0, (x[3].scale(m[4])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<Vector, Multivector, T, 5>> for Multivector<(Multivector,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<Vector, Multivector, T, 5>) -> Self {
        let m = p.m;
        Multivector { c: [[m[0], T::zero(), T::zero(), T::zero()], [T::zero(), m[1], m[2], T::zero()], [T::zero(), m[2], m[3], T::zero()], [T::zero(), T::zero(), T::zero(), m[4]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Multivector, gx::batch::Plain> for Vector {
    type Y = Multivector;
    type Versor<T: gx::Coef> = Vector<(), T>;
    type Prepared<T: gx::Coef> = gx::Prepared<Vector, Multivector, T, 5>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: Vector<(), T>) -> Vector<(), T> {
        v
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: Vector<(), T>) -> gx::Prepared<Vector, Multivector, T, 5> {
        gx::Prepare::<Multivector>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<Vector, Multivector, T, 5>, mut f: impl FnMut(T) -> W) -> gx::Prepared<Vector, Multivector, W, 5> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0]), f(m[1]), f(m[2]), f(m[3]), f(m[4])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<Vector, Multivector, T, 5>, x: Multivector<(), T>) -> Multivector<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: Vector<(), T>, x: Multivector<(), T>) -> Multivector<(), T> {
        gx::Transform::transform(v, x)
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Multivector<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Multivector<S, T>;
    #[inline(always)]
    fn transform(self, x: Multivector<S, T>) -> Multivector<S, T> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        if let Some(xv) = gx::slots::values::<S, T, 4>(&x.c) {
        let t0 = v[0] * v[0];
        let t1 = v[1] * v[1];
        let t2 = v[0] * v[1];
        let t3 = t0 - t1;
        let t5 = xv[2] * t2;
        let t6 = xv[1] * t2;
        let t8 = t5 * T::from_i64(2);
        let t9 = xv[1].mul_add(t3, t8);
        let t10 = t6 * T::from_i64(2);
        let t11 = (-xv[2]).mul_add(t3, t10);
        let t12 = -xv[3];
        let t13 = t0 + t1;
        let t14 = xv[0] * t13;
        let t15 = t12 * t13;
            return Multivector { c: gx::slots::from_values::<S, T, 4>([t14, t9, t11, t15]) };
        }
        let m0 = v[0] * v[0];
        let m1 = v[1] * v[1];
        let m2 = v[0] * v[1];
        let m3 = m0 - m1;
        let m4 = m0 + m1;
        let m5 = m2 * T::from_i64(2);
        let m6 = -m3;
        let m7 = -m4;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Multivector { c: [(x[0].scale(m4)).0, (x[1].scale(m3) + x[2].scale(m5)).0, (x[1].scale(m5) + x[2].scale(m6)).0, (x[3].scale(m7)).0] }
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::TransformInv<Multivector<S, T>> for gx::Unit<Vector<(), T>> {
    type Output = Multivector<S, T>;
    #[inline(always)]
    fn transform_inv(self, x: Multivector<S, T>) -> Multivector<S, T> {
        gx::Transform::transform(gx::Unit::new_unchecked(self.into_inner().reverse()), x)
    }
}

impl<T: gx::Coef> gx::Prepare<Multivector> for gx::Unit<Vector<(), T>> {
    type Output = gx::Prepared<gx::Unit<Vector>, Multivector, T, 5>;
    #[inline]
    fn prepare(self) -> gx::Prepared<gx::Unit<Vector>, Multivector, T, 5> {
        let v = self.into_inner().c;
        #[cfg(feature = "check-units")]
        {
        let u1 = v[1] * v[1];
        let u2 = v[0].mul_add(v[0], u1);
        let u3 = u2 - T::from_i64(1);
            T::check_unit(&[u3]);
        }
        let m0 = v[0] * v[0];
        let m1 = v[1] * v[1];
        let m2 = v[0] * v[1];
        let m3 = m0 - m1;
        let m4 = m0 + m1;
        let m5 = m2 * T::from_i64(2);
        let m6 = -m3;
        let m7 = -m4;
        gx::Prepared::from_entries([m4, m3, m5, m6, m7])
    }
}

impl<S: gx::Slots, T: gx::Coef> gx::Transform<Multivector<S, T>> for gx::Prepared<gx::Unit<Vector>, Multivector, T, 5> {
    type Output = Multivector<S, T>;
    #[inline(always)]
    fn transform(self, x: Multivector<S, T>) -> Multivector<S, T> {
        let m = self.m;
        let x = x.c.map(gx::SlotArr::<S, T>);
        Multivector { c: [(x[0].scale(m[0])).0, (x[1].scale(m[1]) + x[2].scale(m[2])).0, (x[1].scale(m[2]) + x[2].scale(m[3])).0, (x[3].scale(m[4])).0] }
    }
}

impl<T: gx::Coef> From<gx::Prepared<gx::Unit<Vector>, Multivector, T, 5>> for Multivector<(Multivector,), T> {
    /// The dense map of the prepared action.
    #[inline]
    fn from(p: gx::Prepared<gx::Unit<Vector>, Multivector, T, 5>) -> Self {
        let m = p.m;
        Multivector { c: [[m[0], T::zero(), T::zero(), T::zero()], [T::zero(), m[1], m[2], T::zero()], [T::zero(), m[2], m[3], T::zero()], [T::zero(), T::zero(), T::zero(), m[4]]] }
    }
}

#[cfg(feature = "batch")]
impl gx::batch::SandwichKernel<Multivector, gx::batch::Certified> for Vector {
    type Y = Multivector;
    type Versor<T: gx::Coef> = gx::Unit<Vector<(), T>>;
    type Prepared<T: gx::Coef> = gx::Prepared<gx::Unit<Vector>, Multivector, T, 5>;
    #[inline(always)]
    fn wrap<T: gx::Coef>(v: Vector<(), T>) -> gx::Unit<Vector<(), T>> {
        gx::Unit::new_unchecked(v)
    }
    #[inline(always)]
    fn unwrap<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> Vector<(), T> {
        v.into_inner()
    }
    #[inline(always)]
    fn prepare<T: gx::Coef>(v: gx::Unit<Vector<(), T>>) -> gx::Prepared<gx::Unit<Vector>, Multivector, T, 5> {
        gx::Prepare::<Multivector>::prepare(v)
    }
    #[inline(always)]
    fn map_prepared<T: gx::Coef, W: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Multivector, T, 5>, mut f: impl FnMut(T) -> W) -> gx::Prepared<gx::Unit<Vector>, Multivector, W, 5> {
        let m = p.m;
        gx::Prepared::from_entries([f(m[0]), f(m[1]), f(m[2]), f(m[3]), f(m[4])])
    }
    #[inline(always)]
    fn apply_prepared<T: gx::Coef>(p: gx::Prepared<gx::Unit<Vector>, Multivector, T, 5>, x: Multivector<(), T>) -> Multivector<(), T> {
        gx::Transform::transform(p, x)
    }
    #[inline(always)]
    fn apply<T: gx::Coef>(v: gx::Unit<Vector<(), T>>, x: Multivector<(), T>) -> Multivector<(), T> {
        gx::Transform::transform(v, x)
    }
}
