// @generated by gax-gen: part of `stap` (see ../stap.rs). Do not edit by hand.

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Scalar<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Scalar<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Scalar<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Trivector<S2, T>> for Scalar<S1, T> {
    type Output = Trivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Trivector<S2, T>) -> Trivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Trivector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Quadvector<S2, T>> for Scalar<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Quadvector<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Pseudoscalar<S2, T>> for Scalar<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Pseudoscalar<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Scalar<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                (p(0, 10)).0,
                (p(0, 11)).0,
                (p(0, 12)).0,
                (p(0, 13)).0,
                (p(0, 14)).0,
                (p(0, 15)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Scalar<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                (p(0, 10)).0,
                (p(0, 11)).0,
                (p(0, 12)).0,
                (p(0, 13)).0,
                (p(0, 14)).0,
                (p(0, 15)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Scalar<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                (p(0, 10)).0,
                (p(0, 11)).0,
                (p(0, 12)).0,
                (p(0, 13)).0,
                (p(0, 14)).0,
                (p(0, 15)).0,
                (p(0, 16)).0,
                (p(0, 17)).0,
                (p(0, 18)).0,
                (p(0, 19)).0,
                (p(0, 20)).0,
                (p(0, 21)).0,
                (p(0, 22)).0,
                (p(0, 23)).0,
                (p(0, 24)).0,
                (p(0, 25)).0,
                (p(0, 26)).0,
                (p(0, 27)).0,
                (p(0, 28)).0,
                (p(0, 29)).0,
                (p(0, 30)).0,
                (p(0, 31)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Vector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Vector<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                ((p(0, 1) - p(1, 0))).0,
                ((p(0, 2) - p(2, 0))).0,
                ((p(0, 3) - p(3, 0))).0,
                ((p(0, 4) - p(4, 0))).0,
                ((p(2, 3) - p(3, 2))).0,
                ((p(3, 1) - p(1, 3))).0,
                ((p(1, 2) - p(2, 1))).0,
                ((p(4, 1) - p(1, 4))).0,
                ((p(4, 2) - p(2, 4))).0,
                ((p(4, 3) - p(3, 4))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Vector<S1, T> {
    type Output = Trivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Trivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Trivector {
            c: [
                (((p(0, 4) + p(3, 1)) - p(2, 2))).0,
                (((p(0, 5) + p(1, 2)) - p(3, 0))).0,
                (((p(0, 6) + p(2, 0)) - p(1, 1))).0,
                (((p(4, 0) - p(0, 7)) - p(1, 3))).0,
                (((p(4, 1) - p(0, 8)) - p(2, 3))).0,
                (((p(4, 2) - p(0, 9)) - p(3, 3))).0,
                (((p(1, 4) + p(2, 5)) + p(3, 6))).0,
                (((p(3, 8) + p(4, 4)) - p(2, 9))).0,
                (((p(1, 9) + p(4, 5)) - p(3, 7))).0,
                (((p(2, 7) + p(4, 6)) - p(1, 8))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Trivector<S2, T>> for Vector<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Trivector<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (((p(2, 5) + p(4, 0)) - (p(0, 7) + p(3, 4)))).0,
                (((p(3, 3) + p(4, 1)) - (p(0, 8) + p(1, 5)))).0,
                (((p(1, 4) + p(4, 2)) - (p(0, 9) + p(2, 3)))).0,
                (((p(0, 6) - p(1, 0)) - (p(2, 1) + p(3, 2)))).0,
                (((p(1, 7) + p(2, 8)) + (p(3, 9) - p(4, 6)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Quadvector<S2, T>> for Vector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Quadvector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                ((((p(0, 4) + p(1, 0)) + p(2, 1)) + (p(3, 2) + p(4, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Vector<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (((p(0, 5) + p(3, 2)) - p(2, 3))).0,
                (((p(0, 6) + p(1, 3)) - p(3, 1))).0,
                (((p(0, 7) + p(2, 1)) - p(1, 2))).0,
                (((p(4, 1) - p(0, 8)) - p(1, 4))).0,
                (((p(4, 2) - p(0, 9)) - p(2, 4))).0,
                (((p(4, 3) - p(0, 10)) - p(3, 4))).0,
                (((p(1, 5) + p(2, 6)) + p(3, 7))).0,
                (((p(3, 9) + p(4, 5)) - p(2, 10))).0,
                (((p(1, 10) + p(4, 6)) - p(3, 8))).0,
                (((p(2, 8) + p(4, 7)) - p(1, 9))).0,
                ((((p(0, 15) + p(1, 11)) + p(2, 12)) + (p(3, 13) + p(4, 14)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Vector<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                ((p(0, 1) - p(1, 0))).0,
                ((p(0, 2) - p(2, 0))).0,
                ((p(0, 3) - p(3, 0))).0,
                ((p(0, 4) - p(4, 0))).0,
                ((p(2, 3) - p(3, 2))).0,
                ((p(3, 1) - p(1, 3))).0,
                ((p(1, 2) - p(2, 1))).0,
                ((p(4, 1) - p(1, 4))).0,
                ((p(4, 2) - p(2, 4))).0,
                ((p(4, 3) - p(3, 4))).0,
                (((p(2, 10) + p(4, 5)) - (p(0, 12) + p(3, 9)))).0,
                (((p(3, 8) + p(4, 6)) - (p(0, 13) + p(1, 10)))).0,
                (((p(1, 9) + p(4, 7)) - (p(0, 14) + p(2, 8)))).0,
                (((p(0, 11) - p(1, 5)) - (p(2, 6) + p(3, 7)))).0,
                (((p(1, 12) + p(2, 13)) + (p(3, 14) - p(4, 11)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Vector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                ((p(0, 2) - p(1, 1))).0,
                ((p(0, 3) - p(2, 1))).0,
                ((p(0, 4) - p(3, 1))).0,
                ((p(0, 5) - p(4, 1))).0,
                ((p(2, 4) - p(3, 3))).0,
                ((p(3, 2) - p(1, 4))).0,
                ((p(1, 3) - p(2, 2))).0,
                ((p(4, 2) - p(1, 5))).0,
                ((p(4, 3) - p(2, 5))).0,
                ((p(4, 4) - p(3, 5))).0,
                (((p(0, 10) + p(3, 7)) - p(2, 8))).0,
                (((p(0, 11) + p(1, 8)) - p(3, 6))).0,
                (((p(0, 12) + p(2, 6)) - p(1, 7))).0,
                (((p(4, 6) - p(0, 13)) - p(1, 9))).0,
                (((p(4, 7) - p(0, 14)) - p(2, 9))).0,
                (((p(4, 8) - p(0, 15)) - p(3, 9))).0,
                (((p(1, 10) + p(2, 11)) + p(3, 12))).0,
                (((p(3, 14) + p(4, 10)) - p(2, 15))).0,
                (((p(1, 15) + p(4, 11)) - p(3, 13))).0,
                (((p(2, 13) + p(4, 12)) - p(1, 14))).0,
                (((p(2, 21) + p(4, 16)) - (p(0, 23) + p(3, 20)))).0,
                (((p(3, 19) + p(4, 17)) - (p(0, 24) + p(1, 21)))).0,
                (((p(1, 20) + p(4, 18)) - (p(0, 25) + p(2, 19)))).0,
                (((p(0, 22) - p(1, 16)) - (p(2, 17) + p(3, 18)))).0,
                (((p(1, 23) + p(2, 24)) + (p(3, 25) - p(4, 22)))).0,
                ((((p(0, 30) + p(1, 26)) + p(2, 27)) + (p(3, 28) + p(4, 29)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Bivector<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Bivector<S1, T> {
    type Output = Trivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Trivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Trivector {
            c: [
                (((p(1, 3) + p(4, 0)) - p(2, 2))).0,
                (((p(2, 1) + p(5, 0)) - p(0, 3))).0,
                (((p(0, 2) + p(6, 0)) - p(1, 1))).0,
                (((p(0, 4) - p(3, 1)) - p(7, 0))).0,
                (((p(1, 4) - p(3, 2)) - p(8, 0))).0,
                (((p(2, 4) - p(3, 3)) - p(9, 0))).0,
                (((p(4, 1) + p(5, 2)) + p(6, 3))).0,
                (((p(4, 4) + p(8, 3)) - p(9, 2))).0,
                (((p(5, 4) + p(9, 1)) - p(7, 3))).0,
                (((p(6, 4) + p(7, 2)) - p(8, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Bivector<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                ((((p(1, 9) + p(9, 1)) - p(2, 8)) - ((p(3, 4) + p(4, 3)) + p(8, 2)))).0,
                ((((p(2, 7) + p(7, 2)) - p(0, 9)) - ((p(3, 5) + p(5, 3)) + p(9, 0)))).0,
                ((((p(0, 8) + p(8, 0)) - p(1, 7)) - ((p(3, 6) + p(6, 3)) + p(7, 1)))).0,
                ((((p(0, 4) + p(1, 5)) + p(2, 6)) + ((p(4, 0) + p(5, 1)) + p(6, 2)))).0,
                (-(((p(4, 7) + p(5, 8)) + p(6, 9)) + ((p(7, 4) + p(8, 5)) + p(9, 6)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Trivector<S2, T>> for Bivector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Trivector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (((((p(0, 7) + p(1, 8)) + p(2, 9)) + (p(4, 3) + p(5, 4))) + (((p(6, 5) - p(3, 6)) - p(7, 0)) - (p(8, 1) + p(9, 2))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Bivector<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                ((((p(1, 10) + p(9, 2)) - p(2, 9)) - ((p(3, 5) + p(4, 4)) + p(8, 3)))).0,
                ((((p(2, 8) + p(7, 3)) - p(0, 10)) - ((p(3, 6) + p(5, 4)) + p(9, 1)))).0,
                ((((p(0, 9) + p(8, 1)) - p(1, 8)) - ((p(3, 7) + p(6, 4)) + p(7, 2)))).0,
                ((((p(0, 5) + p(1, 6)) + p(2, 7)) + ((p(4, 1) + p(5, 2)) + p(6, 3)))).0,
                (-(((p(4, 8) + p(5, 9)) + p(6, 10)) + ((p(7, 5) + p(8, 6)) + p(9, 7)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Bivector<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (((p(1, 3) + p(4, 0)) - p(2, 2))).0,
                (((p(2, 1) + p(5, 0)) - p(0, 3))).0,
                (((p(0, 2) + p(6, 0)) - p(1, 1))).0,
                (((p(0, 4) - p(3, 1)) - p(7, 0))).0,
                (((p(1, 4) - p(3, 2)) - p(8, 0))).0,
                (((p(2, 4) - p(3, 3)) - p(9, 0))).0,
                (((p(4, 1) + p(5, 2)) + p(6, 3))).0,
                (((p(4, 4) + p(8, 3)) - p(9, 2))).0,
                (((p(5, 4) + p(9, 1)) - p(7, 3))).0,
                (((p(6, 4) + p(7, 2)) - p(8, 1))).0,
                (((((p(0, 12) + p(1, 13)) + p(2, 14)) + (p(4, 8) + p(5, 9))) + (((p(6, 10) - p(3, 11)) - p(7, 5)) - (p(8, 6) + p(9, 7))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Bivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (((p(1, 4) + p(4, 1)) - p(2, 3))).0,
                (((p(2, 2) + p(5, 1)) - p(0, 4))).0,
                (((p(0, 3) + p(6, 1)) - p(1, 2))).0,
                (((p(0, 5) - p(3, 2)) - p(7, 1))).0,
                (((p(1, 5) - p(3, 3)) - p(8, 1))).0,
                (((p(2, 5) - p(3, 4)) - p(9, 1))).0,
                (((p(4, 2) + p(5, 3)) + p(6, 4))).0,
                (((p(4, 5) + p(8, 4)) - p(9, 3))).0,
                (((p(5, 5) + p(9, 2)) - p(7, 4))).0,
                (((p(6, 5) + p(7, 3)) - p(8, 2))).0,
                ((((p(1, 15) + p(9, 7)) - p(2, 14)) - ((p(3, 10) + p(4, 9)) + p(8, 8)))).0,
                ((((p(2, 13) + p(7, 8)) - p(0, 15)) - ((p(3, 11) + p(5, 9)) + p(9, 6)))).0,
                ((((p(0, 14) + p(8, 6)) - p(1, 13)) - ((p(3, 12) + p(6, 9)) + p(7, 7)))).0,
                ((((p(0, 10) + p(1, 11)) + p(2, 12)) + ((p(4, 6) + p(5, 7)) + p(6, 8)))).0,
                (-(((p(4, 13) + p(5, 14)) + p(6, 15)) + ((p(7, 10) + p(8, 11)) + p(9, 12)))).0,
                (((((p(0, 23) + p(1, 24)) + p(2, 25)) + (p(4, 19) + p(5, 20))) + (((p(6, 21) - p(3, 22)) - p(7, 16)) - (p(8, 17) + p(9, 18))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Trivector<S1, T> {
    type Output = Trivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Trivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Trivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Trivector<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (((p(4, 3) + p(7, 0)) - (p(0, 4) + p(5, 2)))).0,
                (((p(5, 1) + p(8, 0)) - (p(1, 4) + p(3, 3)))).0,
                (((p(3, 2) + p(9, 0)) - (p(2, 4) + p(4, 1)))).0,
                (((p(0, 1) + p(1, 2)) + (p(2, 3) - p(6, 0)))).0,
                (((p(6, 4) - p(7, 1)) - (p(8, 2) + p(9, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Trivector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (((((p(3, 4) + p(4, 5)) + p(5, 6)) + (p(7, 0) + p(8, 1))) + (((p(9, 2) - p(0, 7)) - p(1, 8)) - (p(2, 9) + p(6, 3))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Trivector<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (((((p(3, 5) + p(4, 6)) + p(5, 7)) + (p(7, 1) + p(8, 2))) + (((p(9, 3) - p(0, 8)) - p(1, 9)) - (p(2, 10) + p(6, 4))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Trivector<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (((p(4, 3) + p(7, 0)) - (p(0, 4) + p(5, 2)))).0,
                (((p(5, 1) + p(8, 0)) - (p(1, 4) + p(3, 3)))).0,
                (((p(3, 2) + p(9, 0)) - (p(2, 4) + p(4, 1)))).0,
                (((p(0, 1) + p(1, 2)) + (p(2, 3) - p(6, 0)))).0,
                (((p(6, 4) - p(7, 1)) - (p(8, 2) + p(9, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Trivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (((p(4, 4) + p(7, 1)) - (p(0, 5) + p(5, 3)))).0,
                (((p(5, 2) + p(8, 1)) - (p(1, 5) + p(3, 4)))).0,
                (((p(3, 3) + p(9, 1)) - (p(2, 5) + p(4, 2)))).0,
                (((p(0, 2) + p(1, 3)) + (p(2, 4) - p(6, 1)))).0,
                (((p(6, 5) - p(7, 2)) - (p(8, 3) + p(9, 4)))).0,
                (((((p(3, 10) + p(4, 11)) + p(5, 12)) + (p(7, 6) + p(8, 7))) + (((p(9, 8) - p(0, 13)) - p(1, 14)) - (p(2, 15) + p(6, 9))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Quadvector<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Quadvector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                ((((p(0, 1) + p(1, 2)) + p(2, 3)) + (p(3, 4) + p(4, 0)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Quadvector<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Quadvector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                ((((p(0, 1) + p(1, 2)) + p(2, 3)) + (p(3, 4) + p(4, 0)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Quadvector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                ((((p(0, 2) + p(1, 3)) + p(2, 4)) + (p(3, 5) + p(4, 1)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Motor<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (p(10, 0)).0,
                (p(11, 0)).0,
                (p(12, 0)).0,
                (p(13, 0)).0,
                (p(14, 0)).0,
                (p(15, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Motor<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (((p(2, 3) + p(5, 0)) - p(3, 2))).0,
                (((p(3, 1) + p(6, 0)) - p(1, 3))).0,
                (((p(1, 2) + p(7, 0)) - p(2, 1))).0,
                (((p(1, 4) - p(4, 1)) - p(8, 0))).0,
                (((p(2, 4) - p(4, 2)) - p(9, 0))).0,
                (((p(3, 4) - p(4, 3)) - p(10, 0))).0,
                (((p(5, 1) + p(6, 2)) + p(7, 3))).0,
                (((p(5, 4) + p(9, 3)) - p(10, 2))).0,
                (((p(6, 4) + p(10, 1)) - p(8, 3))).0,
                (((p(7, 4) + p(8, 2)) - p(9, 1))).0,
                ((((p(11, 1) + p(12, 2)) + p(13, 3)) + (p(14, 4) + p(15, 0)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Motor<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                ((((p(2, 9) + p(10, 1)) - p(3, 8)) - ((p(4, 4) + p(5, 3)) + p(9, 2)))).0,
                ((((p(3, 7) + p(8, 2)) - p(1, 9)) - ((p(4, 5) + p(6, 3)) + p(10, 0)))).0,
                ((((p(1, 8) + p(9, 0)) - p(2, 7)) - ((p(4, 6) + p(7, 3)) + p(8, 1)))).0,
                ((((p(1, 4) + p(2, 5)) + p(3, 6)) + ((p(5, 0) + p(6, 1)) + p(7, 2)))).0,
                (-(((p(5, 7) + p(6, 8)) + p(7, 9)) + ((p(8, 4) + p(9, 5)) + p(10, 6)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Trivector<S2, T>> for Motor<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Trivector<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                (((((p(1, 7) + p(2, 8)) + p(3, 9)) + (p(5, 3) + p(6, 4))) + (((p(7, 5) - p(4, 6)) - p(8, 0)) - (p(9, 1) + p(10, 2))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Quadvector<S2, T>> for Motor<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Quadvector<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Pseudoscalar<S2, T>> for Motor<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Pseudoscalar<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Motor<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (p(0, 0)).0,
                ((p(0, 1) + p(1, 0))).0,
                ((p(0, 2) + p(2, 0))).0,
                ((p(0, 3) + p(3, 0))).0,
                ((p(0, 4) + p(4, 0))).0,
                ((p(0, 5) + p(5, 0))).0,
                ((p(0, 6) + p(6, 0))).0,
                ((p(0, 7) + p(7, 0))).0,
                ((p(0, 8) + p(8, 0))).0,
                ((p(0, 9) + p(9, 0))).0,
                ((p(0, 10) + p(10, 0))).0,
                ((((p(0, 11) + p(2, 10)) + (p(10, 2) + p(11, 0))) - ((p(3, 9) + p(4, 5)) + (p(5, 4) + p(9, 3))))).0,
                ((((p(0, 12) + p(3, 8)) + (p(8, 3) + p(12, 0))) - ((p(1, 10) + p(4, 6)) + (p(6, 4) + p(10, 1))))).0,
                ((((p(0, 13) + p(1, 9)) + (p(9, 1) + p(13, 0))) - ((p(2, 8) + p(4, 7)) + (p(7, 4) + p(8, 2))))).0,
                ((((p(0, 14) + p(1, 5)) + (p(2, 6) + p(3, 7))) + ((p(5, 1) + p(6, 2)) + (p(7, 3) + p(14, 0))))).0,
                ((((p(0, 15) + p(15, 0)) - (p(5, 8) + p(6, 9))) - ((p(7, 10) + p(8, 5)) + (p(9, 6) + p(10, 7))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Motor<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (((p(0, 5) + p(2, 3)) + (p(5, 0) - p(3, 2)))).0,
                (((p(0, 6) + p(3, 1)) + (p(6, 0) - p(1, 3)))).0,
                (((p(0, 7) + p(1, 2)) + (p(7, 0) - p(2, 1)))).0,
                (((p(0, 8) + p(1, 4)) - (p(4, 1) + p(8, 0)))).0,
                (((p(0, 9) + p(2, 4)) - (p(4, 2) + p(9, 0)))).0,
                (((p(0, 10) + p(3, 4)) - (p(4, 3) + p(10, 0)))).0,
                (((p(0, 11) + p(5, 1)) + (p(6, 2) + p(7, 3)))).0,
                (((p(0, 12) + p(5, 4)) + (p(9, 3) - p(10, 2)))).0,
                (((p(0, 13) + p(6, 4)) + (p(10, 1) - p(8, 3)))).0,
                (((p(0, 14) + p(7, 4)) + (p(8, 2) - p(9, 1)))).0,
                (((((p(0, 15) + p(1, 12)) + (p(2, 13) + p(3, 14))) + ((p(5, 8) + p(6, 9)) + (p(7, 10) + p(11, 1)))) + (((p(12, 2) + p(13, 3)) + (p(14, 4) + p(15, 0))) - ((p(4, 11) + p(8, 5)) + (p(9, 6) + p(10, 7)))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Motor<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                ((p(0, 6) + p(1, 0))).0,
                ((p(0, 7) + p(2, 0))).0,
                ((p(0, 8) + p(3, 0))).0,
                ((p(0, 9) + p(4, 0))).0,
                ((p(0, 10) + p(5, 0))).0,
                ((p(0, 11) + p(6, 0))).0,
                ((p(0, 12) + p(7, 0))).0,
                ((p(0, 13) + p(8, 0))).0,
                ((p(0, 14) + p(9, 0))).0,
                ((p(0, 15) + p(10, 0))).0,
                (((p(0, 16) + p(2, 4)) + (p(5, 1) - p(3, 3)))).0,
                (((p(0, 17) + p(3, 2)) + (p(6, 1) - p(1, 4)))).0,
                (((p(0, 18) + p(1, 3)) + (p(7, 1) - p(2, 2)))).0,
                (((p(0, 19) + p(1, 5)) - (p(4, 2) + p(8, 1)))).0,
                (((p(0, 20) + p(2, 5)) - (p(4, 3) + p(9, 1)))).0,
                (((p(0, 21) + p(3, 5)) - (p(4, 4) + p(10, 1)))).0,
                (((p(0, 22) + p(5, 2)) + (p(6, 3) + p(7, 4)))).0,
                (((p(0, 23) + p(5, 5)) + (p(9, 4) - p(10, 3)))).0,
                (((p(0, 24) + p(6, 5)) + (p(10, 2) - p(8, 4)))).0,
                (((p(0, 25) + p(7, 5)) + (p(8, 3) - p(9, 2)))).0,
                ((((p(0, 26) + p(2, 15)) + (p(10, 7) + p(11, 0))) - ((p(3, 14) + p(4, 10)) + (p(5, 9) + p(9, 8))))).0,
                ((((p(0, 27) + p(3, 13)) + (p(8, 8) + p(12, 0))) - ((p(1, 15) + p(4, 11)) + (p(6, 9) + p(10, 6))))).0,
                ((((p(0, 28) + p(1, 14)) + (p(9, 6) + p(13, 0))) - ((p(2, 13) + p(4, 12)) + (p(7, 9) + p(8, 7))))).0,
                ((((p(0, 29) + p(1, 10)) + (p(2, 11) + p(3, 12))) + ((p(5, 6) + p(6, 7)) + (p(7, 8) + p(14, 0))))).0,
                ((((p(0, 30) + p(15, 0)) - (p(5, 13) + p(6, 14))) - ((p(7, 15) + p(8, 10)) + (p(9, 11) + p(10, 12))))).0,
                (((((p(0, 31) + p(1, 23)) + (p(2, 24) + p(3, 25))) + ((p(5, 19) + p(6, 20)) + (p(7, 21) + p(11, 2)))) + (((p(12, 3) + p(13, 4)) + (p(14, 5) + p(15, 1))) - ((p(4, 22) + p(8, 16)) + (p(9, 17) + p(10, 18)))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Odd<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (p(10, 0)).0,
                (p(11, 0)).0,
                (p(12, 0)).0,
                (p(13, 0)).0,
                (p(14, 0)).0,
                (p(15, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Odd<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                ((p(0, 1) - p(1, 0))).0,
                ((p(0, 2) - p(2, 0))).0,
                ((p(0, 3) - p(3, 0))).0,
                ((p(0, 4) - p(4, 0))).0,
                ((p(2, 3) - p(3, 2))).0,
                ((p(3, 1) - p(1, 3))).0,
                ((p(1, 2) - p(2, 1))).0,
                ((p(4, 1) - p(1, 4))).0,
                ((p(4, 2) - p(2, 4))).0,
                ((p(4, 3) - p(3, 4))).0,
                (((p(9, 3) + p(12, 0)) - (p(5, 4) + p(10, 2)))).0,
                (((p(10, 1) + p(13, 0)) - (p(6, 4) + p(8, 3)))).0,
                (((p(8, 2) + p(14, 0)) - (p(7, 4) + p(9, 1)))).0,
                (((p(5, 1) + p(6, 2)) + (p(7, 3) - p(11, 0)))).0,
                (((p(11, 4) - p(12, 1)) - (p(13, 2) + p(14, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Odd<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (((p(0, 4) + p(3, 1)) - p(2, 2))).0,
                (((p(0, 5) + p(1, 2)) - p(3, 0))).0,
                (((p(0, 6) + p(2, 0)) - p(1, 1))).0,
                (((p(4, 0) - p(0, 7)) - p(1, 3))).0,
                (((p(4, 1) - p(0, 8)) - p(2, 3))).0,
                (((p(4, 2) - p(0, 9)) - p(3, 3))).0,
                (((p(1, 4) + p(2, 5)) + p(3, 6))).0,
                (((p(3, 8) + p(4, 4)) - p(2, 9))).0,
                (((p(1, 9) + p(4, 5)) - p(3, 7))).0,
                (((p(2, 7) + p(4, 6)) - p(1, 8))).0,
                (((((p(8, 4) + p(9, 5)) + p(10, 6)) + (p(12, 0) + p(13, 1))) + (((p(14, 2) - p(5, 7)) - p(6, 8)) - (p(7, 9) + p(11, 3))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Trivector<S2, T>> for Odd<S1, T> {
    type Output = Quadvector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Trivector<S2, T>) -> Quadvector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Quadvector {
            c: [
                (((p(2, 5) + p(4, 0)) - (p(0, 7) + p(3, 4)))).0,
                (((p(3, 3) + p(4, 1)) - (p(0, 8) + p(1, 5)))).0,
                (((p(1, 4) + p(4, 2)) - (p(0, 9) + p(2, 3)))).0,
                (((p(0, 6) - p(1, 0)) - (p(2, 1) + p(3, 2)))).0,
                (((p(1, 7) + p(2, 8)) + (p(3, 9) - p(4, 6)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Quadvector<S2, T>> for Odd<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Quadvector<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                ((((p(0, 4) + p(1, 0)) + p(2, 1)) + (p(3, 2) + p(4, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Odd<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (((p(0, 5) + p(3, 2)) + (p(5, 0) - p(2, 3)))).0,
                (((p(0, 6) + p(1, 3)) + (p(6, 0) - p(3, 1)))).0,
                (((p(0, 7) + p(2, 1)) + (p(7, 0) - p(1, 2)))).0,
                (((p(4, 1) + p(8, 0)) - (p(0, 8) + p(1, 4)))).0,
                (((p(4, 2) + p(9, 0)) - (p(0, 9) + p(2, 4)))).0,
                (((p(4, 3) + p(10, 0)) - (p(0, 10) + p(3, 4)))).0,
                (((p(1, 5) + p(2, 6)) + (p(3, 7) + p(11, 0)))).0,
                (((p(3, 9) + p(4, 5)) + (p(12, 0) - p(2, 10)))).0,
                (((p(1, 10) + p(4, 6)) + (p(13, 0) - p(3, 8)))).0,
                (((p(2, 8) + p(4, 7)) + (p(14, 0) - p(1, 9)))).0,
                (((((p(0, 15) + p(1, 11)) + (p(2, 12) + p(3, 13))) + ((p(4, 14) + p(8, 5)) + (p(9, 6) + p(10, 7)))) + (((p(12, 1) + p(13, 2)) + (p(14, 3) + p(15, 0))) - ((p(5, 8) + p(6, 9)) + (p(7, 10) + p(11, 4)))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Odd<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                ((p(0, 1) - p(1, 0))).0,
                ((p(0, 2) - p(2, 0))).0,
                ((p(0, 3) - p(3, 0))).0,
                ((p(0, 4) - p(4, 0))).0,
                ((p(2, 3) - p(3, 2))).0,
                ((p(3, 1) - p(1, 3))).0,
                ((p(1, 2) - p(2, 1))).0,
                ((p(4, 1) - p(1, 4))).0,
                ((p(4, 2) - p(2, 4))).0,
                ((p(4, 3) - p(3, 4))).0,
                ((((p(2, 10) + p(4, 5)) + (p(9, 3) + p(12, 0))) - ((p(0, 12) + p(3, 9)) + (p(5, 4) + p(10, 2))))).0,
                ((((p(3, 8) + p(4, 6)) + (p(10, 1) + p(13, 0))) - ((p(0, 13) + p(1, 10)) + (p(6, 4) + p(8, 3))))).0,
                ((((p(1, 9) + p(4, 7)) + (p(8, 2) + p(14, 0))) - ((p(0, 14) + p(2, 8)) + (p(7, 4) + p(9, 1))))).0,
                ((((p(0, 11) + p(5, 1)) + (p(6, 2) + p(7, 3))) - ((p(1, 5) + p(2, 6)) + (p(3, 7) + p(11, 0))))).0,
                ((((p(1, 12) + p(2, 13)) + (p(3, 14) + p(11, 4))) - ((p(4, 11) + p(12, 1)) + (p(13, 2) + p(14, 3))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Odd<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                ((p(0, 2) - p(1, 1))).0,
                ((p(0, 3) - p(2, 1))).0,
                ((p(0, 4) - p(3, 1))).0,
                ((p(0, 5) - p(4, 1))).0,
                ((p(2, 4) - p(3, 3))).0,
                ((p(3, 2) - p(1, 4))).0,
                ((p(1, 3) - p(2, 2))).0,
                ((p(4, 2) - p(1, 5))).0,
                ((p(4, 3) - p(2, 5))).0,
                ((p(4, 4) - p(3, 5))).0,
                (((p(0, 10) + p(3, 7)) + (p(5, 0) - p(2, 8)))).0,
                (((p(0, 11) + p(1, 8)) + (p(6, 0) - p(3, 6)))).0,
                (((p(0, 12) + p(2, 6)) + (p(7, 0) - p(1, 7)))).0,
                (((p(4, 6) + p(8, 0)) - (p(0, 13) + p(1, 9)))).0,
                (((p(4, 7) + p(9, 0)) - (p(0, 14) + p(2, 9)))).0,
                (((p(4, 8) + p(10, 0)) - (p(0, 15) + p(3, 9)))).0,
                (((p(1, 10) + p(2, 11)) + (p(3, 12) + p(11, 0)))).0,
                (((p(3, 14) + p(4, 10)) + (p(12, 0) - p(2, 15)))).0,
                (((p(1, 15) + p(4, 11)) + (p(13, 0) - p(3, 13)))).0,
                (((p(2, 13) + p(4, 12)) + (p(14, 0) - p(1, 14)))).0,
                ((((p(2, 21) + p(4, 16)) + (p(9, 4) + p(12, 1))) - ((p(0, 23) + p(3, 20)) + (p(5, 5) + p(10, 3))))).0,
                ((((p(3, 19) + p(4, 17)) + (p(10, 2) + p(13, 1))) - ((p(0, 24) + p(1, 21)) + (p(6, 5) + p(8, 4))))).0,
                ((((p(1, 20) + p(4, 18)) + (p(8, 3) + p(14, 1))) - ((p(0, 25) + p(2, 19)) + (p(7, 5) + p(9, 2))))).0,
                ((((p(0, 22) + p(5, 2)) + (p(6, 3) + p(7, 4))) - ((p(1, 16) + p(2, 17)) + (p(3, 18) + p(11, 1))))).0,
                ((((p(1, 23) + p(2, 24)) + (p(3, 25) + p(11, 5))) - ((p(4, 22) + p(12, 2)) + (p(13, 3) + p(14, 4))))).0,
                (((((p(0, 30) + p(1, 26)) + (p(2, 27) + p(3, 28))) + ((p(4, 29) + p(8, 10)) + (p(9, 11) + p(10, 12)))) + (((p(12, 6) + p(13, 7)) + (p(14, 8) + p(15, 0))) - ((p(5, 13) + p(6, 14)) + (p(7, 15) + p(11, 9)))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Scalar<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Scalar<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (p(10, 0)).0,
                (p(11, 0)).0,
                (p(12, 0)).0,
                (p(13, 0)).0,
                (p(14, 0)).0,
                (p(15, 0)).0,
                (p(16, 0)).0,
                (p(17, 0)).0,
                (p(18, 0)).0,
                (p(19, 0)).0,
                (p(20, 0)).0,
                (p(21, 0)).0,
                (p(22, 0)).0,
                (p(23, 0)).0,
                (p(24, 0)).0,
                (p(25, 0)).0,
                (p(26, 0)).0,
                (p(27, 0)).0,
                (p(28, 0)).0,
                (p(29, 0)).0,
                (p(30, 0)).0,
                (p(31, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Vector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Vector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                ((p(1, 1) - p(2, 0))).0,
                ((p(1, 2) - p(3, 0))).0,
                ((p(1, 3) - p(4, 0))).0,
                ((p(1, 4) - p(5, 0))).0,
                ((p(3, 3) - p(4, 2))).0,
                ((p(4, 1) - p(2, 3))).0,
                ((p(2, 2) - p(3, 1))).0,
                ((p(5, 1) - p(2, 4))).0,
                ((p(5, 2) - p(3, 4))).0,
                ((p(5, 3) - p(4, 4))).0,
                (((p(7, 3) + p(10, 0)) - p(8, 2))).0,
                (((p(8, 1) + p(11, 0)) - p(6, 3))).0,
                (((p(6, 2) + p(12, 0)) - p(7, 1))).0,
                (((p(6, 4) - p(9, 1)) - p(13, 0))).0,
                (((p(7, 4) - p(9, 2)) - p(14, 0))).0,
                (((p(8, 4) - p(9, 3)) - p(15, 0))).0,
                (((p(10, 1) + p(11, 2)) + p(12, 3))).0,
                (((p(10, 4) + p(14, 3)) - p(15, 2))).0,
                (((p(11, 4) + p(15, 1)) - p(13, 3))).0,
                (((p(12, 4) + p(13, 2)) - p(14, 1))).0,
                (((p(20, 3) + p(23, 0)) - (p(16, 4) + p(21, 2)))).0,
                (((p(21, 1) + p(24, 0)) - (p(17, 4) + p(19, 3)))).0,
                (((p(19, 2) + p(25, 0)) - (p(18, 4) + p(20, 1)))).0,
                (((p(16, 1) + p(17, 2)) + (p(18, 3) - p(22, 0)))).0,
                (((p(22, 4) - p(23, 1)) - (p(24, 2) + p(25, 3)))).0,
                ((((p(26, 1) + p(27, 2)) + p(28, 3)) + (p(29, 4) + p(30, 0)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Bivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Bivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                (((p(1, 4) + p(4, 1)) - p(3, 2))).0,
                (((p(1, 5) + p(2, 2)) - p(4, 0))).0,
                (((p(1, 6) + p(3, 0)) - p(2, 1))).0,
                (((p(5, 0) - p(1, 7)) - p(2, 3))).0,
                (((p(5, 1) - p(1, 8)) - p(3, 3))).0,
                (((p(5, 2) - p(1, 9)) - p(4, 3))).0,
                (((p(2, 4) + p(3, 5)) + p(4, 6))).0,
                (((p(4, 8) + p(5, 4)) - p(3, 9))).0,
                (((p(2, 9) + p(5, 5)) - p(4, 7))).0,
                (((p(3, 7) + p(5, 6)) - p(2, 8))).0,
                ((((p(7, 9) + p(15, 1)) - p(8, 8)) - ((p(9, 4) + p(10, 3)) + p(14, 2)))).0,
                ((((p(8, 7) + p(13, 2)) - p(6, 9)) - ((p(9, 5) + p(11, 3)) + p(15, 0)))).0,
                ((((p(6, 8) + p(14, 0)) - p(7, 7)) - ((p(9, 6) + p(12, 3)) + p(13, 1)))).0,
                ((((p(6, 4) + p(7, 5)) + p(8, 6)) + ((p(10, 0) + p(11, 1)) + p(12, 2)))).0,
                (-(((p(10, 7) + p(11, 8)) + p(12, 9)) + ((p(13, 4) + p(14, 5)) + p(15, 6)))).0,
                (((((p(19, 4) + p(20, 5)) + p(21, 6)) + (p(23, 0) + p(24, 1))) + (((p(25, 2) - p(16, 7)) - p(17, 8)) - (p(18, 9) + p(22, 3))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Trivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Trivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 5)).0,
                (p(0, 6)).0,
                (p(0, 7)).0,
                (p(0, 8)).0,
                (p(0, 9)).0,
                (((p(3, 5) + p(5, 0)) - (p(1, 7) + p(4, 4)))).0,
                (((p(4, 3) + p(5, 1)) - (p(1, 8) + p(2, 5)))).0,
                (((p(2, 4) + p(5, 2)) - (p(1, 9) + p(3, 3)))).0,
                (((p(1, 6) - p(2, 0)) - (p(3, 1) + p(4, 2)))).0,
                (((p(2, 7) + p(3, 8)) + (p(4, 9) - p(5, 6)))).0,
                (((((p(6, 7) + p(7, 8)) + p(8, 9)) + (p(10, 3) + p(11, 4))) + (((p(12, 5) - p(9, 6)) - p(13, 0)) - (p(14, 1) + p(15, 2))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Quadvector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Quadvector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                ((((p(1, 4) + p(2, 0)) + p(3, 1)) + (p(4, 2) + p(5, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Pseudoscalar<S2, T>> for Multivector<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Pseudoscalar<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Motor<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Motor<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                ((p(0, 1) + p(6, 0))).0,
                ((p(0, 2) + p(7, 0))).0,
                ((p(0, 3) + p(8, 0))).0,
                ((p(0, 4) + p(9, 0))).0,
                ((p(0, 5) + p(10, 0))).0,
                ((p(0, 6) + p(11, 0))).0,
                ((p(0, 7) + p(12, 0))).0,
                ((p(0, 8) + p(13, 0))).0,
                ((p(0, 9) + p(14, 0))).0,
                ((p(0, 10) + p(15, 0))).0,
                (((p(1, 5) + p(4, 2)) + (p(16, 0) - p(3, 3)))).0,
                (((p(1, 6) + p(2, 3)) + (p(17, 0) - p(4, 1)))).0,
                (((p(1, 7) + p(3, 1)) + (p(18, 0) - p(2, 2)))).0,
                (((p(5, 1) + p(19, 0)) - (p(1, 8) + p(2, 4)))).0,
                (((p(5, 2) + p(20, 0)) - (p(1, 9) + p(3, 4)))).0,
                (((p(5, 3) + p(21, 0)) - (p(1, 10) + p(4, 4)))).0,
                (((p(2, 5) + p(3, 6)) + (p(4, 7) + p(22, 0)))).0,
                (((p(4, 9) + p(5, 5)) + (p(23, 0) - p(3, 10)))).0,
                (((p(2, 10) + p(5, 6)) + (p(24, 0) - p(4, 8)))).0,
                (((p(3, 8) + p(5, 7)) + (p(25, 0) - p(2, 9)))).0,
                ((((p(0, 11) + p(7, 10)) + (p(15, 2) + p(26, 0))) - ((p(8, 9) + p(9, 5)) + (p(10, 4) + p(14, 3))))).0,
                ((((p(0, 12) + p(8, 8)) + (p(13, 3) + p(27, 0))) - ((p(6, 10) + p(9, 6)) + (p(11, 4) + p(15, 1))))).0,
                ((((p(0, 13) + p(6, 9)) + (p(14, 1) + p(28, 0))) - ((p(7, 8) + p(9, 7)) + (p(12, 4) + p(13, 2))))).0,
                ((((p(0, 14) + p(6, 5)) + (p(7, 6) + p(8, 7))) + ((p(10, 1) + p(11, 2)) + (p(12, 3) + p(29, 0))))).0,
                ((((p(0, 15) + p(30, 0)) - (p(10, 8) + p(11, 9))) - ((p(12, 10) + p(13, 5)) + (p(14, 6) + p(15, 7))))).0,
                (((((p(1, 15) + p(2, 11)) + (p(3, 12) + p(4, 13))) + ((p(5, 14) + p(19, 5)) + (p(20, 6) + p(21, 7)))) + (((p(23, 1) + p(24, 2)) + (p(25, 3) + p(31, 0))) - ((p(16, 8) + p(17, 9)) + (p(18, 10) + p(22, 4)))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Odd<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Odd<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 0)).0,
                (p(0, 1)).0,
                (p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 4)).0,
                ((p(1, 1) - p(2, 0))).0,
                ((p(1, 2) - p(3, 0))).0,
                ((p(1, 3) - p(4, 0))).0,
                ((p(1, 4) - p(5, 0))).0,
                ((p(3, 3) - p(4, 2))).0,
                ((p(4, 1) - p(2, 3))).0,
                ((p(2, 2) - p(3, 1))).0,
                ((p(5, 1) - p(2, 4))).0,
                ((p(5, 2) - p(3, 4))).0,
                ((p(5, 3) - p(4, 4))).0,
                (((p(0, 5) + p(7, 3)) + (p(10, 0) - p(8, 2)))).0,
                (((p(0, 6) + p(8, 1)) + (p(11, 0) - p(6, 3)))).0,
                (((p(0, 7) + p(6, 2)) + (p(12, 0) - p(7, 1)))).0,
                (((p(0, 8) + p(6, 4)) - (p(9, 1) + p(13, 0)))).0,
                (((p(0, 9) + p(7, 4)) - (p(9, 2) + p(14, 0)))).0,
                (((p(0, 10) + p(8, 4)) - (p(9, 3) + p(15, 0)))).0,
                (((p(0, 11) + p(10, 1)) + (p(11, 2) + p(12, 3)))).0,
                (((p(0, 12) + p(10, 4)) + (p(14, 3) - p(15, 2)))).0,
                (((p(0, 13) + p(11, 4)) + (p(15, 1) - p(13, 3)))).0,
                (((p(0, 14) + p(12, 4)) + (p(13, 2) - p(14, 1)))).0,
                ((((p(3, 10) + p(5, 5)) + (p(20, 3) + p(23, 0))) - ((p(1, 12) + p(4, 9)) + (p(16, 4) + p(21, 2))))).0,
                ((((p(4, 8) + p(5, 6)) + (p(21, 1) + p(24, 0))) - ((p(1, 13) + p(2, 10)) + (p(17, 4) + p(19, 3))))).0,
                ((((p(2, 9) + p(5, 7)) + (p(19, 2) + p(25, 0))) - ((p(1, 14) + p(3, 8)) + (p(18, 4) + p(20, 1))))).0,
                ((((p(1, 11) + p(16, 1)) + (p(17, 2) + p(18, 3))) - ((p(2, 5) + p(3, 6)) + (p(4, 7) + p(22, 0))))).0,
                ((((p(2, 12) + p(3, 13)) + (p(4, 14) + p(22, 4))) - ((p(5, 11) + p(23, 1)) + (p(24, 2) + p(25, 3))))).0,
                (((((p(0, 15) + p(6, 12)) + (p(7, 13) + p(8, 14))) + ((p(10, 8) + p(11, 9)) + (p(12, 10) + p(26, 1)))) + (((p(27, 2) + p(28, 3)) + (p(29, 4) + p(30, 0))) - ((p(9, 11) + p(13, 5)) + (p(14, 6) + p(15, 7)))))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Wedge<Multivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn wedge(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (p(0, 0)).0,
                ((p(0, 1) + p(1, 0))).0,
                ((p(0, 2) + p(2, 0))).0,
                ((p(0, 3) + p(3, 0))).0,
                ((p(0, 4) + p(4, 0))).0,
                ((p(0, 5) + p(5, 0))).0,
                (((p(0, 6) + p(1, 2)) + (p(6, 0) - p(2, 1)))).0,
                (((p(0, 7) + p(1, 3)) + (p(7, 0) - p(3, 1)))).0,
                (((p(0, 8) + p(1, 4)) + (p(8, 0) - p(4, 1)))).0,
                (((p(0, 9) + p(1, 5)) + (p(9, 0) - p(5, 1)))).0,
                (((p(0, 10) + p(3, 4)) + (p(10, 0) - p(4, 3)))).0,
                (((p(0, 11) + p(4, 2)) + (p(11, 0) - p(2, 4)))).0,
                (((p(0, 12) + p(2, 3)) + (p(12, 0) - p(3, 2)))).0,
                (((p(0, 13) + p(5, 2)) + (p(13, 0) - p(2, 5)))).0,
                (((p(0, 14) + p(5, 3)) + (p(14, 0) - p(3, 5)))).0,
                (((p(0, 15) + p(5, 4)) + (p(15, 0) - p(4, 5)))).0,
                ((((p(0, 16) + p(1, 10)) + (p(4, 7) + p(7, 4))) + ((p(10, 1) + p(16, 0)) - (p(3, 8) + p(8, 3))))).0,
                ((((p(0, 17) + p(1, 11)) + (p(2, 8) + p(8, 2))) + ((p(11, 1) + p(17, 0)) - (p(4, 6) + p(6, 4))))).0,
                ((((p(0, 18) + p(1, 12)) + (p(3, 6) + p(6, 3))) + ((p(12, 1) + p(18, 0)) - (p(2, 7) + p(7, 2))))).0,
                ((((p(0, 19) + p(5, 6)) + (p(6, 5) + p(19, 0))) - ((p(1, 13) + p(2, 9)) + (p(9, 2) + p(13, 1))))).0,
                ((((p(0, 20) + p(5, 7)) + (p(7, 5) + p(20, 0))) - ((p(1, 14) + p(3, 9)) + (p(9, 3) + p(14, 1))))).0,
                ((((p(0, 21) + p(5, 8)) + (p(8, 5) + p(21, 0))) - ((p(1, 15) + p(4, 9)) + (p(9, 4) + p(15, 1))))).0,
                ((((p(0, 22) + p(2, 10)) + (p(3, 11) + p(4, 12))) + ((p(10, 2) + p(11, 3)) + (p(12, 4) + p(22, 0))))).0,
                ((((p(0, 23) + p(4, 14)) + (p(5, 10) + p(10, 5))) + ((p(14, 4) + p(23, 0)) - (p(3, 15) + p(15, 3))))).0,
                ((((p(0, 24) + p(2, 15)) + (p(5, 11) + p(11, 5))) + ((p(15, 2) + p(24, 0)) - (p(4, 13) + p(13, 4))))).0,
                ((((p(0, 25) + p(3, 13)) + (p(5, 12) + p(12, 5))) + ((p(13, 3) + p(25, 0)) - (p(2, 14) + p(14, 2))))).0,
                (((((p(0, 26) + p(3, 21)) + (p(5, 16) + p(7, 15))) + ((p(15, 7) + p(20, 4)) + (p(23, 1) + p(26, 0)))) - (((p(1, 23) + p(4, 20)) + (p(8, 14) + p(9, 10))) + ((p(10, 9) + p(14, 8)) + (p(16, 5) + p(21, 3)))))).0,
                (((((p(0, 27) + p(4, 19)) + (p(5, 17) + p(8, 13))) + ((p(13, 8) + p(21, 2)) + (p(24, 1) + p(27, 0)))) - (((p(1, 24) + p(2, 21)) + (p(6, 15) + p(9, 11))) + ((p(11, 9) + p(15, 6)) + (p(17, 5) + p(19, 4)))))).0,
                (((((p(0, 28) + p(2, 20)) + (p(5, 18) + p(6, 14))) + ((p(14, 6) + p(19, 3)) + (p(25, 1) + p(28, 0)))) - (((p(1, 25) + p(3, 19)) + (p(7, 13) + p(9, 12))) + ((p(12, 9) + p(13, 7)) + (p(18, 5) + p(20, 2)))))).0,
                (((((p(0, 29) + p(1, 22)) + (p(6, 10) + p(7, 11))) + ((p(8, 12) + p(10, 6)) + (p(11, 7) + p(12, 8)))) + (((p(16, 2) + p(17, 3)) + (p(18, 4) + p(29, 0))) - ((p(2, 16) + p(3, 17)) + (p(4, 18) + p(22, 1)))))).0,
                (((((p(0, 30) + p(2, 23)) + (p(3, 24) + p(4, 25))) + ((p(22, 5) + p(30, 0)) - (p(5, 22) + p(10, 13)))) - (((p(11, 14) + p(12, 15)) + (p(13, 10) + p(14, 11))) + ((p(15, 12) + p(23, 2)) + (p(24, 3) + p(25, 4)))))).0,
                ((((((p(0, 31) + p(1, 30)) + (p(2, 26) + p(3, 27))) + ((p(4, 28) + p(5, 29)) + (p(6, 23) + p(7, 24)))) + (((p(8, 25) + p(10, 19)) + (p(11, 20) + p(12, 21))) + ((p(19, 10) + p(20, 11)) + (p(21, 12) + p(23, 6))))) + ((((p(24, 7) + p(25, 8)) + (p(26, 2) + p(27, 3))) + ((p(28, 4) + p(29, 5)) + (p(30, 1) + p(31, 0)))) - (((p(9, 22) + p(13, 16)) + (p(14, 17) + p(15, 18))) + ((p(16, 13) + p(17, 14)) + (p(18, 15) + p(22, 9))))))).0,
            ],
        }
    }
}
