//! The symbolic law harness (docs/laws.md).
//!
//! Coefficients are `gax_gen::sym::Sym`: handles to hash-consed exact polynomials over ℚ with
//! unbounded expansion, so `==` on symbolic values is polynomial identity. A law checked on
//! fresh symbolic inputs is proved for that algebra, those kinds and that slot shape; the code
//! under test is generic over the slots, so the shapes stand for all of them. Laws that hold
//! only under a condition (unit versors, the conditions that make an element a versor) are
//! checked modulo the ideal of that condition, whose generators come from the library's own
//! products on the symbolic input.
//!
//! Each `tests/laws_*.rs` is one generated `law_suite!` invocation listing what the generator
//! emitted for that algebra.

#![allow(
    dead_code,
    unused_macros,
    unused_imports,
    clippy::all,
    clippy::pedantic
)]

use gax::{Coef, Extensor, Kind, Slots};
use gax_gen::groebner::{groebner, normal_form};
use gax_gen::poly::Poly;
pub use gax_gen::sym::Sym;
use std::cell::Cell;

/// The coefficient type of the proofs.
pub type T = Sym;

thread_local! {
    static NEXT: Cell<usize> = const { Cell::new(0) };
}

/// Start a new proof: clear the arena (handles from earlier proofs become invalid).
pub fn reset() {
    Sym::reset();
    NEXT.set(0);
}

/// A fresh symbolic variable.
pub fn var() -> Sym {
    let i = NEXT.get();
    NEXT.set(i + 1);
    Sym::input(0, i)
}

/// A value, map or form whose coefficients are fresh variables.
pub fn fresh<M: Extensor<Coef = Sym>>() -> M {
    M::from_coeffs(<M::Kind as Kind>::arr_from_fn(|_| {
        <M::Slots as Slots>::from_flat(&mut |_| var(), 0)
    }))
}

/// All coefficients, output first.
pub fn flat<M: Extensor>(m: &M) -> Vec<M::Coef> {
    let mut v = Vec::new();
    for col in m.coeffs().as_ref() {
        for k in 0..<M::Slots as Slots>::SIZE {
            v.push(<M::Slots as Slots>::get_flat(col, k));
        }
    }
    v
}

/// A Gröbner basis of the ideal generated by `gens`.
pub fn basis(gens: &[Poly]) -> Vec<Poly> {
    groebner(gens, 4000).expect("a small ideal")
}

/// Whether `a == b` modulo the ideal with Gröbner basis `basis`.
pub fn same_mod<M: Extensor<Coef = Sym>>(a: &M, b: &M, basis: &[Poly]) -> bool {
    flat(a)
        .into_iter()
        .zip(flat(b))
        .all(|(x, y)| normal_form(&(&x.poly() - &y.poly()), basis).is_zero())
}

/// The scalar part of a value (`None` if its kind has no scalar blade).
pub fn scalar_part<M: Extensor<Slots = (), Coef = Sym>>(m: &M) -> Option<Sym> {
    let i = <M::Kind as Kind>::BLADES.iter().position(|b| *b == "1")?;
    Some(m.coeffs().as_ref()[i])
}

/// `N = <v ~v>₀` and a Gröbner basis of the other parts of `v ~v`: the conditions under
/// which `v` is a versor. `vv` is `v * v.reverse()`.
pub fn versor_basis<M: Extensor<Slots = (), Coef = Sym>>(vv: &M) -> (Sym, Vec<Poly>) {
    let n = scalar_part(vv).expect("v ~v has a scalar part");
    let gens: Vec<Poly> = <M::Kind as Kind>::BLADES
        .iter()
        .zip(vv.coeffs().as_ref())
        .filter(|(b, _)| **b != "1")
        .map(|(_, c)| c.poly())
        .filter(|p| !p.is_zero())
        .collect();
    (n, basis(&gens))
}

/// A Gröbner basis of `v ~v = 1`. `vv` is `v * v.reverse()`.
pub fn unit_basis<M: Extensor<Slots = (), Coef = Sym>>(vv: &M) -> Vec<Poly> {
    let one = Poly::constant(gax_gen::poly::Rational::ONE);
    let gens: Vec<Poly> = <M::Kind as Kind>::BLADES
        .iter()
        .zip(vv.coeffs().as_ref())
        .map(|(b, c)| {
            if *b == "1" {
                &c.poly() - &one
            } else {
                c.poly()
            }
        })
        .filter(|p| !p.is_zero())
        .collect();
    basis(&gens)
}

/// `sign · N^power`.
pub fn factor(n: Sym, sign: i64, power: u32) -> Sym {
    let mut f = Sym::from_i64(sign);
    for _ in 0..power {
        f = f * n;
    }
    f
}

/// A blade name in canonical order, and the sign of the permutation to it.
fn canonical(name: &str) -> (String, i64) {
    if name == "1" {
        return (String::new(), 1);
    }
    let mut c: Vec<char> = name.trim_start_matches('e').chars().collect();
    let mut sign = 1;
    for i in 0..c.len() {
        for j in 0..c.len() - 1 - i {
            if c[j] > c[j + 1] {
                c.swap(j, j + 1);
                sign = -sign;
            }
        }
    }
    (c.into_iter().collect(), sign)
}

/// Whether the value `y` equals the value `z` of a larger kind modulo the ideal: equal on the
/// blades of `y`, and zero on the blades `y` lacks.
pub fn projects_to<Y, Z>(y: &Y, z: &Z, basis: &[Poly]) -> bool
where
    Y: Extensor<Slots = (), Coef = Sym>,
    Z: Extensor<Slots = (), Coef = Sym>,
{
    let yb: Vec<(String, i64)> = <Y::Kind as Kind>::BLADES
        .iter()
        .map(|b| canonical(b))
        .collect();
    let (yc, zc) = (y.coeffs().as_ref(), z.coeffs().as_ref());
    let zero_mod = |p: Poly| normal_form(&p, basis).is_zero();
    let mut covered = vec![false; yb.len()];
    for (zb, zv) in <Z::Kind as Kind>::BLADES.iter().zip(zc) {
        let (zn, zs) = canonical(zb);
        match yb.iter().position(|(n, _)| *n == zn) {
            Some(i) => {
                covered[i] = true;
                let (_, ys) = yb[i];
                // Coefficients of the same blade in the two orientations.
                let yv = yc[i]
                    .poly()
                    .scale(gax_gen::poly::Rational::int(i128::from(ys * zs)));
                if !zero_mod(&zv.poly() - &yv) {
                    return false;
                }
            }
            None => {
                if !zero_mod(zv.poly()) {
                    return false;
                }
            }
        }
    }
    // Blades of y that z lacks must vanish.
    covered
        .iter()
        .zip(yc)
        .all(|(c, v)| *c || zero_mod(v.poly()))
}

/// The adjoint of the map `t: B<(B,)>` through the pairing `p: Scalar<(A, B)>`, which must be
/// a constant signed permutation matrix: the map `adj: A<(A,)>` with
/// `p(adj(l), x) == p(l, t(x))`. With `P⁻¹ = Pᵀ`, `adj = P tᵀ Pᵀ`.
pub fn adjoint<A: Kind, B: Kind, T: Coef, P, M>(p: &P, t: &M) -> A::Mv<(A,), T>
where
    P: Extensor<Slots = (A, B), Coef = T>,
    M: Extensor<Kind = B, Slots = (B,), Coef = T>,
{
    let nb = B::N;
    let pc = |a: usize, b: usize| <(A, B) as Slots>::get_flat(&p.coeffs().as_ref()[0], a * nb + b);
    let tc = |o: usize, i: usize| <(B,) as Slots>::get_flat(&t.coeffs().as_ref()[o], i);
    Extensor::from_coeffs(A::arr_from_fn(|i| {
        <(A,) as Slots>::from_flat(
            &mut |j| {
                let mut acc = T::zero();
                for k in 0..nb {
                    for l in 0..nb {
                        acc = acc + pc(i, k) * tc(l, k) * pc(j, l);
                    }
                }
                acc
            },
            0,
        )
    }))
}

/// The determinant of a map, read from its extension to the top grade.
pub fn top_coefficient<M: Extensor>(m: &M) -> M::Coef {
    <M::Slots as Slots>::get_flat(&m.coeffs().as_ref()[0], 0)
}

/// Relative closeness of two f64 extensors (for the property tests against solvers).
pub fn close<M: Extensor<Coef = f64>>(a: &M, b: &M, tol: f64) -> bool {
    let (a, b) = (flat(a), flat(b));
    let scale = a.iter().chain(&b).fold(1.0f64, |m, x| m.max(x.abs()));
    a.iter().zip(&b).all(|(x, y)| (x - y).abs() <= tol * scale)
}

/// A pseudo-random f64 map or value.
pub fn random_f64<M: Extensor<Coef = f64>>(seed: &mut u64) -> M {
    let mut next = || {
        *seed ^= *seed << 13;
        *seed ^= *seed >> 7;
        *seed ^= *seed << 17;
        (*seed >> 11) as f64 / (1u64 << 53) as f64 * 2.0 - 1.0
    };
    M::from_coeffs(<M::Kind as Kind>::arr_from_fn(|_| {
        <M::Slots as Slots>::from_flat(&mut |_| next(), 0)
    }))
}

/// Fail with the law's name (the symbolic operands would be unreadable).
#[track_caller]
pub fn law(holds: bool, name: &str) {
    assert!(holds, "law failed: {name}");
}

/// The law suite of an algebra. The lists are generated from what the generator emitted.
macro_rules! law_suite {
    (
        scalar: $scalar:ident, slot: $slot:ident, other: $other:ident,
        products: [$(($ptr:ident, $pm:ident, $pa:ident, $pb:ident)),* $(,)?],
        unary: [$(($utr:ident, $um:ident, $ua:ident)),* $(,)?],
        sandwiches: [$(($sv:ident, $sx:ident)),* $(,)?],
        plain_sandwiches: [$(($pv:ident, $px:ident)),* $(,)?],
        actions: [$(($av:ident, $ax:ident)),* $(,)?],
        equivariant: [$(($ev:ident, $etr:ident, $em:ident, $ea:ident, $eb:ident, $es:literal, $ep:literal)),* $(,)?],
        unit_equivariant: [$(($qv:ident, $qtr:ident, $qm:ident, $qa:ident, $qb:ident, $qs:literal)),* $(,)?],
        violations: [$(($nv:ident, $ntr:ident, $nm:ident, $na:ident, $nb:ident)),* $(,)?],
        conjugations: [$(($cv:ident, $cx:ident, $cs:literal, $cp:literal)),* $(,)?],
        outer: [$(($ov:ident, $ob:ident)),* $(,)?],
        top: [$(($tv:ident, $tb:ident)),* $(,)?],
        unit_det: [$(($dv:ident, $dx:ident, $dt:ident, $de:literal)),* $(,)?],
        pairings: [$(($rtr:ident, $rm:ident, $ra:ident, $rb:ident)),* $(,)?] $(,)?
    ) => {
        #[allow(unused_imports)]
        use law_suite::{
            adjoint, close, factor, flat, fresh, law, projects_to, random_f64, reset,
            same_mod, top_coefficient, unit_basis, var, versor_basis, T,
        };
        #[allow(unused_imports)]
        use gax::{Coef, Extensor, Kind, Unit};

        /// A: the multicategory laws (units, associativity, interchange, symmetry).
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn multicategory() {
            reset();
            let f: $other<($slot,), T> = fresh();
            law($other::slot().of(f) == f, "left unit");
            law(f.of($slot::slot()) == f, "right unit");
            let g: $other<($slot, $other), T> = fresh();
            law(g.at::<1>().of($other::slot()) == g.at::<1>(), "unit in slot 1");
            law(g.of($slot::slot()) == g, "unit in slot 0");

            reset();
            let f: $other<($slot, $other), T> = fresh();
            let g: $slot<($other, $slot), T> = fresh();
            let h: $other<($slot,), T> = fresh();
            law(f.of(g.of(h)) == f.of(g).of(h), "associativity with multi-slot maps");

            reset();
            let f: $other<($slot, $other), T> = fresh();
            let g: $slot<($other,), T> = fresh();
            let h: $other<($slot,), T> = fresh();
            let first = f.of(g).at::<1>().of(h);
            let second = f.at::<1>().of(h).at::<1>().of(g);
            law(first == second.at::<1>(), "interchange of maps");
            let (x, y): ($slot<(), T>, $other<(), T>) = (fresh(), fresh());
            law(f.of(x).of(y) == f.at::<1>().of(y).of(x), "interchange of values");

            reset();
            let q: $slot<($slot, $other), T> = fresh();
            law(q.at::<1>().at::<1>() == q, "transposition is an involution");
            let b: $scalar<($slot, $other), T> = fresh();
            law(b.swap().swap() == b, "swap is an involution");
            let r: $slot<($slot, $other, $scalar), T> = fresh();
            law(r.at::<1>().at::<1>() == r, "σ² = 1");
            law(r.at::<2>().at::<2>().at::<2>() == r, "τ³ = 1");
            law(r.at::<1>().at::<2>().at::<1>() == r.at::<2>().at::<2>(), "στσ = τ²");
            let f: $other<($slot, $other), T> = fresh();
            let y: $other<(), T> = fresh();
            law(f.at::<1>().of(y) == f.fill(y), "permuting then substituting");

            reset();
            let m: $slot<($slot, $other, $slot), T> = fresh();
            let re = gax::slots::reassoc::<($slot,), ($other,), ($slot,), _>(m);
            law(flat(&re) == flat(&m), "reassoc is the identity on coefficients");
        }

        /// B: `of` is linear in the map and in the argument.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn linearity() {
            reset();
            let (f, g): ($other<($slot,), T>, $other<($slot,), T>) = (fresh(), fresh());
            let (x, y): ($slot<(), T>, $slot<(), T>) = (fresh(), fresh());
            let s = var();
            law(f.of(x + y) == f.of(x) + f.of(y), "additive in the argument");
            law((f + g).of(x) == f.of(x) + g.of(x), "additive in the map");
            law(f.of(x.gp(s)) == f.of(x).gp(s), "homogeneous in the argument");
            law(f.gp(s).of(x) == f.of(x).gp(s), "homogeneous in the map");
            law(f.of($slot::<(), T>::zero()) == $other::<(), T>::zero(), "zero");
            let h: $other<($slot, $other), T> = fresh();
            law(h.of(x + y) == h.of(x) + h.of(y), "additive in slot 0 of a form");
        }

        /// C: lifting is a homomorphism, for every product and unary operation.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn lifting() {
            $((|| {
                reset();
                let f: $pa<($slot,), T> = fresh();
                let g: $pb<($slot,), T> = fresh();
                let (x, y): ($slot<(), T>, $slot<(), T>) = (fresh(), fresh());
                let (a, b): ($pa<(), T>, $pb<(), T>) = (fresh(), fresh());
                let name = concat!(stringify!($pm), " of ", stringify!($pa), " and ", stringify!($pb));
                law(gax::$ptr::$pm(f, g).of(x).of(y) == gax::$ptr::$pm(f.of(x), g.of(y)), name);
                law(gax::$ptr::$pm(a, g).of(y) == gax::$ptr::$pm(a, g.of(y)), name);
                law(gax::$ptr::$pm(f, b).of(x) == gax::$ptr::$pm(f.of(x), b), name);
            })();)*
            $((|| {
                reset();
                let f: $ua<($slot,), T> = fresh();
                let x: $slot<(), T> = fresh();
                law(
                    gax::$utr::$um(f).of(x) == gax::$utr::$um(f.of(x)),
                    concat!(stringify!($um), " of ", stringify!($ua)),
                );
            })();)*
        }

        /// D: versors act (exactly for plain versors, modulo `u ~u = 1` for units).
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn versor_action() {
            $((|| {
                reset();
                let (a, b): ($av<(), T>, $av<(), T>) = (fresh(), fresh());
                let x: $ax<(), T> = fresh();
                let name = concat!(stringify!($av), " on ", stringify!($ax));
                law((a * b) >> x == a >> (b >> x), name);
                law((a * b) >> $ax::slot() == (a >> $ax::slot()).of(b >> $ax::slot()), name);
            })();)*
            $((|| {
                reset();
                let v: $sv<(), T> = fresh();
                let x: $sx<(), T> = fresh();
                let basis = unit_basis(&(v * v.reverse()));
                let u = Unit::new_unchecked(v);
                law(
                    same_mod(&(u << (u >> x)), &x, &basis),
                    concat!("Unit<", stringify!($sv), "> << >> ", stringify!($sx)),
                );
            })();)*
        }

        /// D: equivariance of the products, with the generator's factors, and the negative
        /// controls (the plain law without its factor must fail).
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn equivariance() {
            $((|| {
                reset();
                let v: $ev<(), T> = fresh();
                let (a, b): ($ea<(), T>, $eb<(), T>) = (fresh(), fresh());
                let (n, basis) = versor_basis(&(v * v.reverse()));
                let lhs = gax::$etr::$em(v >> a, v >> b);
                let rhs = v >> gax::$etr::$em(a, b);
                law(
                    same_mod(&lhs, &rhs.gp(factor(n, $es, $ep)), &basis),
                    concat!(stringify!($ev), " ", stringify!($em), " ", stringify!($ea), " ", stringify!($eb)),
                );
            })();)*
            $((|| {
                reset();
                let v: $qv<(), T> = fresh();
                let (a, b): ($qa<(), T>, $qb<(), T>) = (fresh(), fresh());
                let basis = unit_basis(&(v * v.reverse()));
                let u = Unit::new_unchecked(v);
                law(
                    same_mod(
                        &gax::$qtr::$qm(u >> a, u >> b),
                        &(u >> gax::$qtr::$qm(a, b)).gp(T::from_i64($qs)),
                        &basis,
                    ),
                    concat!("Unit<", stringify!($qv), "> ", stringify!($qm), " ", stringify!($qa), " ", stringify!($qb)),
                );
            })();)*
            $((|| {
                reset();
                let v: $nv<(), T> = fresh();
                let (a, b): ($na<(), T>, $nb<(), T>) = (fresh(), fresh());
                let (_, basis) = versor_basis(&(v * v.reverse()));
                law(
                    !same_mod(&gax::$ntr::$nm(v >> a, v >> b), &(v >> gax::$ntr::$nm(a, b)), &basis),
                    concat!("negative control: ", stringify!($nv), " ", stringify!($nm), " without its factor"),
                );
            })();)*
        }

        /// D: conjugation of maps, `conj_m(f) = (m >> f).of(m.reverse() >> K::slot())`.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn conjugation() {
            $((|| {
                reset();
                let m: $cv<(), T> = fresh();
                let f: $cx<($cx,), T> = fresh();
                let x: $cx<(), T> = fresh();
                let conj = |m: $cv<(), T>, f: $cx<($cx,), T>| (m >> f).of(m.reverse() >> $cx::slot());
                let (n, basis) = versor_basis(&(m * m.reverse()));
                let fac = factor(n, $cs, $cp);
                let name = concat!("conjugation by ", stringify!($cv), " of maps on ", stringify!($cx));
                law(same_mod(&conj(m, f).of(m >> x), &(m >> f.of(x)).gp(fac), &basis), name);
                // For a unit versor the factor is its sign alone.
                let ub = unit_basis(&(m * m.reverse()));
                let u = Unit::new_unchecked(m);
                let uconj = (u >> f).of(u.inverse() >> $cx::slot());
                law(same_mod(&uconj.of(u >> x), &(u >> f.of(x)).gp(T::from_i64($cs)), &ub), name);
            })();)*
        }

        /// D: conjugation is multiplicative and composes: `conj_m(f) ∘ conj_m(g)` is
        /// `f · conj_m(f ∘ g)` modulo the versor conditions, and `conj_{ab} = conj_a ∘ conj_b`
        /// exactly. These expand to degree 8 in one free versor, or degree 4 in two, which takes
        /// minutes in algebras with a non-degenerate metric, so they run with `--ignored` (a CI
        /// job does).
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        #[ignore = "slow: run with --ignored"]
        fn conjugation_slow() {
            $((|| {
                reset();
                let (m, m2): ($cv<(), T>, $cv<(), T>) = (fresh(), fresh());
                let (f, g): ($cx<($cx,), T>, $cx<($cx,), T>) = (fresh(), fresh());
                let conj = |m: $cv<(), T>, f: $cx<($cx,), T>| (m >> f).of(m.reverse() >> $cx::slot());
                let name = concat!("conjugation by ", stringify!($cv), " of maps on ", stringify!($cx));
                law(conj(m * m2, f) == conj(m, conj(m2, f)), name);
                let (n, basis) = versor_basis(&(m * m.reverse()));
                let fac = factor(n, $cs, $cp);
                law(same_mod(&conj(m, f).of(conj(m, g)), &conj(m, f.of(g)).gp(fac), &basis), name);
            })();)*
        }

        /// E: the outermorphism is a functor, and the determinant (its top grade) is multiplicative.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn outermorphism() {
            $((|| {
                reset();
                let (f, g): ($ov<($ov,), T>, $ov<($ov,), T>) = (fresh(), fresh());
                let name = concat!(stringify!($ov), " to ", stringify!($ob));
                law(
                    f.of(g).outermorphism::<$ob>() == f.outermorphism::<$ob>().of(g.outermorphism::<$ob>()),
                    name,
                );
                law($ov::slot().outermorphism::<$ob>() == $ob::<(), T>::slot(), name);
            })();)*
            $((|| {
                reset();
                let (f, g): ($tv<($tv,), T>, $tv<($tv,), T>) = (fresh(), fresh());
                let det = |m: $tv<($tv,), T>| top_coefficient(&m.outermorphism::<$tb>());
                law(det(f.of(g)) == det(f) * det(g), concat!("det on ", stringify!($tv), " is multiplicative"));
            })();)*
            $((|| {
                reset();
                let v: $dv<(), T> = fresh();
                let basis = unit_basis(&(v * v.reverse()));
                let u = Unit::new_unchecked(v);
                let d = top_coefficient(&(u >> $dx::slot()).outermorphism::<$dt>());
                let expected = if $de { 1 } else { -1 };
                law(
                    gax_gen::groebner::normal_form(&(&d.poly() - &T::from_i64(expected).poly()), &basis).is_zero(),
                    concat!("det of Unit<", stringify!($dv), "> on ", stringify!($dx)),
                );
            })();)*
        }

        /// F: the trace is cyclic, linear, and agrees with `trace_at`.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn trace() {
            reset();
            let f: $slot<($other,), T> = fresh();
            let g: $other<($slot,), T> = fresh();
            law(f.of(g).trace() == g.of(f).trace(), "cyclic");
            law(
                $slot::<(), T>::slot().trace() == T::from_i64(<$slot as Kind>::N as i64),
                "trace of the identity",
            );
            let (a, b): ($slot<($slot,), T>, $slot<($slot,), T>) = (fresh(), fresh());
            let s = var();
            law((a + b).trace() == a.trace() + b.trace(), "additive");
            law(a.gp(s).trace() == s * a.trace(), "homogeneous");
            let m: $slot<($other, $slot), T> = fresh();
            let y: $other<(), T> = fresh();
            let form = m.trace_at::<1>();
            law(form.of(y).coeffs().as_ref()[0] == m.of(y).trace(), "trace_at");
        }

        /// H: `fill` is the diagonal.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn fill() {
            reset();
            let b: $scalar<($slot, $slot), T> = fresh();
            let (x, y): ($slot<(), T>, $slot<(), T>) = (fresh(), fresh());
            let s = var();
            law(b.fill(x.gp(s)) == b.fill(x).gp(s * s), "homogeneous of degree 2");
            law(b.fill(x) == b.of(x).of(x), "binding the same value in each slot");
            law(
                b.fill(x + y) - b.fill(x) - b.fill(y) == b.of(x).of(y) + b.of(y).of(x),
                "polarization",
            );
            law(b.fill(x) == (b + b.swap()).gp(T::from_f64(0.5)).fill(x), "symmetrization");
            let m: $other<($slot, $other, $slot), T> = fresh();
            law(m.fill(x) == m.of(x).at::<1>().of(x), "fill of a map with two slots of a kind");
            law(m.fill(x.gp(s)) == m.fill(x).gp(s * s), "homogeneous in the filled kind");
        }

        /// G: adjoints through constant signed-permutation pairings.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn adjoint_laws() {
            $((|| {
                reset();
                let p: $scalar<($ra, $rb), T> = gax::$rtr::$rm($ra::slot(), $rb::slot());
                let q: $scalar<($rb, $ra), T> = gax::$rtr::$rm($rb::slot(), $ra::slot());
                let (t, s): ($rb<($rb,), T>, $rb<($rb,), T>) = (fresh(), fresh());
                let (l, x): ($ra<(), T>, $rb<(), T>) = (fresh(), fresh());
                let name = concat!(stringify!($rm), " pairing of ", stringify!($ra), " and ", stringify!($rb));
                let adj_t: $ra<($ra,), T> = adjoint(&p, &t);
                law(gax::$rtr::$rm(adj_t.of(l), x) == gax::$rtr::$rm(l, t.of(x)), name);
                let adj_s: $ra<($ra,), T> = adjoint(&p, &s);
                let adj_ts: $ra<($ra,), T> = adjoint(&p, &t.of(s));
                law(adj_ts == adj_s.of(adj_t), name);
                let adj_id: $ra<($ra,), T> = adjoint(&p, &$rb::<(), T>::slot());
                law(adj_id == $ra::slot(), name);
                let back: $rb<($rb,), T> = adjoint(&q, &adj_t);
                law(back == t, name);

                // The solver agrees with the closed form (f64).
                let mut seed = 0x9e37_79b9_7f4a_7c15u64;
                let pf: $scalar<($ra, $rb), f64> = gax::$rtr::$rm($ra::slot(), $rb::slot());
                for _ in 0..4 {
                    let tf: $rb<($rb,), f64> = random_f64(&mut seed);
                    let solved: $ra<($ra,), f64> = pf.solve(gax::$rtr::$rm($ra::slot(), tf));
                    let closed: $ra<($ra,), f64> = adjoint(&pf, &tf);
                    law(close(&solved, &closed, 1e-12), name);
                }
            })();)*
        }

        /// I: the generated sandwich kernels (value path, map path, prepared) agree with the
        /// tier-1 products, exactly for plain versors and modulo `u ~u = 1` for units.
        #[test]
        #[allow(clippy::redundant_closure_call)] // each block is a closure call, to bound the stack frame
        fn tiers() {
            $((|| {
                reset();
                let v: $pv<(), T> = fresh();
                let x: $px<(), T> = fresh();
                let name = concat!(stringify!($pv), " >> ", stringify!($px));
                let y = v >> x;
                law(projects_to(&y, &((v * x) * v.reverse()), &[]), name);
                law((v >> $px::slot()).of(x) == y, name);
                let prepared = gax::Prepare::<$px>::prepare(v);
                law((prepared >> x) == y, name);
                let dense: $px<($px,), T> = prepared.into();
                law(dense == v >> $px::slot(), name);
            })();)*
            $((|| {
                reset();
                let v: $sv<(), T> = fresh();
                let x: $sx<(), T> = fresh();
                let basis = unit_basis(&(v * v.reverse()));
                let u = Unit::new_unchecked(v);
                let name = concat!("Unit<", stringify!($sv), "> >> ", stringify!($sx));
                let y = u >> x;
                law(projects_to(&y, &((v * x) * v.reverse()), &basis), name);
                law(same_mod(&(u >> $sx::slot()).of(x), &y, &basis), name);
                let prepared = u.prepare::<$sx>();
                law(same_mod(&(prepared >> x), &y, &basis), name);
                let dense: $sx<($sx,), T> = prepared.into();
                law(same_mod(&dense, &(u >> $sx::slot()), &basis), name);
            })();)*
        }
    };
}

pub(crate) use law_suite;
