//! Splitting an algebra's generated module into files of a readable size.
//!
//! The emitter marks the start of each section with a `// @part <name>` line (kinds and value
//! methods, each product, conversions, each versor's sandwiches, outermorphisms, layouts). The
//! regeneration tool writes `algebras/<name>.rs` as an index of `include!`s and the parts as
//! `algebras/<name>/<part>.rs`; a part over the size budget is cut into numbered pieces at
//! top-level item boundaries. The compiled module is the same either way: `include!` pastes the
//! parts back in order. (`algebra!` emits one token stream and never splits.)

use std::fmt::Write as _;

/// The marker the emitter writes before each part.
pub const MARKER: &str = "// @part ";

/// The index file and the parts `(file name, content)` of the module `code` of algebra `name`,
/// each part at most `budget` bytes where top-level items allow.
#[must_use]
pub fn split(name: &str, code: &str, budget: usize) -> (String, Vec<(String, String)>) {
    let mut sections: Vec<(String, String)> = Vec::new();
    let mut prelude = String::new();
    for line in code.split_inclusive('\n') {
        if let Some(part) = line.trim_end().strip_prefix(MARKER) {
            sections.push((part.to_string(), String::new()));
        } else if let Some((_, body)) = sections.last_mut() {
            body.push_str(line);
        } else {
            prelude.push_str(line);
        }
    }
    let mut files = Vec::new();
    for (part, body) in sections {
        let body = body.trim_matches('\n');
        if body.is_empty() {
            continue;
        }
        let pieces = cut(body, budget);
        let many = pieces.len() > 1;
        for (i, piece) in pieces.into_iter().enumerate() {
            let file = if many {
                format!("{part}_{}.rs", i + 1)
            } else {
                format!("{part}.rs")
            };
            let content = format!(
                "// @generated by gax-gen: part of `{name}` (see ../{name}.rs). Do not edit by hand.\n\n{piece}\n"
            );
            files.push((file, content));
        }
    }
    let mut index = prelude.trim_end_matches('\n').to_string();
    index.push_str("\n\n");
    for (file, _) in &files {
        let _ = writeln!(index, "include!(\"{name}/{file}\");");
    }
    (index, files)
}

/// `body` cut into pieces of at most `budget` bytes, at lines that start a top-level item: at
/// brace depth zero, after a blank line. An item larger than the budget is a piece of its own.
fn cut(body: &str, budget: usize) -> Vec<String> {
    let lines: Vec<&str> = body.split_inclusive('\n').collect();
    // The byte offsets where a piece may start.
    let mut starts = vec![0usize];
    let (mut depth, mut offset, mut prev_blank) = (0i64, 0usize, false);
    for line in &lines {
        if depth == 0 && prev_blank && offset > 0 && !line.starts_with(char::is_whitespace) {
            starts.push(offset);
        }
        depth += brace_delta(line);
        prev_blank = line.trim().is_empty();
        offset += line.len();
    }
    starts.push(body.len());
    let mut pieces = Vec::new();
    let mut begin = 0;
    for w in starts.windows(2) {
        // Close the current piece before an item that would take it over the budget.
        if w[1] - begin > budget && w[0] > begin {
            pieces.push(body[begin..w[0]].trim_matches('\n').to_string());
            begin = w[0];
        }
    }
    pieces.push(body[begin..].trim_matches('\n').to_string());
    pieces
}

/// Opening minus closing braces on a line, outside line comments and string literals.
fn brace_delta(line: &str) -> i64 {
    let code = line.trim_start();
    if code.starts_with("//") {
        return 0;
    }
    let (mut delta, mut in_str, mut escaped) = (0i64, false, false);
    let mut chars = code.chars().peekable();
    while let Some(c) = chars.next() {
        if in_str {
            match (escaped, c) {
                (true, _) => escaped = false,
                (false, '\\') => escaped = true,
                (false, '"') => in_str = false,
                _ => {}
            }
            continue;
        }
        match c {
            '"' => in_str = true,
            '/' if chars.peek() == Some(&'/') => break,
            '{' => delta += 1,
            '}' => delta -= 1,
            _ => {}
        }
    }
    delta
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parts_and_pieces() {
        let code = "// header\nuse crate as gx;\n\n// @part kinds\npub struct A;\n\nimpl A {\n    fn f() {\n\n        let x = \"}\";\n    }\n}\n\n// @part products_gp\n/// doc\nimpl B {}\n\nimpl C {}\n";
        let (index, files) = split("alg", code, 1 << 20);
        assert!(index.starts_with("// header\nuse crate as gx;\n\n"));
        assert!(index.contains("include!(\"alg/kinds.rs\");\ninclude!(\"alg/products_gp.rs\");"));
        assert_eq!(files.len(), 2);
        assert!(
            files[0]
                .1
                .contains("impl A {\n    fn f() {\n\n        let x = \"}\";\n    }\n}")
        );
        // A small budget cuts between items, never inside one, and keeps a doc with its item.
        let (_, files) = split("alg", code, 10);
        let names: Vec<&str> = files.iter().map(|f| f.0.as_str()).collect();
        assert_eq!(
            names,
            [
                "kinds_1.rs",
                "kinds_2.rs",
                "products_gp_1.rs",
                "products_gp_2.rs"
            ]
        );
        assert!(
            files[1]
                .1
                .contains("impl A {\n    fn f() {\n\n        let x = \"}\";\n    }\n}")
        );
        assert!(files[2].1.contains("/// doc\nimpl B {}"));
    }
}
