// @generated by gax-gen: part of `cga2d` (see ../cga2d.rs). Do not edit by hand.

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Scalar<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Scalar<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Scalar<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Scalar<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Vector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Vector<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(0, 0) + p(1, 1)) - (p(2, 3) + p(3, 2)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Vector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Vector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Vector<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(0, 0) + p(1, 1)) - (p(2, 3) + p(3, 2)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Vector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 8 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(0, 1) + p(1, 2)) - (p(2, 4) + p(3, 3)))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Twist<S1, T> {
    type Output = Twist<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Twist<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 3 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Twist {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Twist<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                ((p(0, 1) - p(1, 2))).0,
                (-(p(0, 0) + p(2, 2))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-(p(1, 0) + p(2, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Twist<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Twist<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 3 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(1, 1) + p(2, 2)) - p(0, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Twist<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (-p(0, 1)).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Twist<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (((p(1, 2) + p(2, 3)) - p(0, 1))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Twist<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                ((p(0, 1) - p(1, 2))).0,
                (-(p(0, 0) + p(2, 2))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-(p(1, 0) + p(2, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Twist<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(1, 6) + p(2, 7)) - p(0, 5))).0,
                ((p(0, 2) - p(1, 3))).0,
                (-(p(0, 1) + p(2, 3))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-(p(1, 1) + p(2, 2))).0,
                (p(0, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(1, 0)).0,
                (p(2, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Bivector<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Bivector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (((p(0, 1) - p(1, 3)) - p(3, 2))).0,
                (-((p(0, 0) + p(2, 3)) + p(4, 2))).0,
                (-((p(1, 0) + p(2, 1)) + p(5, 2))).0,
                (((p(5, 3) - p(3, 0)) - p(4, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Bivector<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 3 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(1, 1) + p(2, 2)) - p(0, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Bivector<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                ((((p(1, 3) + p(2, 4)) + p(3, 1)) + ((p(4, 2) + p(5, 5)) - p(0, 0)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Bivector<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 9 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (((p(1, 2) + p(2, 3)) - p(0, 1))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Bivector<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                ((((p(1, 4) + p(2, 5)) + p(3, 2)) + ((p(4, 3) + p(5, 6)) - p(0, 1)))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Bivector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (((p(0, 1) - p(1, 3)) - p(3, 2))).0,
                (-((p(0, 0) + p(2, 3)) + p(4, 2))).0,
                (-((p(1, 0) + p(2, 1)) + p(5, 2))).0,
                (((p(5, 3) - p(3, 0)) - p(4, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Bivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 24 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                ((((p(1, 8) + p(2, 9)) + p(3, 6)) + ((p(4, 7) + p(5, 10)) - p(0, 5)))).0,
                (((p(0, 2) - p(1, 4)) - p(3, 3))).0,
                (-((p(0, 1) + p(2, 4)) + p(4, 3))).0,
                (-((p(1, 1) + p(2, 2)) + p(5, 3))).0,
                (((p(5, 4) - p(3, 1)) - p(4, 2))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Trivector<S1, T> {
    type Output = Trivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Trivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Trivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Trivector<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                (-(p(0, 3) + p(1, 2))).0,
                (-(p(0, 1) + p(2, 2))).0,
                ((p(0, 0) - p(3, 2))).0,
                ((p(2, 3) - p(1, 1))).0,
                ((p(1, 0) + p(3, 3))).0,
                ((p(2, 0) + p(3, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Trivector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 2)).0,
                (-p(0, 1)).0,
                (-p(0, 0)).0,
                (((p(2, 1) + p(3, 2)) - p(1, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Trivector<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (((p(0, 4) + p(1, 2)) + p(2, 5))).0,
                (((p(3, 5) - p(0, 3)) - p(1, 1))).0,
                (-((p(0, 0) + p(2, 1)) + p(3, 2))).0,
                (((p(2, 3) + p(3, 4)) - p(1, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Trivector<S2, T>> for Trivector<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Trivector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(0, 1) + p(1, 0)) + (p(2, 2) + p(3, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Trivector<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 10 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 3)).0,
                (-p(0, 2)).0,
                (-p(0, 1)).0,
                (((p(2, 2) + p(3, 3)) - p(1, 1))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Trivector<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 16 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (((p(0, 5) + p(1, 3)) + p(2, 6))).0,
                (((p(3, 6) - p(0, 4)) - p(1, 2))).0,
                (-((p(0, 1) + p(2, 2)) + p(3, 3))).0,
                (((p(2, 4) + p(3, 5)) - p(1, 1))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Trivector<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 16 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (((p(0, 5) + p(1, 4)) + (p(2, 6) + p(3, 7)))).0,
                (-(p(0, 3) + p(1, 2))).0,
                (-(p(0, 1) + p(2, 2))).0,
                ((p(0, 0) - p(3, 2))).0,
                ((p(2, 3) - p(1, 1))).0,
                ((p(1, 0) + p(3, 3))).0,
                ((p(2, 0) + p(3, 1))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Trivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 32 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(0, 12) + p(1, 11)) + (p(2, 13) + p(3, 14)))).0,
                (((p(0, 9) + p(1, 7)) + p(2, 10))).0,
                (((p(3, 10) - p(0, 8)) - p(1, 6))).0,
                (-((p(0, 5) + p(2, 6)) + p(3, 7))).0,
                (((p(2, 8) + p(3, 9)) - p(1, 5))).0,
                (-(p(0, 4) + p(1, 3))).0,
                (-(p(0, 2) + p(2, 3))).0,
                ((p(0, 1) - p(3, 3))).0,
                ((p(2, 4) - p(1, 2))).0,
                ((p(1, 1) + p(3, 4))).0,
                ((p(2, 1) + p(3, 2))).0,
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Pseudoscalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Pseudoscalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Pseudoscalar {
            c: [
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Trivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Trivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Trivector {
            c: [
                (-p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 1)).0,
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 3 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 2)).0,
                (-p(0, 1)).0,
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Bivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Bivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Bivector {
            c: [
                (p(0, 5)).0,
                (-p(0, 2)).0,
                (p(0, 1)).0,
                (p(0, 4)).0,
                (-p(0, 3)).0,
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Trivector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Trivector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(0, 3)).0,
                (-p(0, 2)).0,
                (p(0, 0)).0,
                (-p(0, 1)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Pseudoscalar<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Pseudoscalar<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(0, 3)).0,
                (-p(0, 2)).0,
                (-p(0, 1)).0,
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 8 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (-p(0, 7)).0,
                (p(0, 6)).0,
                (-p(0, 3)).0,
                (p(0, 2)).0,
                (p(0, 5)).0,
                (-p(0, 4)).0,
                (-p(0, 1)).0,
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 8 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 7)).0,
                (-p(0, 6)).0,
                (p(0, 4)).0,
                (-p(0, 5)).0,
                (-p(0, 2)).0,
                (p(0, 3)).0,
                (p(0, 1)).0,
                (-p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Pseudoscalar<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 16 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (-p(0, 15)).0,
                (p(0, 14)).0,
                (-p(0, 13)).0,
                (p(0, 11)).0,
                (-p(0, 12)).0,
                (p(0, 10)).0,
                (-p(0, 7)).0,
                (p(0, 6)).0,
                (p(0, 9)).0,
                (-p(0, 8)).0,
                (-p(0, 5)).0,
                (-p(0, 3)).0,
                (p(0, 4)).0,
                (p(0, 2)).0,
                (-p(0, 1)).0,
                (p(0, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Motor<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Motor<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                ((p(1, 1) - p(2, 2))).0,
                (-(p(1, 0) + p(3, 2))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-(p(2, 0) + p(3, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Motor<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (-p(1, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Motor<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 3 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(2, 1) + p(3, 2)) - p(1, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Motor<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 5 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                ((p(0, 0) - p(1, 1))).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Motor<S1, T> {
    type Output = Motor<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Motor<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 7 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Motor {
            c: [
                (((p(0, 0) + p(2, 2)) + (p(3, 3) - p(1, 1)))).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Motor<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                ((p(1, 1) - p(2, 2))).0,
                (-(p(1, 0) + p(3, 2))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-(p(2, 0) + p(3, 1))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Motor<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 13 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(0, 0) + p(2, 6)) + (p(3, 7) - p(1, 5)))).0,
                ((p(1, 2) - p(2, 3))).0,
                (-(p(1, 1) + p(3, 3))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (-(p(2, 1) + p(3, 2))).0,
                (p(1, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(2, 0)).0,
                (p(3, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Even<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 8 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Even<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 16 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (((p(1, 1) - p(2, 3)) - p(4, 2))).0,
                (-((p(1, 0) + p(3, 3)) + p(5, 2))).0,
                (-((p(2, 0) + p(3, 1)) + p(6, 2))).0,
                (((p(6, 3) - p(4, 0)) - p(5, 1))).0,
                (-p(7, 2)).0,
                (p(7, 3)).0,
                (p(7, 1)).0,
                (-p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Even<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (((p(2, 1) + p(3, 2)) - p(1, 0))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(7, 2)).0,
                (-p(7, 1)).0,
                (-p(7, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Even<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                ((((p(2, 3) + p(3, 4)) + p(4, 1)) + ((p(5, 2) + p(6, 5)) - p(1, 0)))).0,
                (p(7, 5)).0,
                (-p(7, 2)).0,
                (p(7, 1)).0,
                (p(7, 4)).0,
                (-p(7, 3)).0,
                (-p(7, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Trivector<S2, T>> for Even<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Trivector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(7, 3)).0,
                (-p(7, 2)).0,
                (p(7, 0)).0,
                (-p(7, 1)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Pseudoscalar<S2, T>> for Even<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Pseudoscalar<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (-p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Even<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 14 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (((p(0, 0) + p(2, 2)) + (p(3, 3) - p(1, 1)))).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                ((p(4, 0) + p(7, 3))).0,
                ((p(5, 0) - p(7, 2))).0,
                ((p(6, 0) - p(7, 1))).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Even<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 21 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                ((((p(0, 0) + p(2, 4)) + (p(3, 5) + p(4, 2))) + ((p(5, 3) + p(6, 6)) - (p(1, 1) + p(7, 7))))).0,
                ((p(1, 0) + p(7, 6))).0,
                ((p(2, 0) - p(7, 3))).0,
                ((p(3, 0) + p(7, 2))).0,
                ((p(4, 0) + p(7, 5))).0,
                ((p(5, 0) - p(7, 4))).0,
                ((p(6, 0) - p(7, 1))).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Even<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 20 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (((p(1, 1) + p(7, 7)) - (p(2, 3) + p(4, 2)))).0,
                (-((p(1, 0) + p(3, 3)) + (p(5, 2) + p(7, 6)))).0,
                (((p(7, 4) - p(2, 0)) - (p(3, 1) + p(6, 2)))).0,
                (((p(6, 3) - p(4, 0)) - (p(5, 1) + p(7, 5)))).0,
                (-p(7, 2)).0,
                (p(7, 3)).0,
                (p(7, 1)).0,
                (-p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Even<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 41 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                ((((p(0, 0) + p(2, 8)) + (p(3, 9) + p(4, 6))) + ((p(5, 7) + p(6, 10)) - (p(1, 5) + p(7, 15))))).0,
                (((p(1, 2) + p(7, 14)) - (p(2, 4) + p(4, 3)))).0,
                (-((p(1, 1) + p(3, 4)) + (p(5, 3) + p(7, 13)))).0,
                (((p(7, 11) - p(2, 1)) - (p(3, 2) + p(6, 3)))).0,
                (((p(6, 4) - p(4, 1)) - (p(5, 2) + p(7, 12)))).0,
                ((p(1, 0) + p(7, 10))).0,
                ((p(2, 0) - p(7, 7))).0,
                ((p(3, 0) + p(7, 6))).0,
                ((p(4, 0) + p(7, 9))).0,
                ((p(5, 0) - p(7, 8))).0,
                ((p(6, 0) - p(7, 5))).0,
                (-p(7, 3)).0,
                (p(7, 4)).0,
                (p(7, 2)).0,
                (-p(7, 1)).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Odd<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 8 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Odd<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 16 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                (((p(0, 0) + p(1, 1)) - (p(2, 3) + p(3, 2)))).0,
                (-(p(4, 3) + p(5, 2))).0,
                (-(p(4, 1) + p(6, 2))).0,
                ((p(4, 0) - p(7, 2))).0,
                ((p(6, 3) - p(5, 1))).0,
                ((p(5, 0) + p(7, 3))).0,
                ((p(6, 0) + p(7, 1))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Odd<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 6 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (p(4, 2)).0,
                (-p(4, 1)).0,
                (-p(4, 0)).0,
                (((p(6, 1) + p(7, 2)) - p(5, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Odd<S1, T> {
    type Output = Vector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Vector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Vector {
            c: [
                (((p(4, 4) + p(5, 2)) + p(6, 5))).0,
                (((p(7, 5) - p(4, 3)) - p(5, 1))).0,
                (-((p(4, 0) + p(6, 1)) + p(7, 2))).0,
                (((p(6, 3) + p(7, 4)) - p(5, 0))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Trivector<S2, T>> for Odd<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Trivector<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 4 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (((p(4, 1) + p(5, 0)) + (p(6, 2) + p(7, 3)))).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Odd<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 14 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                ((p(0, 0) + p(4, 3))).0,
                ((p(1, 0) - p(4, 2))).0,
                ((p(2, 0) - p(4, 1))).0,
                (((p(3, 0) + p(6, 2)) + (p(7, 3) - p(5, 1)))).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Odd<S1, T> {
    type Output = Odd<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Odd<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 20 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Odd {
            c: [
                (((p(0, 0) + p(4, 5)) + (p(5, 3) + p(6, 6)))).0,
                (((p(1, 0) + p(7, 6)) - (p(4, 4) + p(5, 2)))).0,
                (((p(2, 0) - p(4, 1)) - (p(6, 2) + p(7, 3)))).0,
                (((p(3, 0) + p(6, 4)) + (p(7, 5) - p(5, 1)))).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Odd<S1, T> {
    type Output = Even<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Even<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 20 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Even {
            c: [
                ((((p(0, 0) + p(1, 1)) + (p(4, 5) + p(5, 4))) + ((p(6, 6) + p(7, 7)) - (p(2, 3) + p(3, 2))))).0,
                (-(p(4, 3) + p(5, 2))).0,
                (-(p(4, 1) + p(6, 2))).0,
                ((p(4, 0) - p(7, 2))).0,
                ((p(6, 3) - p(5, 1))).0,
                ((p(5, 0) + p(7, 3))).0,
                ((p(6, 0) + p(7, 1))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Odd<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 40 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                ((((p(0, 1) + p(1, 2)) + (p(4, 12) + p(5, 11))) + ((p(6, 13) + p(7, 14)) - (p(2, 4) + p(3, 3))))).0,
                (((p(0, 0) + p(4, 9)) + (p(5, 7) + p(6, 10)))).0,
                (((p(1, 0) + p(7, 10)) - (p(4, 8) + p(5, 6)))).0,
                (((p(2, 0) - p(4, 5)) - (p(6, 6) + p(7, 7)))).0,
                (((p(3, 0) + p(6, 8)) + (p(7, 9) - p(5, 5)))).0,
                (-(p(4, 4) + p(5, 3))).0,
                (-(p(4, 2) + p(6, 3))).0,
                ((p(4, 1) - p(7, 3))).0,
                ((p(6, 4) - p(5, 2))).0,
                ((p(5, 1) + p(7, 4))).0,
                ((p(6, 1) + p(7, 2))).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Scalar<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Scalar<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 16 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (p(0, 0)).0,
                (p(1, 0)).0,
                (p(2, 0)).0,
                (p(3, 0)).0,
                (p(4, 0)).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                (p(8, 0)).0,
                (p(9, 0)).0,
                (p(10, 0)).0,
                (p(11, 0)).0,
                (p(12, 0)).0,
                (p(13, 0)).0,
                (p(14, 0)).0,
                (p(15, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Vector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Vector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 32 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(1, 0) + p(2, 1)) - (p(3, 3) + p(4, 2)))).0,
                (((p(5, 1) - p(6, 3)) - p(8, 2))).0,
                (-((p(5, 0) + p(7, 3)) + p(9, 2))).0,
                (-((p(6, 0) + p(7, 1)) + p(10, 2))).0,
                (((p(10, 3) - p(8, 0)) - p(9, 1))).0,
                (-(p(11, 3) + p(12, 2))).0,
                (-(p(11, 1) + p(13, 2))).0,
                ((p(11, 0) - p(14, 2))).0,
                ((p(13, 3) - p(12, 1))).0,
                ((p(12, 0) + p(14, 3))).0,
                ((p(13, 0) + p(14, 1))).0,
                (-p(15, 2)).0,
                (p(15, 3)).0,
                (p(15, 1)).0,
                (-p(15, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Twist<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Twist<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 12 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(6, 1) + p(7, 2)) - p(5, 0))).0,
                (p(11, 2)).0,
                (-p(11, 1)).0,
                (-p(11, 0)).0,
                (((p(13, 1) + p(14, 2)) - p(12, 0))).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                (p(15, 2)).0,
                (-p(15, 1)).0,
                (-p(15, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Bivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Bivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 24 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                ((((p(6, 3) + p(7, 4)) + p(8, 1)) + ((p(9, 2) + p(10, 5)) - p(5, 0)))).0,
                (((p(11, 4) + p(12, 2)) + p(13, 5))).0,
                (((p(14, 5) - p(11, 3)) - p(12, 1))).0,
                (-((p(11, 0) + p(13, 1)) + p(14, 2))).0,
                (((p(13, 3) + p(14, 4)) - p(12, 0))).0,
                (p(15, 5)).0,
                (-p(15, 2)).0,
                (p(15, 1)).0,
                (p(15, 4)).0,
                (-p(15, 3)).0,
                (-p(15, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Trivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Trivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 8 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(11, 1) + p(12, 0)) + (p(13, 2) + p(14, 3)))).0,
                (p(15, 3)).0,
                (-p(15, 2)).0,
                (p(15, 0)).0,
                (-p(15, 1)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Pseudoscalar<S2, T>> for Multivector<S1, T> {
    type Output = Scalar<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Pseudoscalar<S2, T>) -> Scalar<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 1 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Scalar {
            c: [
                (-p(15, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Motor<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Motor<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 28 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((p(0, 0) + p(6, 2)) + (p(7, 3) - p(5, 1)))).0,
                ((p(1, 0) + p(11, 3))).0,
                ((p(2, 0) - p(11, 2))).0,
                ((p(3, 0) - p(11, 1))).0,
                (((p(4, 0) + p(13, 2)) + (p(14, 3) - p(12, 1)))).0,
                (p(5, 0)).0,
                (p(6, 0)).0,
                (p(7, 0)).0,
                ((p(8, 0) + p(15, 3))).0,
                ((p(9, 0) - p(15, 2))).0,
                ((p(10, 0) - p(15, 1))).0,
                (p(11, 0)).0,
                (p(12, 0)).0,
                (p(13, 0)).0,
                (p(14, 0)).0,
                (p(15, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Even<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Even<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 41 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                ((((p(0, 0) + p(6, 4)) + (p(7, 5) + p(8, 2))) + ((p(9, 3) + p(10, 6)) - (p(5, 1) + p(15, 7))))).0,
                (((p(1, 0) + p(11, 5)) + (p(12, 3) + p(13, 6)))).0,
                (((p(2, 0) + p(14, 6)) - (p(11, 4) + p(12, 2)))).0,
                (((p(3, 0) - p(11, 1)) - (p(13, 2) + p(14, 3)))).0,
                (((p(4, 0) + p(13, 4)) + (p(14, 5) - p(12, 1)))).0,
                ((p(5, 0) + p(15, 6))).0,
                ((p(6, 0) - p(15, 3))).0,
                ((p(7, 0) + p(15, 2))).0,
                ((p(8, 0) + p(15, 5))).0,
                ((p(9, 0) - p(15, 4))).0,
                ((p(10, 0) - p(15, 1))).0,
                (p(11, 0)).0,
                (p(12, 0)).0,
                (p(13, 0)).0,
                (p(14, 0)).0,
                (p(15, 0)).0,
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Odd<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Odd<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 40 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                ((((p(1, 0) + p(2, 1)) + (p(11, 5) + p(12, 4))) + ((p(13, 6) + p(14, 7)) - (p(3, 3) + p(4, 2))))).0,
                (((p(5, 1) + p(15, 7)) - (p(6, 3) + p(8, 2)))).0,
                (-((p(5, 0) + p(7, 3)) + (p(9, 2) + p(15, 6)))).0,
                (((p(15, 4) - p(6, 0)) - (p(7, 1) + p(10, 2)))).0,
                (((p(10, 3) - p(8, 0)) - (p(9, 1) + p(15, 5)))).0,
                (-(p(11, 3) + p(12, 2))).0,
                (-(p(11, 1) + p(13, 2))).0,
                ((p(11, 0) - p(14, 2))).0,
                ((p(13, 3) - p(12, 1))).0,
                ((p(12, 0) + p(14, 3))).0,
                ((p(13, 0) + p(14, 1))).0,
                (-p(15, 2)).0,
                (p(15, 3)).0,
                (p(15, 1)).0,
                (-p(15, 0)).0,
                <gx::Cat<S1, S2> as gx::Slots>::from_flat(&mut |_| T::zero(), 0),
            ],
        }
    }
}

impl<S1: gx::Slots, S2: gx::Slots, T: gx::Coef> gx::Rc<Multivector<S2, T>> for Multivector<S1, T> {
    type Output = Multivector<gx::Cat<S1, S2>, T>;
    #[inline(always)]
    fn rc(self, rhs: Multivector<S2, T>) -> Multivector<gx::Cat<S1, S2>, T> {
        if const { <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > 1 && 81 * <S1 as gx::Slots>::SIZE * <S2 as gx::Slots>::SIZE > gx::slots::SLOT_UNROLL_MAX } {
            return gx::slots::by_entries(&self, &rhs, |x, y| gx::Rc::rc(x, y));
        }
        let a = self.c.map(gx::SlotArr::<S1, T>);
        let b = rhs.c.map(gx::SlotArr::<S2, T>);
        let p = move |i: usize, j: usize| a[i] * b[j];
        Multivector {
            c: [
                (((((p(0, 0) + p(1, 1)) + (p(2, 2) + p(6, 8))) + ((p(7, 9) + p(8, 6)) + (p(9, 7) + p(10, 10)))) + (((p(11, 12) + p(12, 11)) + (p(13, 13) + p(14, 14))) - ((p(3, 4) + p(4, 3)) + (p(5, 5) + p(15, 15)))))).0,
                ((((p(1, 0) + p(5, 2)) + (p(11, 9) + p(12, 7))) + ((p(13, 10) + p(15, 14)) - (p(6, 4) + p(8, 3))))).0,
                ((((p(2, 0) + p(14, 10)) - (p(5, 1) + p(7, 4))) - ((p(9, 3) + p(11, 8)) + (p(12, 6) + p(15, 13))))).0,
                ((((p(3, 0) + p(15, 11)) - (p(6, 1) + p(7, 2))) - ((p(10, 3) + p(11, 5)) + (p(13, 6) + p(14, 7))))).0,
                ((((p(4, 0) + p(10, 4)) + (p(13, 8) + p(14, 9))) - ((p(8, 1) + p(9, 2)) + (p(12, 5) + p(15, 12))))).0,
                (((p(5, 0) + p(15, 10)) - (p(11, 4) + p(12, 3)))).0,
                (((p(6, 0) - p(11, 2)) - (p(13, 3) + p(15, 7)))).0,
                (((p(7, 0) + p(11, 1)) + (p(15, 6) - p(14, 3)))).0,
                (((p(8, 0) + p(13, 4)) + (p(15, 9) - p(12, 2)))).0,
                (((p(9, 0) + p(12, 1)) + (p(14, 4) - p(15, 8)))).0,
                (((p(10, 0) + p(13, 1)) + (p(14, 2) - p(15, 5)))).0,
                ((p(11, 0) - p(15, 3))).0,
                ((p(12, 0) + p(15, 4))).0,
                ((p(13, 0) + p(15, 2))).0,
                ((p(14, 0) - p(15, 1))).0,
                (p(15, 0)).0,
            ],
        }
    }
}
