// @generated by gax-regen from the `pga4d` spec. Do not edit by hand.
//! The algebraic laws of `pga4d`, proved exactly on symbolic coefficients
//! (docs/laws.md). The lists below are what the generator emitted for this algebra.

#![cfg(feature = "macros")]

mod law_suite;

gax::algebra! {
// A test-only algebra declared through `algebra!`, so that the law suite also covers macro
// output: plane-based PGA of 4D Euclidean space.
algebra pga4d "Plane-based PGA of 4D Euclidean space, R(4,0,1).";
basis e0 = 0, e1 = 1, e2 = 1, e3 = 1, e4 = 1;
kind Hyperplane = [e1, e2, e3, e4, e0];
kind Bivector = [e12, e13, e14, e23, e24, e34, e01, e02, e03, e04];
kind Point = [e0234, e0134, e0124, e0123, e1234];
versor Motor = [1, e12, e13, e14, e23, e24, e34, e01, e02, e03, e04,
    e1234, e0123, e0124, e0134, e0234];
}

use pga4d::*;

law_suite::law_suite! {
    scalar: Scalar,
    slot: Hyperplane,
    other: Point,
    products: [
        (Gp, gp, Scalar, Scalar),
        (Gp, gp, Scalar, Hyperplane),
        (Gp, gp, Scalar, Point),
        (Gp, gp, Hyperplane, Scalar),
        (Gp, gp, Point, Scalar),
        (Wedge, wedge, Scalar, Scalar),
        (Wedge, wedge, Scalar, Hyperplane),
        (Wedge, wedge, Scalar, Point),
        (Wedge, wedge, Hyperplane, Scalar),
        (Wedge, wedge, Point, Scalar),
        (Vee, vee, Hyperplane, Point),
        (Vee, vee, Point, Hyperplane),
        (Lc, lc, Scalar, Scalar),
        (Lc, lc, Scalar, Hyperplane),
        (Lc, lc, Scalar, Point),
        (Lc, lc, Hyperplane, Hyperplane),
        (Lc, lc, Point, Point),
        (Rc, rc, Scalar, Scalar),
        (Rc, rc, Hyperplane, Scalar),
        (Rc, rc, Hyperplane, Hyperplane),
        (Rc, rc, Point, Scalar),
        (Rc, rc, Point, Point),
        (Dot, dot, Scalar, Scalar),
        (Dot, dot, Scalar, Hyperplane),
        (Dot, dot, Scalar, Point),
        (Dot, dot, Hyperplane, Scalar),
        (Dot, dot, Hyperplane, Hyperplane),
        (Dot, dot, Point, Scalar),
        (Dot, dot, Point, Point),
        (ScalarProduct, scalar_product, Scalar, Scalar),
        (ScalarProduct, scalar_product, Hyperplane, Hyperplane),
        (ScalarProduct, scalar_product, Point, Point),
        (Anticommutator, anticommutator, Scalar, Scalar),
        (Anticommutator, anticommutator, Scalar, Hyperplane),
        (Anticommutator, anticommutator, Scalar, Point),
        (Anticommutator, anticommutator, Hyperplane, Scalar),
        (Anticommutator, anticommutator, Hyperplane, Hyperplane),
        (Anticommutator, anticommutator, Point, Scalar),
        (Anticommutator, anticommutator, Point, Point),
    ],
    unary: [
        (Reverse, reverse, Scalar),
        (Involute, involute, Scalar),
        (Conjugate, conjugate, Scalar),
        (Reverse, reverse, Hyperplane),
        (Involute, involute, Hyperplane),
        (Conjugate, conjugate, Hyperplane),
        (Dual, dual, Hyperplane),
        (Undual, undual, Hyperplane),
        (Reverse, reverse, Point),
        (Involute, involute, Point),
        (Conjugate, conjugate, Point),
        (Dual, dual, Point),
        (Undual, undual, Point),
    ],
    sandwiches: [
    ],
    plain_sandwiches: [
    ],
    actions: [
    ],
    equivariant: [
    ],
    unit_equivariant: [
    ],
    violations: [
    ],
    conjugations: [
    ],
    outer: [
        (Hyperplane, Point),
        (Point, Scalar),
        (Point, Hyperplane),
    ],
    top: [
        (Point, Scalar),
    ],
    unit_det: [
    ],
    pairings: [
        (Vee, vee, Hyperplane, Point),
        (Vee, vee, Point, Hyperplane),
    ],
}
