// @generated by gax-gen from the `sta` declaration. Do not edit by hand.
//! Every generated kernel of `sta`, checked against the dense oracle.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![cfg(feature = "sta")]
#![allow(clippy::pedantic, clippy::too_many_lines)]

mod common;
use common::{assert_close, random, Oracle, Rng};
use gax::{Extensor, Unit};
use gax_gen::table::{BinOp, UnOp};
use gax::sta::*;

const SPEC: &str = include_str!("../specs/sta.gax");

fn bin<A, B, R>(o: &Oracle, rng: &mut Rng, op: BinOp, f: impl Fn(A, B) -> R)
where
    A: Extensor<Slots = (), Coef = f64>,
    B: Extensor<Slots = (), Coef = f64>,
    R: Extensor<Slots = (), Coef = f64>,
{
    for _ in 0..8 {
        let (a, b): (A, B) = (random(rng), random(rng));
        let want = o.binop(op, &o.dense(&a), &o.dense(&b));
        assert_close(&o.dense(&f(a, b)), &want, &format!("{op:?} {} {}", std::any::type_name::<A>(), std::any::type_name::<B>()));
    }
}

fn un<A, R>(o: &Oracle, rng: &mut Rng, op: UnOp, f: impl Fn(A) -> R)
where
    A: Extensor<Slots = (), Coef = f64>,
    R: Extensor<Slots = (), Coef = f64>,
{
    for _ in 0..8 {
        let a: A = random(rng);
        assert_close(&o.dense(&f(a)), &o.unop(op, &o.dense(&a)), &format!("{op:?} {}", std::any::type_name::<A>()));
    }
}

/// `v x ~v` against the oracle; with `unit`, `v` is first normalized to `v ~v = 1`.
fn sandwich<V, X, R>(o: &Oracle, rng: &mut Rng, unit: bool, f: impl Fn(V, X) -> R, prepared: impl Fn(V, X) -> R)
where
    V: Extensor<Slots = (), Coef = f64>,
    X: Extensor<Slots = (), Coef = f64>,
    R: Extensor<Slots = (), Coef = f64>,
{
    let mut tested = 0;
    for _ in 0..16 {
        let (mut v, x): (V, X) = (random(rng), random(rng));
        if unit {
            let Some(u) = o.random_unit(rng) else { continue };
            v = u;
        }
        tested += 1;
        let (dv, dx) = (o.dense(&v), o.dense(&x));
        let want = o.binop(BinOp::Gp, &o.binop(BinOp::Gp, &dv, &dx), &o.unop(UnOp::Reverse, &dv));
        assert_close(&o.dense(&f(v, x)), &want, &format!("sandwich {} {}", std::any::type_name::<V>(), std::any::type_name::<X>()));
        assert_close(&o.dense(&prepared(v, x)), &want, &format!("prepared {} {}", std::any::type_name::<V>(), std::any::type_name::<X>()));
    }
    assert!(tested > 0, "no sample of {} could be normalized", std::any::type_name::<V>());
}

#[test]
fn gp() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(1);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Gp, |a, b| a.gp(b));
}

#[test]
fn wedge() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(2);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Bivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Bivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Trivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Pseudoscalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Wedge, |a, b| a.wedge(b));
}

#[test]
fn vee() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(3);
    bin::<Scalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Bivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Bivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Vee, |a, b| a.vee(b));
}

#[test]
fn lc() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(4);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Bivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Bivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Trivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Lc, |a, b| a.lc(b));
}

#[test]
fn rc() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(5);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Bivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Bivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Rc, |a, b| a.rc(b));
}

#[test]
fn dot() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(6);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Dot, |a, b| a.dot(b));
}

#[test]
fn scalar_product() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(7);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Scalar, |a, b| a.scalar_product(b));
}

#[test]
fn commutator() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(8);
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Bivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Bivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Pseudoscalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Pseudoscalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Pseudoscalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Commutator, |a, b| a.commutator(b));
}

#[test]
fn anticommutator() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(9);
    bin::<Scalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Scalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Bivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Trivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Pseudoscalar<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Pseudoscalar<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Pseudoscalar<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Pseudoscalar<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Pseudoscalar<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Even<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
    bin::<Multivector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, BinOp::Anticommutator, |a, b| a.anticommutator(b));
}

#[test]
fn reverse() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(20);
    un::<Scalar<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Vector<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Bivector<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Trivector<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Pseudoscalar<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Even<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Odd<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
    un::<Multivector<(), f64>, _>(&o, &mut rng, UnOp::Reverse, |a| a.reverse());
}

#[test]
fn involute() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(21);
    un::<Scalar<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Vector<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Bivector<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Trivector<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Pseudoscalar<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Even<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Odd<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
    un::<Multivector<(), f64>, _>(&o, &mut rng, UnOp::Involute, |a| a.involute());
}

#[test]
fn conjugate() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(22);
    un::<Scalar<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Vector<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Bivector<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Trivector<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Pseudoscalar<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Even<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Odd<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
    un::<Multivector<(), f64>, _>(&o, &mut rng, UnOp::Conjugate, |a| a.conjugate());
}

#[test]
fn dual() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(23);
    un::<Scalar<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Vector<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Bivector<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Trivector<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Pseudoscalar<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Even<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Odd<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
    un::<Multivector<(), f64>, _>(&o, &mut rng, UnOp::Dual, |a| a.dual());
}

#[test]
fn undual() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(24);
    un::<Scalar<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Vector<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Bivector<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Trivector<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Pseudoscalar<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Even<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Odd<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
    un::<Multivector<(), f64>, _>(&o, &mut rng, UnOp::Undual, |a| a.undual());
}

#[test]
fn value_methods() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(77);
    common::inverse::<Scalar<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Scalar<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
    common::inverse::<Vector<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Vector<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
    common::inverse::<Bivector<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Bivector<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
    common::exp_log::<Bivector<(), f64>, Even<(), f64>>(&o, &mut rng, |b| b.exp(), |r| r.log());
    common::inverse::<Trivector<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Trivector<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
    common::inverse::<Pseudoscalar<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Pseudoscalar<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
    common::inverse::<Even<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Even<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
    common::sqrt::<Even<(), f64>>(&o, &mut rng, |r| r.sqrt().into_inner(), |r| r.into_inner() * r.into_inner());
    common::inverse::<Odd<(), f64>, _>(&o, &mut rng, |x| x.inverse());
    common::normalized::<Odd<(), f64>>(&o, &mut rng, |x| x.normalized().into_inner());
}

#[test]
fn sandwiches() {
    let o = Oracle::from_spec(SPEC);
    let mut rng = Rng::new(99);
    sandwich::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Scalar>() >> x);
    sandwich::<Vector<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Scalar>() >> x);
    sandwich::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Vector>() >> x);
    sandwich::<Vector<(), f64>, Vector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Vector>() >> x);
    sandwich::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Bivector>() >> x);
    sandwich::<Vector<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Bivector>() >> x);
    sandwich::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Trivector>() >> x);
    sandwich::<Vector<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Trivector>() >> x);
    sandwich::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Pseudoscalar>() >> x);
    sandwich::<Vector<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Pseudoscalar>() >> x);
    sandwich::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Even>() >> x);
    sandwich::<Vector<(), f64>, Even<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Even>() >> x);
    sandwich::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Odd>() >> x);
    sandwich::<Vector<(), f64>, Odd<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Odd>() >> x);
    sandwich::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Multivector>() >> x);
    sandwich::<Vector<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Multivector>() >> x);
    sandwich::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Scalar>() >> x);
    sandwich::<Even<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Scalar>() >> x);
    sandwich::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Vector>() >> x);
    sandwich::<Even<(), f64>, Vector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Vector>() >> x);
    sandwich::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Bivector>() >> x);
    sandwich::<Even<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Bivector>() >> x);
    sandwich::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Trivector>() >> x);
    sandwich::<Even<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Trivector>() >> x);
    sandwich::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Pseudoscalar>() >> x);
    sandwich::<Even<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Pseudoscalar>() >> x);
    sandwich::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Even>() >> x);
    sandwich::<Even<(), f64>, Even<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Even>() >> x);
    sandwich::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Odd>() >> x);
    sandwich::<Even<(), f64>, Odd<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Odd>() >> x);
    sandwich::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Multivector>() >> x);
    sandwich::<Even<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Multivector>() >> x);
    sandwich::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Scalar>() >> x);
    sandwich::<Odd<(), f64>, Scalar<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Scalar>() >> x);
    sandwich::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Vector>() >> x);
    sandwich::<Odd<(), f64>, Vector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Vector>() >> x);
    sandwich::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Bivector>() >> x);
    sandwich::<Odd<(), f64>, Bivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Bivector>() >> x);
    sandwich::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Trivector>() >> x);
    sandwich::<Odd<(), f64>, Trivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Trivector>() >> x);
    sandwich::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Pseudoscalar>() >> x);
    sandwich::<Odd<(), f64>, Pseudoscalar<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Pseudoscalar>() >> x);
    sandwich::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Even>() >> x);
    sandwich::<Odd<(), f64>, Even<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Even>() >> x);
    sandwich::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Odd>() >> x);
    sandwich::<Odd<(), f64>, Odd<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Odd>() >> x);
    sandwich::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, false, |v, x| v >> x, |v, x| v.prepare::<Multivector>() >> x);
    sandwich::<Odd<(), f64>, Multivector<(), f64>, _>(&o, &mut rng, true, |v, x| Unit::new_unchecked(v) >> x, |v, x| Unit::new_unchecked(v).prepare::<Multivector>() >> x);
}
