enable f16;

// @generated by gax-regen from the `vga3d` spec. Do not edit by hand.
//
// gax WGSL module `gax::vga3d_f16` (plain WGSL, also valid WESL; see gax's docs/shaders.md).
//
// * Each kind is a struct of `ceil(N/4)` `vec4<f16>` fields `c0, c1, ...` holding its N
//   coefficients in the Rust blade order (listed per struct), zero-padded. The Rust side has
//   the same layout (`{Kind}Gpu`, feature `bytemuck`).
// * Function names: `motor_new`, `motor_from_rotor`, `motor_reverse`, `motor_mul_point`
//   (geometric product), `motor_sandwich_point` (`v x ~v`), `unit_motor_sandwich_point` (for
//   `v ~v = 1`), `motor_matrix_point` (the matrix of the sandwich, applied as `m * x`),
//   `motor_normalized`, `motor_renormalize_fast`, `line_exp`, `unit_motor_log`,
//   `motor_norm_squared`.
// * Everything is `f16` (the device needs `shader-f16`), except inside the Study helpers,
//   which compute in `f32`. Kernels are the Rust kernels' verified straight-line programs.

// `Scalar`: [1]
struct Scalar {
    c0: vec4<f16>,
}

// `Vector`: [e1, e2, e3]
struct Vector {
    c0: vec4<f16>,
}

// `Bivector`: [e23, e31, e12]
struct Bivector {
    c0: vec4<f16>,
}

// `Pseudoscalar`: [e123]
struct Pseudoscalar {
    c0: vec4<f16>,
}

// `Paravector`: [1, e1, e2, e3]
struct Paravector {
    c0: vec4<f16>,
}

// `Rotor`: [1, e23, e31, e12]
struct Rotor {
    c0: vec4<f16>,
}

// `Odd`: [e1, e2, e3, e123]
struct Odd {
    c0: vec4<f16>,
}

// `Multivector`: [1, e1, e2, e3, e23, e31, e12, e123]
struct Multivector {
    c0: vec4<f16>,
    c1: vec4<f16>,
}

alias Even = Rotor;

// A `Scalar` from its coefficients.
fn scalar_new(s: f16) -> Scalar {
    return Scalar(vec4<f16>(s, 0.0, 0.0, 0.0));
}

// A `Vector` from its coefficients.
fn vector_new(e1: f16, e2: f16, e3: f16) -> Vector {
    return Vector(vec4<f16>(e1, e2, e3, 0.0));
}

// A `Bivector` from its coefficients.
fn bivector_new(e23: f16, e31: f16, e12: f16) -> Bivector {
    return Bivector(vec4<f16>(e23, e31, e12, 0.0));
}

// A `Pseudoscalar` from its coefficients.
fn pseudoscalar_new(e123: f16) -> Pseudoscalar {
    return Pseudoscalar(vec4<f16>(e123, 0.0, 0.0, 0.0));
}

// A `Paravector` from its coefficients.
fn paravector_new(s: f16, e1: f16, e2: f16, e3: f16) -> Paravector {
    return Paravector(vec4<f16>(s, e1, e2, e3));
}

// A `Rotor` from its coefficients.
fn rotor_new(s: f16, e23: f16, e31: f16, e12: f16) -> Rotor {
    return Rotor(vec4<f16>(s, e23, e31, e12));
}

// A `Odd` from its coefficients.
fn odd_new(e1: f16, e2: f16, e3: f16, e123: f16) -> Odd {
    return Odd(vec4<f16>(e1, e2, e3, e123));
}

// A `Multivector` from its coefficients.
fn multivector_new(s: f16, e1: f16, e2: f16, e3: f16, e23: f16, e31: f16, e12: f16, e123: f16) -> Multivector {
    return Multivector(vec4<f16>(s, e1, e2, e3), vec4<f16>(e23, e31, e12, e123));
}

// A `Vector` as a `Odd`.
fn odd_from_vector(x: Vector) -> Odd {
    return Odd(vec4<f16>(x.c0.x, x.c0.y, x.c0.z, 0.0));
}

// The reverse `~x`.
fn scalar_reverse(x: Scalar) -> Scalar {
    return Scalar(vec4<f16>(x.c0.x, 0.0, 0.0, 0.0));
}

// The reverse `~x`.
fn vector_reverse(x: Vector) -> Vector {
    return Vector(vec4<f16>(x.c0.x, x.c0.y, x.c0.z, 0.0));
}

// The reverse `~x`.
fn bivector_reverse(x: Bivector) -> Bivector {
    let t0 = -x.c0.x;
    let t1 = -x.c0.y;
    let t2 = -x.c0.z;
    return Bivector(vec4<f16>(t0, t1, t2, 0.0));
}

// The reverse `~x`.
fn pseudoscalar_reverse(x: Pseudoscalar) -> Pseudoscalar {
    let t0 = -x.c0.x;
    return Pseudoscalar(vec4<f16>(t0, 0.0, 0.0, 0.0));
}

// The reverse `~x`.
fn paravector_reverse(x: Paravector) -> Paravector {
    return Paravector(vec4<f16>(x.c0.x, x.c0.y, x.c0.z, x.c0.w));
}

// The reverse `~x`.
fn rotor_reverse(x: Rotor) -> Rotor {
    let t0 = -x.c0.y;
    let t1 = -x.c0.z;
    let t2 = -x.c0.w;
    return Rotor(vec4<f16>(x.c0.x, t0, t1, t2));
}

// The reverse `~x`.
fn odd_reverse(x: Odd) -> Odd {
    let t0 = -x.c0.w;
    return Odd(vec4<f16>(x.c0.x, x.c0.y, x.c0.z, t0));
}

// The reverse `~x`.
fn multivector_reverse(x: Multivector) -> Multivector {
    let t0 = -x.c1.x;
    let t1 = -x.c1.y;
    let t2 = -x.c1.z;
    let t3 = -x.c1.w;
    return Multivector(vec4<f16>(x.c0.x, x.c0.y, x.c0.z, x.c0.w), vec4<f16>(t0, t1, t2, t3));
}

// The geometric product of a `Vector` and a `Vector` (composition).
fn vector_mul_vector(a: Vector, b: Vector) -> Rotor {
    let t1 = a.c0.y * b.c0.y;
    let t3 = a.c0.y * b.c0.z;
    let t6 = a.c0.z * b.c0.x;
    let t7 = a.c0.x * b.c0.y;
    let t9 = fma(a.c0.x, b.c0.x, t1);
    let t10 = fma(a.c0.z, b.c0.z, t9);
    let t11 = fma(-a.c0.z, b.c0.y, t3);
    let t12 = fma(-a.c0.x, b.c0.z, t6);
    let t13 = fma(-a.c0.y, b.c0.x, t7);
    return Rotor(vec4<f16>(t10, t11, t12, t13));
}

// The geometric product of a `Vector` and a `Rotor` (composition).
fn vector_mul_rotor(a: Vector, b: Rotor) -> Odd {
    let t2 = a.c0.z * b.c0.z;
    let t4 = a.c0.y * b.c0.x;
    let t8 = a.c0.z * b.c0.x;
    let t10 = a.c0.y * b.c0.z;
    let t12 = fma(a.c0.x, b.c0.x, t2);
    let t13 = fma(-a.c0.y, b.c0.w, t12);
    let t14 = fma(a.c0.x, b.c0.w, t4);
    let t15 = fma(-a.c0.z, b.c0.y, t14);
    let t16 = fma(a.c0.y, b.c0.y, t8);
    let t17 = fma(-a.c0.x, b.c0.z, t16);
    let t18 = fma(a.c0.x, b.c0.y, t10);
    let t19 = fma(a.c0.z, b.c0.w, t18);
    return Odd(vec4<f16>(t13, t15, t17, t19));
}

// The geometric product of a `Vector` and a `Odd` (composition).
fn vector_mul_odd(a: Vector, b: Odd) -> Rotor {
    let t1 = a.c0.y * b.c0.y;
    let t4 = a.c0.y * b.c0.z;
    let t8 = a.c0.z * b.c0.x;
    let t11 = a.c0.z * b.c0.w;
    let t12 = fma(a.c0.x, b.c0.x, t1);
    let t13 = fma(a.c0.z, b.c0.z, t12);
    let t14 = fma(a.c0.x, b.c0.w, t4);
    let t15 = fma(-a.c0.z, b.c0.y, t14);
    let t16 = fma(a.c0.y, b.c0.w, t8);
    let t17 = fma(-a.c0.x, b.c0.z, t16);
    let t18 = fma(a.c0.x, b.c0.y, t11);
    let t19 = fma(-a.c0.y, b.c0.x, t18);
    return Rotor(vec4<f16>(t13, t15, t17, t19));
}

// The geometric product of a `Rotor` and a `Vector` (composition).
fn rotor_mul_vector(a: Rotor, b: Vector) -> Odd {
    let t2 = a.c0.w * b.c0.y;
    let t4 = a.c0.y * b.c0.z;
    let t8 = a.c0.z * b.c0.x;
    let t10 = a.c0.z * b.c0.y;
    let t12 = fma(a.c0.x, b.c0.x, t2);
    let t13 = fma(-a.c0.z, b.c0.z, t12);
    let t14 = fma(a.c0.x, b.c0.y, t4);
    let t15 = fma(-a.c0.w, b.c0.x, t14);
    let t16 = fma(a.c0.x, b.c0.z, t8);
    let t17 = fma(-a.c0.y, b.c0.y, t16);
    let t18 = fma(a.c0.y, b.c0.x, t10);
    let t19 = fma(a.c0.w, b.c0.z, t18);
    return Odd(vec4<f16>(t13, t15, t17, t19));
}

// The geometric product of a `Rotor` and a `Rotor` (composition).
fn rotor_mul_rotor(a: Rotor, b: Rotor) -> Rotor {
    let t0 = a.c0.x * b.c0.x;
    let t3 = a.c0.w * b.c0.w;
    let t5 = a.c0.y * b.c0.x;
    let t7 = a.c0.w * b.c0.z;
    let t9 = a.c0.y * b.c0.w;
    let t10 = a.c0.z * b.c0.x;
    let t14 = a.c0.z * b.c0.y;
    let t15 = a.c0.w * b.c0.x;
    let t16 = fma(-a.c0.y, b.c0.y, t0);
    let t17 = fma(a.c0.z, b.c0.z, t3);
    let t18 = t16 - t17;
    let t19 = fma(a.c0.x, b.c0.y, t5);
    let t20 = fma(-a.c0.z, b.c0.w, t7);
    let t21 = t19 + t20;
    let t22 = fma(a.c0.x, b.c0.z, t9);
    let t23 = fma(-a.c0.w, b.c0.y, t10);
    let t24 = t22 + t23;
    let t25 = fma(a.c0.x, b.c0.w, t14);
    let t26 = fma(-a.c0.y, b.c0.z, t15);
    let t27 = t25 + t26;
    return Rotor(vec4<f16>(t18, t21, t24, t27));
}

// The geometric product of a `Rotor` and a `Odd` (composition).
fn rotor_mul_odd(a: Rotor, b: Odd) -> Odd {
    let t2 = a.c0.z * b.c0.z;
    let t3 = a.c0.w * b.c0.y;
    let t5 = a.c0.y * b.c0.z;
    let t7 = a.c0.w * b.c0.x;
    let t10 = a.c0.z * b.c0.x;
    let t11 = a.c0.w * b.c0.w;
    let t13 = a.c0.y * b.c0.x;
    let t15 = a.c0.w * b.c0.z;
    let t16 = fma(a.c0.x, b.c0.x, t3);
    let t17 = fma(a.c0.y, b.c0.w, t2);
    let t18 = t16 - t17;
    let t19 = fma(a.c0.x, b.c0.y, t5);
    let t20 = fma(a.c0.z, b.c0.w, t7);
    let t21 = t19 - t20;
    let t22 = fma(a.c0.x, b.c0.z, t10);
    let t23 = fma(a.c0.y, b.c0.y, t11);
    let t24 = t22 - t23;
    let t25 = fma(a.c0.x, b.c0.w, t13);
    let t26 = fma(a.c0.z, b.c0.y, t15);
    let t27 = t25 + t26;
    return Odd(vec4<f16>(t18, t21, t24, t27));
}

// The geometric product of a `Odd` and a `Vector` (composition).
fn odd_mul_vector(a: Odd, b: Vector) -> Rotor {
    let t1 = a.c0.y * b.c0.y;
    let t5 = a.c0.w * b.c0.x;
    let t8 = a.c0.w * b.c0.y;
    let t11 = a.c0.w * b.c0.z;
    let t12 = fma(a.c0.x, b.c0.x, t1);
    let t13 = fma(a.c0.z, b.c0.z, t12);
    let t14 = fma(a.c0.y, b.c0.z, t5);
    let t15 = fma(-a.c0.z, b.c0.y, t14);
    let t16 = fma(a.c0.z, b.c0.x, t8);
    let t17 = fma(-a.c0.x, b.c0.z, t16);
    let t18 = fma(a.c0.x, b.c0.y, t11);
    let t19 = fma(-a.c0.y, b.c0.x, t18);
    return Rotor(vec4<f16>(t13, t15, t17, t19));
}

// The geometric product of a `Odd` and a `Rotor` (composition).
fn odd_mul_rotor(a: Odd, b: Rotor) -> Odd {
    let t2 = a.c0.z * b.c0.z;
    let t3 = a.c0.w * b.c0.y;
    let t5 = a.c0.y * b.c0.x;
    let t7 = a.c0.w * b.c0.z;
    let t10 = a.c0.z * b.c0.x;
    let t11 = a.c0.w * b.c0.w;
    let t13 = a.c0.y * b.c0.z;
    let t15 = a.c0.w * b.c0.x;
    let t16 = fma(a.c0.x, b.c0.x, t2);
    let t17 = fma(a.c0.y, b.c0.w, t3);
    let t18 = t16 - t17;
    let t19 = fma(a.c0.x, b.c0.w, t5);
    let t20 = fma(a.c0.z, b.c0.y, t7);
    let t21 = t19 - t20;
    let t22 = fma(a.c0.y, b.c0.y, t10);
    let t23 = fma(a.c0.x, b.c0.z, t11);
    let t24 = t22 - t23;
    let t25 = fma(a.c0.x, b.c0.y, t13);
    let t26 = fma(a.c0.z, b.c0.w, t15);
    let t27 = t25 + t26;
    return Odd(vec4<f16>(t18, t21, t24, t27));
}

// The geometric product of a `Odd` and a `Odd` (composition).
fn odd_mul_odd(a: Odd, b: Odd) -> Rotor {
    let t1 = a.c0.y * b.c0.y;
    let t2 = a.c0.z * b.c0.z;
    let t5 = a.c0.y * b.c0.z;
    let t7 = a.c0.w * b.c0.x;
    let t10 = a.c0.z * b.c0.x;
    let t11 = a.c0.w * b.c0.y;
    let t14 = a.c0.z * b.c0.w;
    let t15 = a.c0.w * b.c0.z;
    let t16 = fma(a.c0.x, b.c0.x, t1);
    let t17 = fma(-a.c0.w, b.c0.w, t2);
    let t18 = t16 + t17;
    let t19 = fma(a.c0.x, b.c0.w, t5);
    let t20 = fma(-a.c0.z, b.c0.y, t7);
    let t21 = t19 + t20;
    let t22 = fma(a.c0.y, b.c0.w, t10);
    let t23 = fma(-a.c0.x, b.c0.z, t11);
    let t24 = t22 + t23;
    let t25 = fma(a.c0.x, b.c0.y, t14);
    let t26 = fma(-a.c0.y, b.c0.x, t15);
    let t27 = t25 + t26;
    return Rotor(vec4<f16>(t18, t21, t24, t27));
}

// The squared norm: the scalar part of `x ~x`.
fn scalar_norm_squared(x: Scalar) -> f16 {
    let t0 = x.c0.x * x.c0.x;
    return t0;
}

// Scaled to a unit versor, `(x ~x)^(-1/2) x`, so that `x ~x = 1`.
fn scalar_normalized(x: Scalar) -> Scalar {
    let p0 = f32(x.c0.x) * f32(x.c0.x);
    let s0 = f16(study_rsqrt_abs(p0));
    let t0 = x.c0.x * s0;
    return Scalar(vec4<f16>(t0, 0.0, 0.0, 0.0));
}

// One Newton step towards `x ~x = 1`, `(3 - x ~x) x / 2`, without a square root.
fn scalar_renormalize_fast(x: Scalar) -> Scalar {
    let t0 = x.c0.x * x.c0.x;
    let t1 = x.c0.x * t0;
    let t3 = x.c0.x * (3.0 / 2.0);
    let t4 = fma(-t1, (1.0 / 2.0), t3);
    return Scalar(vec4<f16>(t4, 0.0, 0.0, 0.0));
}

// The squared norm: the scalar part of `x ~x`.
fn vector_norm_squared(x: Vector) -> f16 {
    let t1 = x.c0.y * x.c0.y;
    let t3 = fma(x.c0.x, x.c0.x, t1);
    let t4 = fma(x.c0.z, x.c0.z, t3);
    return t4;
}

// Scaled to a unit versor, `(x ~x)^(-1/2) x`, so that `x ~x = 1`.
fn vector_normalized(x: Vector) -> Vector {
    let p1 = f32(x.c0.y) * f32(x.c0.y);
    let p3 = fma(f32(x.c0.x), f32(x.c0.x), p1);
    let p4 = fma(f32(x.c0.z), f32(x.c0.z), p3);
    let s0 = f16(study_rsqrt_abs(p4));
    let t0 = x.c0.x * s0;
    let t1 = x.c0.y * s0;
    let t2 = x.c0.z * s0;
    return Vector(vec4<f16>(t0, t1, t2, 0.0));
}

// One Newton step towards `x ~x = 1`, `(3 - x ~x) x / 2`, without a square root.
fn vector_renormalize_fast(x: Vector) -> Vector {
    let t1 = x.c0.y * x.c0.y;
    let t3 = fma(x.c0.x, x.c0.x, t1);
    let t4 = fma(x.c0.z, x.c0.z, t3);
    let t6 = fma(-t4, (1.0 / 3.0), 1.0);
    let t7 = x.c0.x * t6;
    let t8 = x.c0.y * t6;
    let t9 = x.c0.z * t6;
    let t10 = t7 * (3.0 / 2.0);
    let t11 = t8 * (3.0 / 2.0);
    let t12 = t9 * (3.0 / 2.0);
    return Vector(vec4<f16>(t10, t11, t12, 0.0));
}

// The squared norm: the scalar part of `x ~x`.
fn bivector_norm_squared(x: Bivector) -> f16 {
    let t1 = x.c0.y * x.c0.y;
    let t3 = fma(x.c0.x, x.c0.x, t1);
    let t4 = fma(x.c0.z, x.c0.z, t3);
    return t4;
}

// Scaled to a unit versor, `(x ~x)^(-1/2) x`, so that `x ~x = 1`.
fn bivector_normalized(x: Bivector) -> Bivector {
    let p1 = f32(x.c0.y) * f32(x.c0.y);
    let p3 = fma(f32(x.c0.x), f32(x.c0.x), p1);
    let p4 = fma(f32(x.c0.z), f32(x.c0.z), p3);
    let s0 = f16(study_rsqrt_abs(p4));
    let t0 = x.c0.x * s0;
    let t1 = x.c0.y * s0;
    let t2 = x.c0.z * s0;
    return Bivector(vec4<f16>(t0, t1, t2, 0.0));
}

// One Newton step towards `x ~x = 1`, `(3 - x ~x) x / 2`, without a square root.
fn bivector_renormalize_fast(x: Bivector) -> Bivector {
    let t1 = x.c0.y * x.c0.y;
    let t3 = fma(x.c0.x, x.c0.x, t1);
    let t4 = fma(x.c0.z, x.c0.z, t3);
    let t6 = fma(-t4, (1.0 / 3.0), 1.0);
    let t7 = x.c0.x * t6;
    let t8 = x.c0.y * t6;
    let t9 = x.c0.z * t6;
    let t10 = t7 * (3.0 / 2.0);
    let t11 = t8 * (3.0 / 2.0);
    let t12 = t9 * (3.0 / 2.0);
    return Bivector(vec4<f16>(t10, t11, t12, 0.0));
}

// The exponential, a unit `Rotor`: `exp(B) = C(B²) + S(B²) B`.
fn bivector_exp(x: Bivector) -> Rotor {
    let p1 = f32(x.c0.y) * f32(x.c0.y);
    let p3 = fma(f32(x.c0.x), f32(x.c0.x), p1);
    let p4 = fma(f32(x.c0.z), f32(x.c0.z), p3);
    let p5 = -p4;
    let r1 = study_exp_rotation(p5, 0.0);
    let c0 = f16(r1[0]);
    let c1 = f16(r1[1]);
    let s0 = f16(r1[2]);
    let s1 = f16(r1[3]);
    let t0 = x.c0.x * s0;
    let t1 = x.c0.y * s0;
    let t2 = x.c0.z * s0;
    return Rotor(vec4<f16>(c0, t0, t1, t2));
}

// The squared norm: the scalar part of `x ~x`.
fn pseudoscalar_norm_squared(x: Pseudoscalar) -> f16 {
    let t0 = x.c0.x * x.c0.x;
    return t0;
}

// Scaled to a unit versor, `(x ~x)^(-1/2) x`, so that `x ~x = 1`.
fn pseudoscalar_normalized(x: Pseudoscalar) -> Pseudoscalar {
    let p0 = f32(x.c0.x) * f32(x.c0.x);
    let s0 = f16(study_rsqrt_abs(p0));
    let t0 = x.c0.x * s0;
    return Pseudoscalar(vec4<f16>(t0, 0.0, 0.0, 0.0));
}

// One Newton step towards `x ~x = 1`, `(3 - x ~x) x / 2`, without a square root.
fn pseudoscalar_renormalize_fast(x: Pseudoscalar) -> Pseudoscalar {
    let t0 = x.c0.x * x.c0.x;
    let t1 = x.c0.x * t0;
    let t3 = x.c0.x * (3.0 / 2.0);
    let t4 = fma(-t1, (1.0 / 2.0), t3);
    return Pseudoscalar(vec4<f16>(t4, 0.0, 0.0, 0.0));
}

// The squared norm: the scalar part of `x ~x`.
fn paravector_norm_squared(x: Paravector) -> f16 {
    let t1 = x.c0.y * x.c0.y;
    let t3 = x.c0.w * x.c0.w;
    let t4 = fma(x.c0.x, x.c0.x, t1);
    let t5 = fma(x.c0.z, x.c0.z, t3);
    let t6 = t4 + t5;
    return t6;
}

// The squared norm: the scalar part of `x ~x`.
fn rotor_norm_squared(x: Rotor) -> f16 {
    let t1 = x.c0.y * x.c0.y;
    let t3 = x.c0.w * x.c0.w;
    let t4 = fma(x.c0.x, x.c0.x, t1);
    let t5 = fma(x.c0.z, x.c0.z, t3);
    let t6 = t4 + t5;
    return t6;
}

// Scaled to a unit versor, `(x ~x)^(-1/2) x`, so that `x ~x = 1`.
fn rotor_normalized(x: Rotor) -> Rotor {
    let p1 = f32(x.c0.y) * f32(x.c0.y);
    let p3 = f32(x.c0.w) * f32(x.c0.w);
    let p4 = fma(f32(x.c0.x), f32(x.c0.x), p1);
    let p5 = fma(f32(x.c0.z), f32(x.c0.z), p3);
    let p6 = p4 + p5;
    let s0 = f16(study_rsqrt_abs(p6));
    let t0 = x.c0.x * s0;
    let t1 = x.c0.y * s0;
    let t2 = x.c0.z * s0;
    let t3 = x.c0.w * s0;
    return Rotor(vec4<f16>(t0, t1, t2, t3));
}

// One Newton step towards `x ~x = 1`, `(3 - x ~x) x / 2`, without a square root.
fn rotor_renormalize_fast(x: Rotor) -> Rotor {
    let t1 = x.c0.y * x.c0.y;
    let t3 = x.c0.w * x.c0.w;
    let t4 = fma(x.c0.x, x.c0.x, t1);
    let t5 = fma(x.c0.z, x.c0.z, t3);
    let t6 = t4 + t5;
    let t8 = fma(-t6, (1.0 / 3.0), 1.0);
    let t9 = x.c0.x * t8;
    let t10 = x.c0.y * t8;
    let t11 = x.c0.z * t8;
    let t12 = x.c0.w * t8;
    let t13 = t9 * (3.0 / 2.0);
    let t14 = t10 * (3.0 / 2.0);
    let t15 = t11 * (3.0 / 2.0);
    let t16 = t12 * (3.0 / 2.0);
    return Rotor(vec4<f16>(t13, t14, t15, t16));
}

// The logarithm of a unit `Rotor`: the `Bivector` B with `exp(B) = x` (rotation half-angle in [0, pi]).
fn unit_rotor_log(x: Rotor) -> Bivector {
    let p1 = f32(x.c0.z) * f32(x.c0.z);
    let p3 = fma(f32(x.c0.y), f32(x.c0.y), p1);
    let p4 = fma(f32(x.c0.w), f32(x.c0.w), p3);
    let p5 = -p4;
    let r1 = study_log_rotation(f32(x.c0.x), 0.0, p5, 0.0);
    let h0 = f16(r1[0]);
    let h1 = f16(r1[1]);
    let t0 = x.c0.y * h0;
    let t1 = x.c0.z * h0;
    let t2 = x.c0.w * h0;
    return Bivector(vec4<f16>(t0, t1, t2, 0.0));
}

// The squared norm: the scalar part of `x ~x`.
fn odd_norm_squared(x: Odd) -> f16 {
    let t1 = x.c0.y * x.c0.y;
    let t3 = x.c0.w * x.c0.w;
    let t4 = fma(x.c0.x, x.c0.x, t1);
    let t5 = fma(x.c0.z, x.c0.z, t3);
    let t6 = t4 + t5;
    return t6;
}

// Scaled to a unit versor, `(x ~x)^(-1/2) x`, so that `x ~x = 1`.
fn odd_normalized(x: Odd) -> Odd {
    let p1 = f32(x.c0.y) * f32(x.c0.y);
    let p3 = f32(x.c0.w) * f32(x.c0.w);
    let p4 = fma(f32(x.c0.x), f32(x.c0.x), p1);
    let p5 = fma(f32(x.c0.z), f32(x.c0.z), p3);
    let p6 = p4 + p5;
    let s0 = f16(study_rsqrt_abs(p6));
    let t0 = x.c0.x * s0;
    let t1 = x.c0.y * s0;
    let t2 = x.c0.z * s0;
    let t3 = x.c0.w * s0;
    return Odd(vec4<f16>(t0, t1, t2, t3));
}

// One Newton step towards `x ~x = 1`, `(3 - x ~x) x / 2`, without a square root.
fn odd_renormalize_fast(x: Odd) -> Odd {
    let t1 = x.c0.y * x.c0.y;
    let t3 = x.c0.w * x.c0.w;
    let t4 = fma(x.c0.x, x.c0.x, t1);
    let t5 = fma(x.c0.z, x.c0.z, t3);
    let t6 = t4 + t5;
    let t8 = fma(-t6, (1.0 / 3.0), 1.0);
    let t9 = x.c0.x * t8;
    let t10 = x.c0.y * t8;
    let t11 = x.c0.z * t8;
    let t12 = x.c0.w * t8;
    let t13 = t9 * (3.0 / 2.0);
    let t14 = t10 * (3.0 / 2.0);
    let t15 = t11 * (3.0 / 2.0);
    let t16 = t12 * (3.0 / 2.0);
    return Odd(vec4<f16>(t13, t14, t15, t16));
}

// The squared norm: the scalar part of `x ~x`.
fn multivector_norm_squared(x: Multivector) -> f16 {
    let t1 = x.c0.y * x.c0.y;
    let t3 = x.c0.w * x.c0.w;
    let t5 = x.c1.y * x.c1.y;
    let t7 = x.c1.w * x.c1.w;
    let t8 = fma(x.c0.x, x.c0.x, t1);
    let t9 = fma(x.c0.z, x.c0.z, t3);
    let t10 = t8 + t9;
    let t11 = fma(x.c1.x, x.c1.x, t5);
    let t12 = fma(x.c1.z, x.c1.z, t7);
    let t13 = t11 + t12;
    let t14 = t10 + t13;
    return t14;
}

// `v x ~v` for `Vector` v and `Scalar` x (`v >> x`).
fn vector_sandwich_scalar(v: Vector, x: Scalar) -> Scalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = fma(v.c0.x, v.c0.x, t1);
    let t4 = fma(v.c0.z, v.c0.z, t3);
    let t5 = x.c0.x * t4;
    return Scalar(vec4<f16>(t5, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Vector` v and `Scalar` x (`v >> x`).
fn unit_vector_sandwich_scalar(v: Vector, x: Scalar) -> Scalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = fma(v.c0.x, v.c0.x, t1);
    let t4 = fma(v.c0.z, v.c0.z, t3);
    let t5 = x.c0.x * t4;
    return Scalar(vec4<f16>(t5, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Vector` v and `Vector` x (`v >> x`).
fn vector_sandwich_vector(v: Vector, x: Vector) -> Vector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.x * v.c0.y;
    let t4 = v.c0.x * v.c0.z;
    let t5 = v.c0.y * v.c0.z;
    let t6 = t0 - t1;
    let t7 = t6 - t2;
    let t8 = t2 + t6;
    let t9 = t0 + t1;
    let t10 = t9 - t2;
    let t13 = x.c0.z * t4;
    let t16 = x.c0.z * t5;
    let t18 = x.c0.y * t5;
    let t20 = fma(x.c0.y, t3, t13);
    let t21 = t20 * 2.0;
    let t22 = fma(x.c0.x, t7, t21);
    let t23 = fma(x.c0.x, t3, t16);
    let t24 = t23 * 2.0;
    let t25 = fma(-x.c0.y, t8, t24);
    let t26 = fma(x.c0.x, t4, t18);
    let t27 = t26 * 2.0;
    let t28 = fma(-x.c0.z, t10, t27);
    return Vector(vec4<f16>(t22, t25, t28, 0.0));
}

// The matrix of `x -> v x ~v` on `Vector` for `Vector` v (`v >> Vector::slot()`); apply it as `m * x`.
fn vector_matrix_vector(v: Vector) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m6 - m2;
    let m8 = m3 * 2.0;
    let m9 = m4 * 2.0;
    let m10 = m2 + m6;
    let m11 = -m10;
    let m12 = m5 * 2.0;
    let m13 = m2 - m0;
    let m14 = m13 - m1;
    return mat3x3<f16>(vec3<f16>(m7, m8, m9), vec3<f16>(m8, m11, m12), vec3<f16>(m9, m12, m14));
}

// `v x ~v` for a unit `Vector` v and `Vector` x (`v >> x`).
fn unit_vector_sandwich_vector(v: Vector, x: Vector) -> Vector {
    let t1 = v.c0.y * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t1);
    let t4 = fma(v.c0.z, x.c0.z, t3);
    let t5 = v.c0.x * t4;
    let t6 = v.c0.y * t4;
    let t7 = v.c0.z * t4;
    let t8 = t5 * 2.0;
    let t10 = v.c0.y * v.c0.y;
    let t12 = fma(v.c0.x, v.c0.x, t10);
    let t13 = fma(v.c0.z, v.c0.z, t12);
    let t15 = fma(-x.c0.x, t13, t8);
    let t16 = t6 * 2.0;
    let t18 = fma(-x.c0.y, t13, t16);
    let t19 = t7 * 2.0;
    let t21 = fma(-x.c0.z, t13, t19);
    return Vector(vec4<f16>(t15, t18, t21, 0.0));
}

// The matrix of `x -> v x ~v` on `Vector` for a unit `Vector` v (`v >> Vector::slot()`); apply it as `m * x`.
fn unit_vector_matrix_vector(v: Vector) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m6 - m2;
    let m8 = m3 * 2.0;
    let m9 = m4 * 2.0;
    let m10 = m2 + m6;
    let m11 = -m10;
    let m12 = m5 * 2.0;
    let m13 = m2 - m0;
    let m14 = m13 - m1;
    return mat3x3<f16>(vec3<f16>(m7, m8, m9), vec3<f16>(m8, m11, m12), vec3<f16>(m9, m12, m14));
}

// `v x ~v` for `Vector` v and `Bivector` x (`v >> x`).
fn vector_sandwich_bivector(v: Vector, x: Bivector) -> Bivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.x * v.c0.y;
    let t4 = v.c0.x * v.c0.z;
    let t5 = v.c0.y * v.c0.z;
    let t6 = t0 - t1;
    let t7 = t6 - t2;
    let t8 = t2 + t6;
    let t9 = t0 + t1;
    let t10 = t9 - t2;
    let t13 = x.c0.z * t4;
    let t16 = x.c0.z * t5;
    let t18 = x.c0.y * t5;
    let t20 = fma(x.c0.y, t3, t13);
    let t21 = t20 * 2.0;
    let t22 = fma(x.c0.x, t7, t21);
    let t23 = fma(x.c0.x, t3, t16);
    let t24 = t23 * 2.0;
    let t25 = fma(-x.c0.y, t8, t24);
    let t26 = fma(x.c0.x, t4, t18);
    let t27 = t26 * 2.0;
    let t28 = fma(-x.c0.z, t10, t27);
    return Bivector(vec4<f16>(t22, t25, t28, 0.0));
}

// The matrix of `x -> v x ~v` on `Bivector` for `Vector` v (`v >> Bivector::slot()`); apply it as `m * x`.
fn vector_matrix_bivector(v: Vector) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m6 - m2;
    let m8 = m3 * 2.0;
    let m9 = m4 * 2.0;
    let m10 = m2 + m6;
    let m11 = -m10;
    let m12 = m5 * 2.0;
    let m13 = m2 - m0;
    let m14 = m13 - m1;
    return mat3x3<f16>(vec3<f16>(m7, m8, m9), vec3<f16>(m8, m11, m12), vec3<f16>(m9, m12, m14));
}

// `v x ~v` for a unit `Vector` v and `Bivector` x (`v >> x`).
fn unit_vector_sandwich_bivector(v: Vector, x: Bivector) -> Bivector {
    let t1 = v.c0.y * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t1);
    let t4 = fma(v.c0.z, x.c0.z, t3);
    let t5 = v.c0.x * t4;
    let t6 = v.c0.y * t4;
    let t7 = v.c0.z * t4;
    let t8 = t5 * 2.0;
    let t10 = v.c0.y * v.c0.y;
    let t12 = fma(v.c0.x, v.c0.x, t10);
    let t13 = fma(v.c0.z, v.c0.z, t12);
    let t15 = fma(-x.c0.x, t13, t8);
    let t16 = t6 * 2.0;
    let t18 = fma(-x.c0.y, t13, t16);
    let t19 = t7 * 2.0;
    let t21 = fma(-x.c0.z, t13, t19);
    return Bivector(vec4<f16>(t15, t18, t21, 0.0));
}

// The matrix of `x -> v x ~v` on `Bivector` for a unit `Vector` v (`v >> Bivector::slot()`); apply it as `m * x`.
fn unit_vector_matrix_bivector(v: Vector) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m6 - m2;
    let m8 = m3 * 2.0;
    let m9 = m4 * 2.0;
    let m10 = m2 + m6;
    let m11 = -m10;
    let m12 = m5 * 2.0;
    let m13 = m2 - m0;
    let m14 = m13 - m1;
    return mat3x3<f16>(vec3<f16>(m7, m8, m9), vec3<f16>(m8, m11, m12), vec3<f16>(m9, m12, m14));
}

// `v x ~v` for `Vector` v and `Pseudoscalar` x (`v >> x`).
fn vector_sandwich_pseudoscalar(v: Vector, x: Pseudoscalar) -> Pseudoscalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = fma(v.c0.x, v.c0.x, t1);
    let t4 = fma(v.c0.z, v.c0.z, t3);
    let t5 = x.c0.x * t4;
    return Pseudoscalar(vec4<f16>(t5, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Vector` v and `Pseudoscalar` x (`v >> x`).
fn unit_vector_sandwich_pseudoscalar(v: Vector, x: Pseudoscalar) -> Pseudoscalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = fma(v.c0.x, v.c0.x, t1);
    let t4 = fma(v.c0.z, v.c0.z, t3);
    let t5 = x.c0.x * t4;
    return Pseudoscalar(vec4<f16>(t5, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Vector` v and `Paravector` x (`v >> x`).
fn vector_sandwich_paravector(v: Vector, x: Paravector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.x * v.c0.y;
    let t4 = v.c0.x * v.c0.z;
    let t5 = v.c0.y * v.c0.z;
    let t6 = t0 - t1;
    let t7 = t0 + t1;
    let t8 = t2 + t7;
    let t9 = t6 - t2;
    let t10 = t2 + t6;
    let t11 = t7 - t2;
    let t12 = x.c0.x * t8;
    let t15 = x.c0.w * t4;
    let t18 = x.c0.w * t5;
    let t20 = x.c0.z * t5;
    let t22 = fma(x.c0.z, t3, t15);
    let t23 = t22 * 2.0;
    let t24 = fma(x.c0.y, t9, t23);
    let t25 = fma(x.c0.y, t3, t18);
    let t26 = t25 * 2.0;
    let t27 = fma(-x.c0.z, t10, t26);
    let t28 = fma(x.c0.y, t4, t20);
    let t29 = t28 * 2.0;
    let t30 = fma(-x.c0.w, t11, t29);
    return Multivector(vec4<f16>(t12, t24, t27, t30), vec4<f16>(0.0, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Vector` v and `Paravector` x (`v >> x`).
fn unit_vector_sandwich_paravector(v: Vector, x: Paravector) -> Multivector {
    let t1 = v.c0.y * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t1);
    let t4 = fma(v.c0.z, x.c0.w, t3);
    let t5 = v.c0.x * t4;
    let t6 = v.c0.y * t4;
    let t7 = v.c0.z * t4;
    let t8 = t5 * 2.0;
    let t10 = v.c0.y * v.c0.y;
    let t12 = fma(v.c0.x, v.c0.x, t10);
    let t13 = fma(v.c0.z, v.c0.z, t12);
    let t15 = fma(-x.c0.y, t13, t8);
    let t16 = t6 * 2.0;
    let t18 = fma(-x.c0.z, t13, t16);
    let t19 = t7 * 2.0;
    let t21 = fma(-x.c0.w, t13, t19);
    let t22 = x.c0.x * t13;
    return Multivector(vec4<f16>(t22, t15, t18, t21), vec4<f16>(0.0, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Vector` v and `Rotor` x (`v >> x`).
fn vector_sandwich_rotor(v: Vector, x: Rotor) -> Rotor {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.x * v.c0.y;
    let t4 = v.c0.x * v.c0.z;
    let t5 = v.c0.y * v.c0.z;
    let t6 = t0 - t1;
    let t7 = t0 + t1;
    let t8 = t2 + t7;
    let t9 = t6 - t2;
    let t10 = t2 + t6;
    let t11 = t7 - t2;
    let t12 = x.c0.x * t8;
    let t15 = x.c0.w * t4;
    let t18 = x.c0.w * t5;
    let t20 = x.c0.z * t5;
    let t22 = fma(x.c0.z, t3, t15);
    let t23 = t22 * 2.0;
    let t24 = fma(x.c0.y, t9, t23);
    let t25 = fma(x.c0.y, t3, t18);
    let t26 = t25 * 2.0;
    let t27 = fma(-x.c0.z, t10, t26);
    let t28 = fma(x.c0.y, t4, t20);
    let t29 = t28 * 2.0;
    let t30 = fma(-x.c0.w, t11, t29);
    return Rotor(vec4<f16>(t12, t24, t27, t30));
}

// The matrix of `x -> v x ~v` on `Rotor` for `Vector` v (`v >> Rotor::slot()`); apply it as `m * x`.
fn vector_matrix_rotor(v: Vector) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m0 + m1;
    let m8 = m2 + m7;
    let m9 = m6 - m2;
    let m10 = m3 * 2.0;
    let m11 = m4 * 2.0;
    let m12 = m2 + m6;
    let m13 = -m12;
    let m14 = m5 * 2.0;
    let m15 = m2 - m7;
    return mat4x4<f16>(vec4<f16>(m8, 0.0, 0.0, 0.0), vec4<f16>(0.0, m9, m10, m11), vec4<f16>(0.0, m10, m13, m14), vec4<f16>(0.0, m11, m14, m15));
}

// `v x ~v` for a unit `Vector` v and `Rotor` x (`v >> x`).
fn unit_vector_sandwich_rotor(v: Vector, x: Rotor) -> Rotor {
    let t1 = v.c0.y * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t1);
    let t4 = fma(v.c0.z, x.c0.w, t3);
    let t5 = v.c0.x * t4;
    let t6 = v.c0.y * t4;
    let t7 = v.c0.z * t4;
    let t8 = t5 * 2.0;
    let t10 = v.c0.y * v.c0.y;
    let t12 = fma(v.c0.x, v.c0.x, t10);
    let t13 = fma(v.c0.z, v.c0.z, t12);
    let t15 = fma(-x.c0.y, t13, t8);
    let t16 = t6 * 2.0;
    let t18 = fma(-x.c0.z, t13, t16);
    let t19 = t7 * 2.0;
    let t21 = fma(-x.c0.w, t13, t19);
    let t22 = x.c0.x * t13;
    return Rotor(vec4<f16>(t22, t15, t18, t21));
}

// The matrix of `x -> v x ~v` on `Rotor` for a unit `Vector` v (`v >> Rotor::slot()`); apply it as `m * x`.
fn unit_vector_matrix_rotor(v: Vector) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m0 + m1;
    let m8 = m2 + m7;
    let m9 = m6 - m2;
    let m10 = m3 * 2.0;
    let m11 = m4 * 2.0;
    let m12 = m2 + m6;
    let m13 = -m12;
    let m14 = m5 * 2.0;
    let m15 = m2 - m7;
    return mat4x4<f16>(vec4<f16>(m8, 0.0, 0.0, 0.0), vec4<f16>(0.0, m9, m10, m11), vec4<f16>(0.0, m10, m13, m14), vec4<f16>(0.0, m11, m14, m15));
}

// `v x ~v` for `Vector` v and `Odd` x (`v >> x`).
fn vector_sandwich_odd(v: Vector, x: Odd) -> Odd {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.x * v.c0.y;
    let t4 = v.c0.x * v.c0.z;
    let t5 = v.c0.y * v.c0.z;
    let t6 = t0 - t1;
    let t7 = t0 + t1;
    let t8 = t6 - t2;
    let t9 = t2 + t6;
    let t10 = t7 - t2;
    let t11 = t2 + t7;
    let t14 = x.c0.z * t4;
    let t17 = x.c0.z * t5;
    let t19 = x.c0.y * t5;
    let t21 = x.c0.w * t11;
    let t22 = fma(x.c0.y, t3, t14);
    let t23 = t22 * 2.0;
    let t24 = fma(x.c0.x, t8, t23);
    let t25 = fma(x.c0.x, t3, t17);
    let t26 = t25 * 2.0;
    let t27 = fma(-x.c0.y, t9, t26);
    let t28 = fma(x.c0.x, t4, t19);
    let t29 = t28 * 2.0;
    let t30 = fma(-x.c0.z, t10, t29);
    return Odd(vec4<f16>(t24, t27, t30, t21));
}

// The matrix of `x -> v x ~v` on `Odd` for `Vector` v (`v >> Odd::slot()`); apply it as `m * x`.
fn vector_matrix_odd(v: Vector) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m0 + m1;
    let m8 = m6 - m2;
    let m9 = m3 * 2.0;
    let m10 = m4 * 2.0;
    let m11 = m2 + m6;
    let m12 = -m11;
    let m13 = m5 * 2.0;
    let m14 = m2 - m7;
    let m15 = m2 + m7;
    return mat4x4<f16>(vec4<f16>(m8, m9, m10, 0.0), vec4<f16>(m9, m12, m13, 0.0), vec4<f16>(m10, m13, m14, 0.0), vec4<f16>(0.0, 0.0, 0.0, m15));
}

// `v x ~v` for a unit `Vector` v and `Odd` x (`v >> x`).
fn unit_vector_sandwich_odd(v: Vector, x: Odd) -> Odd {
    let t1 = v.c0.y * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t1);
    let t4 = fma(v.c0.z, x.c0.z, t3);
    let t5 = v.c0.x * t4;
    let t6 = v.c0.y * t4;
    let t7 = v.c0.z * t4;
    let t8 = t5 * 2.0;
    let t10 = v.c0.y * v.c0.y;
    let t12 = fma(v.c0.x, v.c0.x, t10);
    let t13 = fma(v.c0.z, v.c0.z, t12);
    let t15 = fma(-x.c0.x, t13, t8);
    let t16 = t6 * 2.0;
    let t18 = fma(-x.c0.y, t13, t16);
    let t19 = t7 * 2.0;
    let t21 = fma(-x.c0.z, t13, t19);
    let t22 = x.c0.w * t13;
    return Odd(vec4<f16>(t15, t18, t21, t22));
}

// The matrix of `x -> v x ~v` on `Odd` for a unit `Vector` v (`v >> Odd::slot()`); apply it as `m * x`.
fn unit_vector_matrix_odd(v: Vector) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.x * v.c0.y;
    let m4 = v.c0.x * v.c0.z;
    let m5 = v.c0.y * v.c0.z;
    let m6 = m0 - m1;
    let m7 = m0 + m1;
    let m8 = m6 - m2;
    let m9 = m3 * 2.0;
    let m10 = m4 * 2.0;
    let m11 = m2 + m6;
    let m12 = -m11;
    let m13 = m5 * 2.0;
    let m14 = m2 - m7;
    let m15 = m2 + m7;
    return mat4x4<f16>(vec4<f16>(m8, m9, m10, 0.0), vec4<f16>(m9, m12, m13, 0.0), vec4<f16>(m10, m13, m14, 0.0), vec4<f16>(0.0, 0.0, 0.0, m15));
}

// `v x ~v` for `Vector` v and `Multivector` x (`v >> x`).
fn vector_sandwich_multivector(v: Vector, x: Multivector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.x * v.c0.y;
    let t4 = v.c0.x * v.c0.z;
    let t5 = v.c0.y * v.c0.z;
    let t6 = t0 - t1;
    let t7 = t0 + t1;
    let t8 = t2 + t7;
    let t9 = t6 - t2;
    let t10 = t2 + t6;
    let t11 = t7 - t2;
    let t12 = x.c0.x * t8;
    let t15 = x.c0.w * t4;
    let t18 = x.c0.w * t5;
    let t20 = x.c0.z * t5;
    let t24 = x.c1.z * t4;
    let t27 = x.c1.z * t5;
    let t29 = x.c1.y * t5;
    let t31 = x.c1.w * t8;
    let t32 = fma(x.c0.z, t3, t15);
    let t33 = t32 * 2.0;
    let t34 = fma(x.c0.y, t9, t33);
    let t35 = fma(x.c0.y, t3, t18);
    let t36 = t35 * 2.0;
    let t37 = fma(-x.c0.z, t10, t36);
    let t38 = fma(x.c0.y, t4, t20);
    let t39 = t38 * 2.0;
    let t40 = fma(-x.c0.w, t11, t39);
    let t41 = fma(x.c1.y, t3, t24);
    let t42 = t41 * 2.0;
    let t43 = fma(x.c1.x, t9, t42);
    let t44 = fma(x.c1.x, t3, t27);
    let t45 = t44 * 2.0;
    let t46 = fma(-x.c1.y, t10, t45);
    let t47 = fma(x.c1.x, t4, t29);
    let t48 = t47 * 2.0;
    let t49 = fma(-x.c1.z, t11, t48);
    return Multivector(vec4<f16>(t12, t34, t37, t40), vec4<f16>(t43, t46, t49, t31));
}

// `v x ~v` for a unit `Vector` v and `Multivector` x (`v >> x`).
fn unit_vector_sandwich_multivector(v: Vector, x: Multivector) -> Multivector {
    let t1 = v.c0.y * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t1);
    let t4 = fma(v.c0.z, x.c0.w, t3);
    let t6 = v.c0.y * x.c1.y;
    let t8 = fma(v.c0.x, x.c1.x, t6);
    let t9 = fma(v.c0.z, x.c1.z, t8);
    let t10 = v.c0.x * t4;
    let t11 = v.c0.y * t4;
    let t12 = v.c0.z * t4;
    let t13 = v.c0.x * t9;
    let t14 = v.c0.y * t9;
    let t15 = v.c0.z * t9;
    let t16 = t10 * 2.0;
    let t18 = v.c0.y * v.c0.y;
    let t20 = fma(v.c0.x, v.c0.x, t18);
    let t21 = fma(v.c0.z, v.c0.z, t20);
    let t23 = fma(-x.c0.y, t21, t16);
    let t24 = t11 * 2.0;
    let t26 = fma(-x.c0.z, t21, t24);
    let t27 = t12 * 2.0;
    let t29 = fma(-x.c0.w, t21, t27);
    let t30 = t13 * 2.0;
    let t32 = fma(-x.c1.x, t21, t30);
    let t33 = t14 * 2.0;
    let t35 = fma(-x.c1.y, t21, t33);
    let t36 = t15 * 2.0;
    let t38 = fma(-x.c1.z, t21, t36);
    let t39 = x.c0.x * t21;
    let t40 = x.c1.w * t21;
    return Multivector(vec4<f16>(t39, t23, t26, t29), vec4<f16>(t32, t35, t38, t40));
}

// `v x ~v` for `Rotor` v and `Scalar` x (`v >> x`).
fn rotor_sandwich_scalar(v: Rotor, x: Scalar) -> Scalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Scalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Rotor` v and `Scalar` x (`v >> x`).
fn unit_rotor_sandwich_scalar(v: Rotor, x: Scalar) -> Scalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Scalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Rotor` v and `Vector` x (`v >> x`).
fn rotor_sandwich_vector(v: Rotor, x: Vector) -> Vector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t2 - t3;
    let t12 = t0 + t1;
    let t13 = t2 + t3;
    let t14 = t12 - t13;
    let t15 = t6 + t7;
    let t16 = t5 - t8;
    let t17 = t6 - t7;
    let t18 = t10 + t11;
    let t19 = t4 + t9;
    let t20 = t5 + t8;
    let t21 = t4 - t9;
    let t22 = t10 - t11;
    let t24 = x.c0.y * t15;
    let t28 = x.c0.z * t19;
    let t29 = x.c0.x * t20;
    let t32 = fma(-x.c0.z, t16, t24);
    let t33 = t32 * 2.0;
    let t34 = fma(x.c0.x, t14, t33);
    let t35 = fma(-x.c0.x, t17, t28);
    let t36 = t35 * 2.0;
    let t37 = fma(x.c0.y, t18, t36);
    let t38 = fma(-x.c0.y, t21, t29);
    let t39 = t38 * 2.0;
    let t40 = fma(x.c0.z, t22, t39);
    return Vector(vec4<f16>(t34, t37, t40, 0.0));
}

// The matrix of `x -> v x ~v` on `Vector` for `Rotor` v (`v >> Vector::slot()`); apply it as `m * x`.
fn rotor_matrix_vector(v: Rotor) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m0 + m1;
    let m13 = m2 + m3;
    let m14 = m12 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m11;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m11;
    return mat3x3<f16>(vec3<f16>(m14, m20, m25), vec3<f16>(m16, m21, m27), vec3<f16>(m18, m23, m28));
}

// `v x ~v` for a unit `Rotor` v and `Vector` x (`v >> x`).
fn unit_rotor_sandwich_vector(v: Rotor, x: Vector) -> Vector {
    let t2 = v.c0.w * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t2);
    let t4 = fma(-v.c0.z, x.c0.z, t3);
    let t6 = v.c0.y * x.c0.z;
    let t8 = fma(v.c0.x, x.c0.y, t6);
    let t9 = fma(-v.c0.w, x.c0.x, t8);
    let t12 = v.c0.z * x.c0.x;
    let t13 = fma(v.c0.x, x.c0.z, t12);
    let t14 = fma(-v.c0.y, x.c0.y, t13);
    let t16 = v.c0.w * t9;
    let t17 = v.c0.y * t14;
    let t20 = v.c0.z * t4;
    let t21 = fma(-v.c0.z, t14, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.x * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t4, t17);
    let t34 = x.c0.y * t29;
    let t35 = fma(t32, 2.0, t34);
    let t36 = fma(-v.c0.y, t9, t20);
    let t38 = x.c0.z * t29;
    let t39 = fma(t36, 2.0, t38);
    return Vector(vec4<f16>(t31, t35, t39, 0.0));
}

// The matrix of `x -> v x ~v` on `Vector` for a unit `Rotor` v (`v >> Vector::slot()`); apply it as `m * x`.
fn unit_rotor_matrix_vector(v: Rotor) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m0 + m1;
    let m13 = m2 + m3;
    let m14 = m12 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m11;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m11;
    return mat3x3<f16>(vec3<f16>(m14, m20, m25), vec3<f16>(m16, m21, m27), vec3<f16>(m18, m23, m28));
}

// `v x ~v` for `Rotor` v and `Bivector` x (`v >> x`).
fn rotor_sandwich_bivector(v: Rotor, x: Bivector) -> Bivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t2 - t3;
    let t12 = t0 + t1;
    let t13 = t2 + t3;
    let t14 = t12 - t13;
    let t15 = t6 + t7;
    let t16 = t5 - t8;
    let t17 = t6 - t7;
    let t18 = t10 + t11;
    let t19 = t4 + t9;
    let t20 = t5 + t8;
    let t21 = t4 - t9;
    let t22 = t10 - t11;
    let t24 = x.c0.y * t15;
    let t28 = x.c0.z * t19;
    let t29 = x.c0.x * t20;
    let t32 = fma(-x.c0.z, t16, t24);
    let t33 = t32 * 2.0;
    let t34 = fma(x.c0.x, t14, t33);
    let t35 = fma(-x.c0.x, t17, t28);
    let t36 = t35 * 2.0;
    let t37 = fma(x.c0.y, t18, t36);
    let t38 = fma(-x.c0.y, t21, t29);
    let t39 = t38 * 2.0;
    let t40 = fma(x.c0.z, t22, t39);
    return Bivector(vec4<f16>(t34, t37, t40, 0.0));
}

// The matrix of `x -> v x ~v` on `Bivector` for `Rotor` v (`v >> Bivector::slot()`); apply it as `m * x`.
fn rotor_matrix_bivector(v: Rotor) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m0 + m1;
    let m13 = m2 + m3;
    let m14 = m12 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m11;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m11;
    return mat3x3<f16>(vec3<f16>(m14, m20, m25), vec3<f16>(m16, m21, m27), vec3<f16>(m18, m23, m28));
}

// `v x ~v` for a unit `Rotor` v and `Bivector` x (`v >> x`).
fn unit_rotor_sandwich_bivector(v: Rotor, x: Bivector) -> Bivector {
    let t2 = v.c0.w * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t2);
    let t4 = fma(-v.c0.z, x.c0.z, t3);
    let t6 = v.c0.y * x.c0.z;
    let t8 = fma(v.c0.x, x.c0.y, t6);
    let t9 = fma(-v.c0.w, x.c0.x, t8);
    let t12 = v.c0.z * x.c0.x;
    let t13 = fma(v.c0.x, x.c0.z, t12);
    let t14 = fma(-v.c0.y, x.c0.y, t13);
    let t16 = v.c0.w * t9;
    let t17 = v.c0.y * t14;
    let t20 = v.c0.z * t4;
    let t21 = fma(-v.c0.z, t14, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.x * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t4, t17);
    let t34 = x.c0.y * t29;
    let t35 = fma(t32, 2.0, t34);
    let t36 = fma(-v.c0.y, t9, t20);
    let t38 = x.c0.z * t29;
    let t39 = fma(t36, 2.0, t38);
    return Bivector(vec4<f16>(t31, t35, t39, 0.0));
}

// The matrix of `x -> v x ~v` on `Bivector` for a unit `Rotor` v (`v >> Bivector::slot()`); apply it as `m * x`.
fn unit_rotor_matrix_bivector(v: Rotor) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m0 + m1;
    let m13 = m2 + m3;
    let m14 = m12 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m11;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m11;
    return mat3x3<f16>(vec3<f16>(m14, m20, m25), vec3<f16>(m16, m21, m27), vec3<f16>(m18, m23, m28));
}

// `v x ~v` for `Rotor` v and `Pseudoscalar` x (`v >> x`).
fn rotor_sandwich_pseudoscalar(v: Rotor, x: Pseudoscalar) -> Pseudoscalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Pseudoscalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Rotor` v and `Pseudoscalar` x (`v >> x`).
fn unit_rotor_sandwich_pseudoscalar(v: Rotor, x: Pseudoscalar) -> Pseudoscalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Pseudoscalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Rotor` v and `Paravector` x (`v >> x`).
fn rotor_sandwich_paravector(v: Rotor, x: Paravector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t11 - t13;
    let t16 = t6 + t7;
    let t17 = t5 - t8;
    let t18 = t6 - t7;
    let t19 = t10 + t12;
    let t20 = t4 + t9;
    let t21 = t5 + t8;
    let t22 = t4 - t9;
    let t23 = t10 - t12;
    let t24 = x.c0.x * t14;
    let t26 = x.c0.z * t16;
    let t30 = x.c0.w * t20;
    let t31 = x.c0.y * t21;
    let t34 = fma(-x.c0.w, t17, t26);
    let t35 = t34 * 2.0;
    let t36 = fma(x.c0.y, t15, t35);
    let t37 = fma(-x.c0.y, t18, t30);
    let t38 = t37 * 2.0;
    let t39 = fma(x.c0.z, t19, t38);
    let t40 = fma(-x.c0.z, t22, t31);
    let t41 = t40 * 2.0;
    let t42 = fma(x.c0.w, t23, t41);
    return Multivector(vec4<f16>(t24, t36, t39, t42), vec4<f16>(0.0, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Rotor` v and `Paravector` x (`v >> x`).
fn unit_rotor_sandwich_paravector(v: Rotor, x: Paravector) -> Multivector {
    let t2 = v.c0.w * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t2);
    let t4 = fma(-v.c0.z, x.c0.w, t3);
    let t6 = v.c0.y * x.c0.w;
    let t8 = fma(v.c0.x, x.c0.z, t6);
    let t9 = fma(-v.c0.w, x.c0.y, t8);
    let t12 = v.c0.z * x.c0.y;
    let t13 = fma(v.c0.x, x.c0.w, t12);
    let t14 = fma(-v.c0.y, x.c0.z, t13);
    let t16 = v.c0.w * t9;
    let t17 = v.c0.y * t14;
    let t20 = v.c0.z * t4;
    let t21 = fma(-v.c0.z, t14, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.y * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t4, t17);
    let t34 = x.c0.z * t29;
    let t35 = fma(t32, 2.0, t34);
    let t36 = fma(-v.c0.y, t9, t20);
    let t38 = x.c0.w * t29;
    let t39 = fma(t36, 2.0, t38);
    let t40 = x.c0.x * t29;
    return Multivector(vec4<f16>(t40, t31, t35, t39), vec4<f16>(0.0, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Rotor` v and `Rotor` x (`v >> x`).
fn rotor_sandwich_rotor(v: Rotor, x: Rotor) -> Rotor {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t11 - t13;
    let t16 = t6 + t7;
    let t17 = t5 - t8;
    let t18 = t6 - t7;
    let t19 = t10 + t12;
    let t20 = t4 + t9;
    let t21 = t5 + t8;
    let t22 = t4 - t9;
    let t23 = t10 - t12;
    let t24 = x.c0.x * t14;
    let t26 = x.c0.z * t16;
    let t30 = x.c0.w * t20;
    let t31 = x.c0.y * t21;
    let t34 = fma(-x.c0.w, t17, t26);
    let t35 = t34 * 2.0;
    let t36 = fma(x.c0.y, t15, t35);
    let t37 = fma(-x.c0.y, t18, t30);
    let t38 = t37 * 2.0;
    let t39 = fma(x.c0.z, t19, t38);
    let t40 = fma(-x.c0.z, t22, t31);
    let t41 = t40 * 2.0;
    let t42 = fma(x.c0.w, t23, t41);
    return Rotor(vec4<f16>(t24, t36, t39, t42));
}

// The matrix of `x -> v x ~v` on `Rotor` for `Rotor` v (`v >> Rotor::slot()`); apply it as `m * x`.
fn rotor_matrix_rotor(v: Rotor) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m0 + m1;
    let m12 = m2 - m3;
    let m13 = m2 + m3;
    let m14 = m11 + m13;
    let m15 = m11 - m13;
    let m16 = m6 + m7;
    let m17 = m16 * 2.0;
    let m18 = m8 - m5;
    let m19 = m18 * 2.0;
    let m20 = m7 - m6;
    let m21 = m20 * 2.0;
    let m22 = m10 + m12;
    let m23 = m4 + m9;
    let m24 = m23 * 2.0;
    let m25 = m5 + m8;
    let m26 = m25 * 2.0;
    let m27 = m9 - m4;
    let m28 = m27 * 2.0;
    let m29 = m10 - m12;
    return mat4x4<f16>(vec4<f16>(m14, 0.0, 0.0, 0.0), vec4<f16>(0.0, m15, m21, m26), vec4<f16>(0.0, m17, m22, m28), vec4<f16>(0.0, m19, m24, m29));
}

// `v x ~v` for a unit `Rotor` v and `Rotor` x (`v >> x`).
fn unit_rotor_sandwich_rotor(v: Rotor, x: Rotor) -> Rotor {
    let t2 = v.c0.w * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t2);
    let t4 = fma(-v.c0.z, x.c0.w, t3);
    let t6 = v.c0.y * x.c0.w;
    let t8 = fma(v.c0.x, x.c0.z, t6);
    let t9 = fma(-v.c0.w, x.c0.y, t8);
    let t12 = v.c0.z * x.c0.y;
    let t13 = fma(v.c0.x, x.c0.w, t12);
    let t14 = fma(-v.c0.y, x.c0.z, t13);
    let t16 = v.c0.w * t9;
    let t17 = v.c0.y * t14;
    let t20 = v.c0.z * t4;
    let t21 = fma(-v.c0.z, t14, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.y * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t4, t17);
    let t34 = x.c0.z * t29;
    let t35 = fma(t32, 2.0, t34);
    let t36 = fma(-v.c0.y, t9, t20);
    let t38 = x.c0.w * t29;
    let t39 = fma(t36, 2.0, t38);
    let t40 = x.c0.x * t29;
    return Rotor(vec4<f16>(t40, t31, t35, t39));
}

// The matrix of `x -> v x ~v` on `Rotor` for a unit `Rotor` v (`v >> Rotor::slot()`); apply it as `m * x`.
fn unit_rotor_matrix_rotor(v: Rotor) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m0 + m1;
    let m13 = m2 + m3;
    let m14 = m12 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m11;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m11;
    let m29 = m12 + m13;
    return mat4x4<f16>(vec4<f16>(m29, 0.0, 0.0, 0.0), vec4<f16>(0.0, m14, m20, m25), vec4<f16>(0.0, m16, m21, m27), vec4<f16>(0.0, m18, m23, m28));
}

// `v x ~v` for `Rotor` v and `Odd` x (`v >> x`).
fn rotor_sandwich_odd(v: Rotor, x: Odd) -> Odd {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 - t13;
    let t15 = t6 + t7;
    let t16 = t5 - t8;
    let t17 = t6 - t7;
    let t18 = t10 + t12;
    let t19 = t4 + t9;
    let t20 = t5 + t8;
    let t21 = t4 - t9;
    let t22 = t10 - t12;
    let t23 = t11 + t13;
    let t25 = x.c0.y * t15;
    let t29 = x.c0.z * t19;
    let t30 = x.c0.x * t20;
    let t33 = x.c0.w * t23;
    let t34 = fma(-x.c0.z, t16, t25);
    let t35 = t34 * 2.0;
    let t36 = fma(x.c0.x, t14, t35);
    let t37 = fma(-x.c0.x, t17, t29);
    let t38 = t37 * 2.0;
    let t39 = fma(x.c0.y, t18, t38);
    let t40 = fma(-x.c0.y, t21, t30);
    let t41 = t40 * 2.0;
    let t42 = fma(x.c0.z, t22, t41);
    return Odd(vec4<f16>(t36, t39, t42, t33));
}

// The matrix of `x -> v x ~v` on `Odd` for `Rotor` v (`v >> Odd::slot()`); apply it as `m * x`.
fn rotor_matrix_odd(v: Rotor) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m0 + m1;
    let m12 = m2 - m3;
    let m13 = m2 + m3;
    let m14 = m11 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m12;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m12;
    let m29 = m11 + m13;
    return mat4x4<f16>(vec4<f16>(m14, m20, m25, 0.0), vec4<f16>(m16, m21, m27, 0.0), vec4<f16>(m18, m23, m28, 0.0), vec4<f16>(0.0, 0.0, 0.0, m29));
}

// `v x ~v` for a unit `Rotor` v and `Odd` x (`v >> x`).
fn unit_rotor_sandwich_odd(v: Rotor, x: Odd) -> Odd {
    let t2 = v.c0.w * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t2);
    let t4 = fma(-v.c0.z, x.c0.z, t3);
    let t6 = v.c0.y * x.c0.z;
    let t8 = fma(v.c0.x, x.c0.y, t6);
    let t9 = fma(-v.c0.w, x.c0.x, t8);
    let t12 = v.c0.z * x.c0.x;
    let t13 = fma(v.c0.x, x.c0.z, t12);
    let t14 = fma(-v.c0.y, x.c0.y, t13);
    let t16 = v.c0.w * t9;
    let t17 = v.c0.y * t14;
    let t20 = v.c0.z * t4;
    let t21 = fma(-v.c0.z, t14, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.x * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t4, t17);
    let t34 = x.c0.y * t29;
    let t35 = fma(t32, 2.0, t34);
    let t36 = fma(-v.c0.y, t9, t20);
    let t38 = x.c0.z * t29;
    let t39 = fma(t36, 2.0, t38);
    let t40 = x.c0.w * t29;
    return Odd(vec4<f16>(t31, t35, t39, t40));
}

// The matrix of `x -> v x ~v` on `Odd` for a unit `Rotor` v (`v >> Odd::slot()`); apply it as `m * x`.
fn unit_rotor_matrix_odd(v: Rotor) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m0 + m1;
    let m13 = m2 + m3;
    let m14 = m12 - m13;
    let m15 = m6 + m7;
    let m16 = m15 * 2.0;
    let m17 = m8 - m5;
    let m18 = m17 * 2.0;
    let m19 = m7 - m6;
    let m20 = m19 * 2.0;
    let m21 = m10 + m11;
    let m22 = m4 + m9;
    let m23 = m22 * 2.0;
    let m24 = m5 + m8;
    let m25 = m24 * 2.0;
    let m26 = m9 - m4;
    let m27 = m26 * 2.0;
    let m28 = m10 - m11;
    let m29 = m12 + m13;
    return mat4x4<f16>(vec4<f16>(m14, m20, m25, 0.0), vec4<f16>(m16, m21, m27, 0.0), vec4<f16>(m18, m23, m28, 0.0), vec4<f16>(0.0, 0.0, 0.0, m29));
}

// `v x ~v` for `Rotor` v and `Multivector` x (`v >> x`).
fn rotor_sandwich_multivector(v: Rotor, x: Multivector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t11 - t13;
    let t16 = t6 + t7;
    let t17 = t5 - t8;
    let t18 = t6 - t7;
    let t19 = t10 + t12;
    let t20 = t4 + t9;
    let t21 = t5 + t8;
    let t22 = t4 - t9;
    let t23 = t10 - t12;
    let t24 = x.c0.x * t14;
    let t26 = x.c0.z * t16;
    let t30 = x.c0.w * t20;
    let t31 = x.c0.y * t21;
    let t35 = x.c1.y * t16;
    let t39 = x.c1.z * t20;
    let t40 = x.c1.x * t21;
    let t43 = x.c1.w * t14;
    let t44 = fma(-x.c0.w, t17, t26);
    let t45 = t44 * 2.0;
    let t46 = fma(x.c0.y, t15, t45);
    let t47 = fma(-x.c0.y, t18, t30);
    let t48 = t47 * 2.0;
    let t49 = fma(x.c0.z, t19, t48);
    let t50 = fma(-x.c0.z, t22, t31);
    let t51 = t50 * 2.0;
    let t52 = fma(x.c0.w, t23, t51);
    let t53 = fma(-x.c1.z, t17, t35);
    let t54 = t53 * 2.0;
    let t55 = fma(x.c1.x, t15, t54);
    let t56 = fma(-x.c1.x, t18, t39);
    let t57 = t56 * 2.0;
    let t58 = fma(x.c1.y, t19, t57);
    let t59 = fma(-x.c1.y, t22, t40);
    let t60 = t59 * 2.0;
    let t61 = fma(x.c1.z, t23, t60);
    return Multivector(vec4<f16>(t24, t46, t49, t52), vec4<f16>(t55, t58, t61, t43));
}

// `v x ~v` for a unit `Rotor` v and `Multivector` x (`v >> x`).
fn unit_rotor_sandwich_multivector(v: Rotor, x: Multivector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t11 - t13;
    let t16 = t6 + t7;
    let t17 = t5 - t8;
    let t18 = t6 - t7;
    let t19 = t10 + t12;
    let t20 = t4 + t9;
    let t21 = t5 + t8;
    let t22 = t4 - t9;
    let t23 = t10 - t12;
    let t24 = x.c0.x * t14;
    let t26 = x.c0.z * t16;
    let t30 = x.c0.w * t20;
    let t31 = x.c0.y * t21;
    let t35 = x.c1.y * t16;
    let t39 = x.c1.z * t20;
    let t40 = x.c1.x * t21;
    let t43 = x.c1.w * t14;
    let t44 = fma(-x.c0.w, t17, t26);
    let t45 = t44 * 2.0;
    let t46 = fma(x.c0.y, t15, t45);
    let t47 = fma(-x.c0.y, t18, t30);
    let t48 = t47 * 2.0;
    let t49 = fma(x.c0.z, t19, t48);
    let t50 = fma(-x.c0.z, t22, t31);
    let t51 = t50 * 2.0;
    let t52 = fma(x.c0.w, t23, t51);
    let t53 = fma(-x.c1.z, t17, t35);
    let t54 = t53 * 2.0;
    let t55 = fma(x.c1.x, t15, t54);
    let t56 = fma(-x.c1.x, t18, t39);
    let t57 = t56 * 2.0;
    let t58 = fma(x.c1.y, t19, t57);
    let t59 = fma(-x.c1.y, t22, t40);
    let t60 = t59 * 2.0;
    let t61 = fma(x.c1.z, t23, t60);
    return Multivector(vec4<f16>(t24, t46, t49, t52), vec4<f16>(t55, t58, t61, t43));
}

// `v x ~v` for `Odd` v and `Scalar` x (`v >> x`).
fn odd_sandwich_scalar(v: Odd, x: Scalar) -> Scalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Scalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Odd` v and `Scalar` x (`v >> x`).
fn unit_odd_sandwich_scalar(v: Odd, x: Scalar) -> Scalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Scalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Odd` v and `Vector` x (`v >> x`).
fn odd_sandwich_vector(v: Odd, x: Vector) -> Vector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t2 - t3;
    let t12 = t10 - t11;
    let t13 = t4 - t9;
    let t14 = t5 + t8;
    let t15 = t4 + t9;
    let t16 = t10 + t11;
    let t17 = t6 - t7;
    let t18 = t5 - t8;
    let t19 = t6 + t7;
    let t20 = t0 + t1;
    let t21 = t2 + t3;
    let t22 = t20 - t21;
    let t25 = x.c0.z * t14;
    let t26 = x.c0.x * t15;
    let t30 = x.c0.y * t19;
    let t32 = fma(x.c0.y, t13, t25);
    let t33 = t32 * 2.0;
    let t34 = fma(x.c0.x, t12, t33);
    let t35 = fma(-x.c0.z, t17, t26);
    let t36 = t35 * 2.0;
    let t37 = fma(-x.c0.y, t16, t36);
    let t38 = fma(x.c0.x, t18, t30);
    let t39 = t38 * 2.0;
    let t40 = fma(-x.c0.z, t22, t39);
    return Vector(vec4<f16>(t34, t37, t40, 0.0));
}

// The matrix of `x -> v x ~v` on `Vector` for `Odd` v (`v >> Vector::slot()`); apply it as `m * x`.
fn odd_matrix_vector(v: Odd) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m10 - m11;
    let m13 = m4 - m9;
    let m14 = m13 * 2.0;
    let m15 = m5 + m8;
    let m16 = m15 * 2.0;
    let m17 = m4 + m9;
    let m18 = m17 * 2.0;
    let m19 = m10 + m11;
    let m20 = -m19;
    let m21 = m7 - m6;
    let m22 = m21 * 2.0;
    let m23 = m5 - m8;
    let m24 = m23 * 2.0;
    let m25 = m6 + m7;
    let m26 = m25 * 2.0;
    let m27 = m2 + m3;
    let m28 = m0 + m1;
    let m29 = m27 - m28;
    return mat3x3<f16>(vec3<f16>(m12, m18, m24), vec3<f16>(m14, m20, m26), vec3<f16>(m16, m22, m29));
}

// `v x ~v` for a unit `Odd` v and `Vector` x (`v >> x`).
fn unit_odd_sandwich_vector(v: Odd, x: Vector) -> Vector {
    let t1 = v.c0.y * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t1);
    let t4 = fma(v.c0.z, x.c0.z, t3);
    let t7 = v.c0.w * x.c0.z;
    let t8 = fma(v.c0.x, x.c0.y, t7);
    let t9 = fma(-v.c0.y, x.c0.x, t8);
    let t10 = v.c0.x * x.c0.z;
    let t13 = fma(-v.c0.z, x.c0.x, t10);
    let t14 = fma(-v.c0.w, x.c0.y, t13);
    let t16 = v.c0.z * t14;
    let t17 = v.c0.y * t4;
    let t20 = v.c0.w * t9;
    let t21 = fma(v.c0.y, t9, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.x * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t14, t17);
    let t33 = t32 * 2.0;
    let t35 = fma(-x.c0.y, t29, t33);
    let t36 = fma(v.c0.z, t4, t20);
    let t37 = t36 * 2.0;
    let t39 = fma(-x.c0.z, t29, t37);
    return Vector(vec4<f16>(t31, t35, t39, 0.0));
}

// The matrix of `x -> v x ~v` on `Vector` for a unit `Odd` v (`v >> Vector::slot()`); apply it as `m * x`.
fn unit_odd_matrix_vector(v: Odd) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m10 - m11;
    let m13 = m4 - m9;
    let m14 = m13 * 2.0;
    let m15 = m5 + m8;
    let m16 = m15 * 2.0;
    let m17 = m4 + m9;
    let m18 = m17 * 2.0;
    let m19 = m10 + m11;
    let m20 = -m19;
    let m21 = m7 - m6;
    let m22 = m21 * 2.0;
    let m23 = m5 - m8;
    let m24 = m23 * 2.0;
    let m25 = m6 + m7;
    let m26 = m25 * 2.0;
    let m27 = m2 + m3;
    let m28 = m0 + m1;
    let m29 = m27 - m28;
    return mat3x3<f16>(vec3<f16>(m12, m18, m24), vec3<f16>(m14, m20, m26), vec3<f16>(m16, m22, m29));
}

// `v x ~v` for `Odd` v and `Bivector` x (`v >> x`).
fn odd_sandwich_bivector(v: Odd, x: Bivector) -> Bivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t2 - t3;
    let t12 = t10 - t11;
    let t13 = t4 - t9;
    let t14 = t5 + t8;
    let t15 = t4 + t9;
    let t16 = t10 + t11;
    let t17 = t6 - t7;
    let t18 = t5 - t8;
    let t19 = t6 + t7;
    let t20 = t0 + t1;
    let t21 = t2 + t3;
    let t22 = t20 - t21;
    let t25 = x.c0.z * t14;
    let t26 = x.c0.x * t15;
    let t30 = x.c0.y * t19;
    let t32 = fma(x.c0.y, t13, t25);
    let t33 = t32 * 2.0;
    let t34 = fma(x.c0.x, t12, t33);
    let t35 = fma(-x.c0.z, t17, t26);
    let t36 = t35 * 2.0;
    let t37 = fma(-x.c0.y, t16, t36);
    let t38 = fma(x.c0.x, t18, t30);
    let t39 = t38 * 2.0;
    let t40 = fma(-x.c0.z, t22, t39);
    return Bivector(vec4<f16>(t34, t37, t40, 0.0));
}

// The matrix of `x -> v x ~v` on `Bivector` for `Odd` v (`v >> Bivector::slot()`); apply it as `m * x`.
fn odd_matrix_bivector(v: Odd) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m10 - m11;
    let m13 = m4 - m9;
    let m14 = m13 * 2.0;
    let m15 = m5 + m8;
    let m16 = m15 * 2.0;
    let m17 = m4 + m9;
    let m18 = m17 * 2.0;
    let m19 = m10 + m11;
    let m20 = -m19;
    let m21 = m7 - m6;
    let m22 = m21 * 2.0;
    let m23 = m5 - m8;
    let m24 = m23 * 2.0;
    let m25 = m6 + m7;
    let m26 = m25 * 2.0;
    let m27 = m2 + m3;
    let m28 = m0 + m1;
    let m29 = m27 - m28;
    return mat3x3<f16>(vec3<f16>(m12, m18, m24), vec3<f16>(m14, m20, m26), vec3<f16>(m16, m22, m29));
}

// `v x ~v` for a unit `Odd` v and `Bivector` x (`v >> x`).
fn unit_odd_sandwich_bivector(v: Odd, x: Bivector) -> Bivector {
    let t1 = v.c0.y * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t1);
    let t4 = fma(v.c0.z, x.c0.z, t3);
    let t7 = v.c0.w * x.c0.z;
    let t8 = fma(v.c0.x, x.c0.y, t7);
    let t9 = fma(-v.c0.y, x.c0.x, t8);
    let t10 = v.c0.x * x.c0.z;
    let t13 = fma(-v.c0.z, x.c0.x, t10);
    let t14 = fma(-v.c0.w, x.c0.y, t13);
    let t16 = v.c0.z * t14;
    let t17 = v.c0.y * t4;
    let t20 = v.c0.w * t9;
    let t21 = fma(v.c0.y, t9, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.x * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t14, t17);
    let t33 = t32 * 2.0;
    let t35 = fma(-x.c0.y, t29, t33);
    let t36 = fma(v.c0.z, t4, t20);
    let t37 = t36 * 2.0;
    let t39 = fma(-x.c0.z, t29, t37);
    return Bivector(vec4<f16>(t31, t35, t39, 0.0));
}

// The matrix of `x -> v x ~v` on `Bivector` for a unit `Odd` v (`v >> Bivector::slot()`); apply it as `m * x`.
fn unit_odd_matrix_bivector(v: Odd) -> mat3x3<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m10 - m11;
    let m13 = m4 - m9;
    let m14 = m13 * 2.0;
    let m15 = m5 + m8;
    let m16 = m15 * 2.0;
    let m17 = m4 + m9;
    let m18 = m17 * 2.0;
    let m19 = m10 + m11;
    let m20 = -m19;
    let m21 = m7 - m6;
    let m22 = m21 * 2.0;
    let m23 = m5 - m8;
    let m24 = m23 * 2.0;
    let m25 = m6 + m7;
    let m26 = m25 * 2.0;
    let m27 = m2 + m3;
    let m28 = m0 + m1;
    let m29 = m27 - m28;
    return mat3x3<f16>(vec3<f16>(m12, m18, m24), vec3<f16>(m14, m20, m26), vec3<f16>(m16, m22, m29));
}

// `v x ~v` for `Odd` v and `Pseudoscalar` x (`v >> x`).
fn odd_sandwich_pseudoscalar(v: Odd, x: Pseudoscalar) -> Pseudoscalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Pseudoscalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Odd` v and `Pseudoscalar` x (`v >> x`).
fn unit_odd_sandwich_pseudoscalar(v: Odd, x: Pseudoscalar) -> Pseudoscalar {
    let t1 = v.c0.y * v.c0.y;
    let t3 = v.c0.w * v.c0.w;
    let t4 = fma(v.c0.x, v.c0.x, t1);
    let t5 = fma(v.c0.z, v.c0.z, t3);
    let t6 = t4 + t5;
    let t7 = x.c0.x * t6;
    return Pseudoscalar(vec4<f16>(t7, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Odd` v and `Paravector` x (`v >> x`).
fn odd_sandwich_paravector(v: Odd, x: Paravector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t10 - t12;
    let t16 = t4 - t9;
    let t17 = t5 + t8;
    let t18 = t4 + t9;
    let t19 = t10 + t12;
    let t20 = t6 - t7;
    let t21 = t5 - t8;
    let t22 = t6 + t7;
    let t23 = t11 - t13;
    let t24 = x.c0.x * t14;
    let t27 = x.c0.w * t17;
    let t28 = x.c0.y * t18;
    let t32 = x.c0.z * t22;
    let t34 = fma(x.c0.z, t16, t27);
    let t35 = t34 * 2.0;
    let t36 = fma(x.c0.y, t15, t35);
    let t37 = fma(-x.c0.w, t20, t28);
    let t38 = t37 * 2.0;
    let t39 = fma(-x.c0.z, t19, t38);
    let t40 = fma(x.c0.y, t21, t32);
    let t41 = t40 * 2.0;
    let t42 = fma(-x.c0.w, t23, t41);
    return Multivector(vec4<f16>(t24, t36, t39, t42), vec4<f16>(0.0, 0.0, 0.0, 0.0));
}

// `v x ~v` for a unit `Odd` v and `Paravector` x (`v >> x`).
fn unit_odd_sandwich_paravector(v: Odd, x: Paravector) -> Multivector {
    let t1 = v.c0.y * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t1);
    let t4 = fma(v.c0.z, x.c0.w, t3);
    let t7 = v.c0.w * x.c0.w;
    let t8 = fma(v.c0.x, x.c0.z, t7);
    let t9 = fma(-v.c0.y, x.c0.y, t8);
    let t10 = v.c0.x * x.c0.w;
    let t13 = fma(-v.c0.z, x.c0.y, t10);
    let t14 = fma(-v.c0.w, x.c0.z, t13);
    let t16 = v.c0.z * t14;
    let t17 = v.c0.y * t4;
    let t20 = v.c0.w * t9;
    let t21 = fma(v.c0.y, t9, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.y * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t14, t17);
    let t33 = t32 * 2.0;
    let t35 = fma(-x.c0.z, t29, t33);
    let t36 = fma(v.c0.z, t4, t20);
    let t37 = t36 * 2.0;
    let t39 = fma(-x.c0.w, t29, t37);
    let t40 = x.c0.x * t29;
    return Multivector(vec4<f16>(t40, t31, t35, t39), vec4<f16>(0.0, 0.0, 0.0, 0.0));
}

// `v x ~v` for `Odd` v and `Rotor` x (`v >> x`).
fn odd_sandwich_rotor(v: Odd, x: Rotor) -> Rotor {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t10 - t12;
    let t16 = t4 - t9;
    let t17 = t5 + t8;
    let t18 = t4 + t9;
    let t19 = t10 + t12;
    let t20 = t6 - t7;
    let t21 = t5 - t8;
    let t22 = t6 + t7;
    let t23 = t11 - t13;
    let t24 = x.c0.x * t14;
    let t27 = x.c0.w * t17;
    let t28 = x.c0.y * t18;
    let t32 = x.c0.z * t22;
    let t34 = fma(x.c0.z, t16, t27);
    let t35 = t34 * 2.0;
    let t36 = fma(x.c0.y, t15, t35);
    let t37 = fma(-x.c0.w, t20, t28);
    let t38 = t37 * 2.0;
    let t39 = fma(-x.c0.z, t19, t38);
    let t40 = fma(x.c0.y, t21, t32);
    let t41 = t40 * 2.0;
    let t42 = fma(-x.c0.w, t23, t41);
    return Rotor(vec4<f16>(t24, t36, t39, t42));
}

// The matrix of `x -> v x ~v` on `Rotor` for `Odd` v (`v >> Rotor::slot()`); apply it as `m * x`.
fn odd_matrix_rotor(v: Odd) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m0 + m1;
    let m12 = m2 - m3;
    let m13 = m2 + m3;
    let m14 = m11 + m13;
    let m15 = m10 - m12;
    let m16 = m4 - m9;
    let m17 = m16 * 2.0;
    let m18 = m5 + m8;
    let m19 = m18 * 2.0;
    let m20 = m4 + m9;
    let m21 = m20 * 2.0;
    let m22 = m10 + m12;
    let m23 = -m22;
    let m24 = m7 - m6;
    let m25 = m24 * 2.0;
    let m26 = m5 - m8;
    let m27 = m26 * 2.0;
    let m28 = m6 + m7;
    let m29 = m28 * 2.0;
    let m30 = m13 - m11;
    return mat4x4<f16>(vec4<f16>(m14, 0.0, 0.0, 0.0), vec4<f16>(0.0, m15, m21, m27), vec4<f16>(0.0, m17, m23, m29), vec4<f16>(0.0, m19, m25, m30));
}

// `v x ~v` for a unit `Odd` v and `Rotor` x (`v >> x`).
fn unit_odd_sandwich_rotor(v: Odd, x: Rotor) -> Rotor {
    let t1 = v.c0.y * x.c0.z;
    let t3 = fma(v.c0.x, x.c0.y, t1);
    let t4 = fma(v.c0.z, x.c0.w, t3);
    let t7 = v.c0.w * x.c0.w;
    let t8 = fma(v.c0.x, x.c0.z, t7);
    let t9 = fma(-v.c0.y, x.c0.y, t8);
    let t10 = v.c0.x * x.c0.w;
    let t13 = fma(-v.c0.z, x.c0.y, t10);
    let t14 = fma(-v.c0.w, x.c0.z, t13);
    let t16 = v.c0.z * t14;
    let t17 = v.c0.y * t4;
    let t20 = v.c0.w * t9;
    let t21 = fma(v.c0.y, t9, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.y * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t14, t17);
    let t33 = t32 * 2.0;
    let t35 = fma(-x.c0.z, t29, t33);
    let t36 = fma(v.c0.z, t4, t20);
    let t37 = t36 * 2.0;
    let t39 = fma(-x.c0.w, t29, t37);
    let t40 = x.c0.x * t29;
    return Rotor(vec4<f16>(t40, t31, t35, t39));
}

// The matrix of `x -> v x ~v` on `Rotor` for a unit `Odd` v (`v >> Rotor::slot()`); apply it as `m * x`.
fn unit_odd_matrix_rotor(v: Odd) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m10 - m11;
    let m13 = m4 - m9;
    let m14 = m13 * 2.0;
    let m15 = m5 + m8;
    let m16 = m15 * 2.0;
    let m17 = m4 + m9;
    let m18 = m17 * 2.0;
    let m19 = m10 + m11;
    let m20 = -m19;
    let m21 = m7 - m6;
    let m22 = m21 * 2.0;
    let m23 = m5 - m8;
    let m24 = m23 * 2.0;
    let m25 = m6 + m7;
    let m26 = m25 * 2.0;
    let m27 = m2 + m3;
    let m28 = m0 + m1;
    let m29 = m27 - m28;
    let m30 = m27 + m28;
    return mat4x4<f16>(vec4<f16>(m30, 0.0, 0.0, 0.0), vec4<f16>(0.0, m12, m18, m24), vec4<f16>(0.0, m14, m20, m26), vec4<f16>(0.0, m16, m22, m29));
}

// `v x ~v` for `Odd` v and `Odd` x (`v >> x`).
fn odd_sandwich_odd(v: Odd, x: Odd) -> Odd {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t10 - t12;
    let t15 = t4 - t9;
    let t16 = t5 + t8;
    let t17 = t4 + t9;
    let t18 = t10 + t12;
    let t19 = t6 - t7;
    let t20 = t5 - t8;
    let t21 = t6 + t7;
    let t22 = t11 - t13;
    let t23 = t11 + t13;
    let t26 = x.c0.z * t16;
    let t27 = x.c0.x * t17;
    let t31 = x.c0.y * t21;
    let t33 = x.c0.w * t23;
    let t34 = fma(x.c0.y, t15, t26);
    let t35 = t34 * 2.0;
    let t36 = fma(x.c0.x, t14, t35);
    let t37 = fma(-x.c0.z, t19, t27);
    let t38 = t37 * 2.0;
    let t39 = fma(-x.c0.y, t18, t38);
    let t40 = fma(x.c0.x, t20, t31);
    let t41 = t40 * 2.0;
    let t42 = fma(-x.c0.z, t22, t41);
    return Odd(vec4<f16>(t36, t39, t42, t33));
}

// The matrix of `x -> v x ~v` on `Odd` for `Odd` v (`v >> Odd::slot()`); apply it as `m * x`.
fn odd_matrix_odd(v: Odd) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m0 + m1;
    let m12 = m2 - m3;
    let m13 = m2 + m3;
    let m14 = m10 - m12;
    let m15 = m4 - m9;
    let m16 = m15 * 2.0;
    let m17 = m5 + m8;
    let m18 = m17 * 2.0;
    let m19 = m4 + m9;
    let m20 = m19 * 2.0;
    let m21 = m10 + m12;
    let m22 = -m21;
    let m23 = m7 - m6;
    let m24 = m23 * 2.0;
    let m25 = m5 - m8;
    let m26 = m25 * 2.0;
    let m27 = m6 + m7;
    let m28 = m27 * 2.0;
    let m29 = m13 - m11;
    let m30 = m11 + m13;
    return mat4x4<f16>(vec4<f16>(m14, m20, m26, 0.0), vec4<f16>(m16, m22, m28, 0.0), vec4<f16>(m18, m24, m29, 0.0), vec4<f16>(0.0, 0.0, 0.0, m30));
}

// `v x ~v` for a unit `Odd` v and `Odd` x (`v >> x`).
fn unit_odd_sandwich_odd(v: Odd, x: Odd) -> Odd {
    let t1 = v.c0.y * x.c0.y;
    let t3 = fma(v.c0.x, x.c0.x, t1);
    let t4 = fma(v.c0.z, x.c0.z, t3);
    let t7 = v.c0.w * x.c0.z;
    let t8 = fma(v.c0.x, x.c0.y, t7);
    let t9 = fma(-v.c0.y, x.c0.x, t8);
    let t10 = v.c0.x * x.c0.z;
    let t13 = fma(-v.c0.z, x.c0.x, t10);
    let t14 = fma(-v.c0.w, x.c0.y, t13);
    let t16 = v.c0.z * t14;
    let t17 = v.c0.y * t4;
    let t20 = v.c0.w * t9;
    let t21 = fma(v.c0.y, t9, t16);
    let t24 = v.c0.y * v.c0.y;
    let t26 = v.c0.w * v.c0.w;
    let t27 = fma(v.c0.x, v.c0.x, t24);
    let t28 = fma(v.c0.z, v.c0.z, t26);
    let t29 = t27 + t28;
    let t30 = x.c0.x * t29;
    let t31 = fma(t21, 2.0, t30);
    let t32 = fma(-v.c0.w, t14, t17);
    let t33 = t32 * 2.0;
    let t35 = fma(-x.c0.y, t29, t33);
    let t36 = fma(v.c0.z, t4, t20);
    let t37 = t36 * 2.0;
    let t39 = fma(-x.c0.z, t29, t37);
    let t40 = x.c0.w * t29;
    return Odd(vec4<f16>(t31, t35, t39, t40));
}

// The matrix of `x -> v x ~v` on `Odd` for a unit `Odd` v (`v >> Odd::slot()`); apply it as `m * x`.
fn unit_odd_matrix_odd(v: Odd) -> mat4x4<f16> {
    let m0 = v.c0.x * v.c0.x;
    let m1 = v.c0.y * v.c0.y;
    let m2 = v.c0.z * v.c0.z;
    let m3 = v.c0.w * v.c0.w;
    let m4 = v.c0.x * v.c0.y;
    let m5 = v.c0.x * v.c0.z;
    let m6 = v.c0.x * v.c0.w;
    let m7 = v.c0.y * v.c0.z;
    let m8 = v.c0.y * v.c0.w;
    let m9 = v.c0.z * v.c0.w;
    let m10 = m0 - m1;
    let m11 = m2 - m3;
    let m12 = m10 - m11;
    let m13 = m4 - m9;
    let m14 = m13 * 2.0;
    let m15 = m5 + m8;
    let m16 = m15 * 2.0;
    let m17 = m4 + m9;
    let m18 = m17 * 2.0;
    let m19 = m10 + m11;
    let m20 = -m19;
    let m21 = m7 - m6;
    let m22 = m21 * 2.0;
    let m23 = m5 - m8;
    let m24 = m23 * 2.0;
    let m25 = m6 + m7;
    let m26 = m25 * 2.0;
    let m27 = m2 + m3;
    let m28 = m0 + m1;
    let m29 = m27 - m28;
    let m30 = m27 + m28;
    return mat4x4<f16>(vec4<f16>(m12, m18, m24, 0.0), vec4<f16>(m14, m20, m26, 0.0), vec4<f16>(m16, m22, m29, 0.0), vec4<f16>(0.0, 0.0, 0.0, m30));
}

// `v x ~v` for `Odd` v and `Multivector` x (`v >> x`).
fn odd_sandwich_multivector(v: Odd, x: Multivector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t10 - t12;
    let t16 = t4 - t9;
    let t17 = t5 + t8;
    let t18 = t4 + t9;
    let t19 = t10 + t12;
    let t20 = t6 - t7;
    let t21 = t5 - t8;
    let t22 = t6 + t7;
    let t23 = t11 - t13;
    let t24 = x.c0.x * t14;
    let t27 = x.c0.w * t17;
    let t28 = x.c0.y * t18;
    let t32 = x.c0.z * t22;
    let t36 = x.c1.z * t17;
    let t37 = x.c1.x * t18;
    let t41 = x.c1.y * t22;
    let t43 = x.c1.w * t14;
    let t44 = fma(x.c0.z, t16, t27);
    let t45 = t44 * 2.0;
    let t46 = fma(x.c0.y, t15, t45);
    let t47 = fma(-x.c0.w, t20, t28);
    let t48 = t47 * 2.0;
    let t49 = fma(-x.c0.z, t19, t48);
    let t50 = fma(x.c0.y, t21, t32);
    let t51 = t50 * 2.0;
    let t52 = fma(-x.c0.w, t23, t51);
    let t53 = fma(x.c1.y, t16, t36);
    let t54 = t53 * 2.0;
    let t55 = fma(x.c1.x, t15, t54);
    let t56 = fma(-x.c1.z, t20, t37);
    let t57 = t56 * 2.0;
    let t58 = fma(-x.c1.y, t19, t57);
    let t59 = fma(x.c1.x, t21, t41);
    let t60 = t59 * 2.0;
    let t61 = fma(-x.c1.z, t23, t60);
    return Multivector(vec4<f16>(t24, t46, t49, t52), vec4<f16>(t55, t58, t61, t43));
}

// `v x ~v` for a unit `Odd` v and `Multivector` x (`v >> x`).
fn unit_odd_sandwich_multivector(v: Odd, x: Multivector) -> Multivector {
    let t0 = v.c0.x * v.c0.x;
    let t1 = v.c0.y * v.c0.y;
    let t2 = v.c0.z * v.c0.z;
    let t3 = v.c0.w * v.c0.w;
    let t4 = v.c0.x * v.c0.y;
    let t5 = v.c0.x * v.c0.z;
    let t6 = v.c0.x * v.c0.w;
    let t7 = v.c0.y * v.c0.z;
    let t8 = v.c0.y * v.c0.w;
    let t9 = v.c0.z * v.c0.w;
    let t10 = t0 - t1;
    let t11 = t0 + t1;
    let t12 = t2 - t3;
    let t13 = t2 + t3;
    let t14 = t11 + t13;
    let t15 = t10 - t12;
    let t16 = t4 - t9;
    let t17 = t5 + t8;
    let t18 = t4 + t9;
    let t19 = t10 + t12;
    let t20 = t6 - t7;
    let t21 = t5 - t8;
    let t22 = t6 + t7;
    let t23 = t11 - t13;
    let t24 = x.c0.x * t14;
    let t27 = x.c0.w * t17;
    let t28 = x.c0.y * t18;
    let t32 = x.c0.z * t22;
    let t36 = x.c1.z * t17;
    let t37 = x.c1.x * t18;
    let t41 = x.c1.y * t22;
    let t43 = x.c1.w * t14;
    let t44 = fma(x.c0.z, t16, t27);
    let t45 = t44 * 2.0;
    let t46 = fma(x.c0.y, t15, t45);
    let t47 = fma(-x.c0.w, t20, t28);
    let t48 = t47 * 2.0;
    let t49 = fma(-x.c0.z, t19, t48);
    let t50 = fma(x.c0.y, t21, t32);
    let t51 = t50 * 2.0;
    let t52 = fma(-x.c0.w, t23, t51);
    let t53 = fma(x.c1.y, t16, t36);
    let t54 = t53 * 2.0;
    let t55 = fma(x.c1.x, t15, t54);
    let t56 = fma(-x.c1.z, t20, t37);
    let t57 = t56 * 2.0;
    let t58 = fma(-x.c1.y, t19, t57);
    let t59 = fma(x.c1.x, t21, t41);
    let t60 = t59 * 2.0;
    let t61 = fma(-x.c1.z, t23, t60);
    return Multivector(vec4<f16>(t24, t46, t49, t52), vec4<f16>(t55, t58, t61, t43));
}

// `exp(B) = C + S B` for `B² = lambda + mu I` with `I² = 0` and `lambda <= 0`, as
// `[C, C_I, S, S_I]`: `C = cos a`, `S = sin a / a` with `a = sqrt(-lambda)`, and the `I` parts
// `mu S / 2` and `mu S'`, `S' = (S - C) / (2 a²)` (series near `a = 0`, see gax_core::study).
fn study_exp_rotation(lambda: f32, mu: f32) -> vec4<f32> {
    let a2 = max(-lambda, 0.0);
    let a = sqrt(a2);
    let sn = sin(a);
    let cs = cos(a);
    let inv = 1.0 / a;
    let s = select(sn * inv, 1.0 + a2 * ((-1.0 / 6.0) + a2 * ((1.0 / 120.0) + a2 * (-1.0 / 5040.0))), a2 < 1e-4);
    var ds = (-8.0 / 355687428096000.0);
    ds = ds * a2 + (7.0 / 1307674368000.0);
    ds = ds * a2 + (-6.0 / 6227020800.0);
    ds = ds * a2 + (5.0 / 39916800.0);
    ds = ds * a2 + (-4.0 / 362880.0);
    ds = ds * a2 + (3.0 / 5040.0);
    ds = ds * a2 + (-2.0 / 120.0);
    ds = ds * a2 + (1.0 / 6.0);
    let d = select((s - cs) * inv * inv * 0.5, ds, a2 < 0.25);
    return vec4<f32>(cs, mu * s * 0.5, s, mu * d);
}

// `log R = h0 P + h1 I P` for a unit versor `R = c + P` with `c = c0 + c1 I`,
// `P² = u0 + u1 I`, `I² = 0`, `u0 <= 0`, as `[h0, h1]`. The rotation half-angle is in
// `[0, pi]`; at `R = -T` (a translation times -1) the result is `log(-R)` (see gax_core::study).
fn study_log_rotation(c0: f32, c1: f32, u0: f32, u1: f32) -> vec2<f32> {
    let s2 = max(-u0, 0.0);
    let s = sqrt(s2);
    let theta = atan2(s, c0);
    let n = c0 * c0 + s2;
    let ic = 1.0 / c0;
    let t2 = s2 * ic * ic;
    let key = select(select(0.0, 1.0, 0.0 < s2), t2, 0.0 < c0);
    let hs = ic * (1.0 + t2 * ((-1.0 / 3.0) + t2 * ((1.0 / 5.0) + t2 * (-1.0 / 7.0))));
    let h0 = select(theta / s, hs, key < 1e-6);
    var g = (-12.0 / 25.0);
    g = g * t2 + (11.0 / 23.0);
    g = g * t2 + (-10.0 / 21.0);
    g = g * t2 + (9.0 / 19.0);
    g = g * t2 + (-8.0 / 17.0);
    g = g * t2 + (7.0 / 15.0);
    g = g * t2 + (-6.0 / 13.0);
    g = g * t2 + (5.0 / 11.0);
    g = g * t2 + (-4.0 / 9.0);
    g = g * t2 + (3.0 / 7.0);
    g = g * t2 + (-2.0 / 5.0);
    g = g * t2 + (1.0 / 3.0);
    let gs = select((theta - c0 * s / n) / (s2 * s * 2.0), g * ic * ic * ic, key < (1.0 / 25.0));
    return vec2<f32>(h0, -c1 / n + u1 * gs);
}

// `1 / sqrt(|a|)`.
fn study_rsqrt_abs(a: f32) -> f32 {
    return 1.0 / sqrt(abs(a));
}

